/*
SpatialFlow API

Real-time geospatial automation platform API.  ## Authentication  **API Key:** Include `X-API-Key` header **JWT Token:** Include `Authorization: Bearer <token>` header  ## Rate Limits  - Authenticated: 1,000 requests per hour (per API key, JWT, or session) - Anonymous: 100 requests per hour  ## Webhook Verification  Outbound webhooks include HMAC-SHA256 signatures in `X-SF-Signature` header.  ## Support  - Documentation: https://docs.spatialflow.io - GitHub: https://github.com/spatialflow/spatialflow - Email: support@spatialflow.io     

API version: v1.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package generated

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the PresignedUrlResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PresignedUrlResponse{}

// PresignedUrlResponse struct for PresignedUrlResponse
type PresignedUrlResponse struct {
	UploadUrl string `json:"upload_url"`
	Key string `json:"key"`
	ExpiresIn int32 `json:"expires_in"`
	FileType string `json:"file_type"`
	Filename string `json:"filename"`
	FileId string `json:"file_id"`
	ContentType string `json:"content_type"`
}

type _PresignedUrlResponse PresignedUrlResponse

// NewPresignedUrlResponse instantiates a new PresignedUrlResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPresignedUrlResponse(uploadUrl string, key string, expiresIn int32, fileType string, filename string, fileId string, contentType string) *PresignedUrlResponse {
	this := PresignedUrlResponse{}
	this.UploadUrl = uploadUrl
	this.Key = key
	this.ExpiresIn = expiresIn
	this.FileType = fileType
	this.Filename = filename
	this.FileId = fileId
	this.ContentType = contentType
	return &this
}

// NewPresignedUrlResponseWithDefaults instantiates a new PresignedUrlResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPresignedUrlResponseWithDefaults() *PresignedUrlResponse {
	this := PresignedUrlResponse{}
	return &this
}

// GetUploadUrl returns the UploadUrl field value
func (o *PresignedUrlResponse) GetUploadUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.UploadUrl
}

// GetUploadUrlOk returns a tuple with the UploadUrl field value
// and a boolean to check if the value has been set.
func (o *PresignedUrlResponse) GetUploadUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UploadUrl, true
}

// SetUploadUrl sets field value
func (o *PresignedUrlResponse) SetUploadUrl(v string) {
	o.UploadUrl = v
}

// GetKey returns the Key field value
func (o *PresignedUrlResponse) GetKey() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Key
}

// GetKeyOk returns a tuple with the Key field value
// and a boolean to check if the value has been set.
func (o *PresignedUrlResponse) GetKeyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Key, true
}

// SetKey sets field value
func (o *PresignedUrlResponse) SetKey(v string) {
	o.Key = v
}

// GetExpiresIn returns the ExpiresIn field value
func (o *PresignedUrlResponse) GetExpiresIn() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.ExpiresIn
}

// GetExpiresInOk returns a tuple with the ExpiresIn field value
// and a boolean to check if the value has been set.
func (o *PresignedUrlResponse) GetExpiresInOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ExpiresIn, true
}

// SetExpiresIn sets field value
func (o *PresignedUrlResponse) SetExpiresIn(v int32) {
	o.ExpiresIn = v
}

// GetFileType returns the FileType field value
func (o *PresignedUrlResponse) GetFileType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.FileType
}

// GetFileTypeOk returns a tuple with the FileType field value
// and a boolean to check if the value has been set.
func (o *PresignedUrlResponse) GetFileTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.FileType, true
}

// SetFileType sets field value
func (o *PresignedUrlResponse) SetFileType(v string) {
	o.FileType = v
}

// GetFilename returns the Filename field value
func (o *PresignedUrlResponse) GetFilename() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Filename
}

// GetFilenameOk returns a tuple with the Filename field value
// and a boolean to check if the value has been set.
func (o *PresignedUrlResponse) GetFilenameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Filename, true
}

// SetFilename sets field value
func (o *PresignedUrlResponse) SetFilename(v string) {
	o.Filename = v
}

// GetFileId returns the FileId field value
func (o *PresignedUrlResponse) GetFileId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.FileId
}

// GetFileIdOk returns a tuple with the FileId field value
// and a boolean to check if the value has been set.
func (o *PresignedUrlResponse) GetFileIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.FileId, true
}

// SetFileId sets field value
func (o *PresignedUrlResponse) SetFileId(v string) {
	o.FileId = v
}

// GetContentType returns the ContentType field value
func (o *PresignedUrlResponse) GetContentType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ContentType
}

// GetContentTypeOk returns a tuple with the ContentType field value
// and a boolean to check if the value has been set.
func (o *PresignedUrlResponse) GetContentTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ContentType, true
}

// SetContentType sets field value
func (o *PresignedUrlResponse) SetContentType(v string) {
	o.ContentType = v
}

func (o PresignedUrlResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PresignedUrlResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["upload_url"] = o.UploadUrl
	toSerialize["key"] = o.Key
	toSerialize["expires_in"] = o.ExpiresIn
	toSerialize["file_type"] = o.FileType
	toSerialize["filename"] = o.Filename
	toSerialize["file_id"] = o.FileId
	toSerialize["content_type"] = o.ContentType
	return toSerialize, nil
}

func (o *PresignedUrlResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"upload_url",
		"key",
		"expires_in",
		"file_type",
		"filename",
		"file_id",
		"content_type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPresignedUrlResponse := _PresignedUrlResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varPresignedUrlResponse)

	if err != nil {
		return err
	}

	*o = PresignedUrlResponse(varPresignedUrlResponse)

	return err
}

type NullablePresignedUrlResponse struct {
	value *PresignedUrlResponse
	isSet bool
}

func (v NullablePresignedUrlResponse) Get() *PresignedUrlResponse {
	return v.value
}

func (v *NullablePresignedUrlResponse) Set(val *PresignedUrlResponse) {
	v.value = val
	v.isSet = true
}

func (v NullablePresignedUrlResponse) IsSet() bool {
	return v.isSet
}

func (v *NullablePresignedUrlResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePresignedUrlResponse(val *PresignedUrlResponse) *NullablePresignedUrlResponse {
	return &NullablePresignedUrlResponse{value: val, isSet: true}
}

func (v NullablePresignedUrlResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePresignedUrlResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


