/*
SpatialFlow API

Real-time geospatial automation platform API.  ## Authentication  **API Key:** Include `X-API-Key` header **JWT Token:** Include `Authorization: Bearer <token>` header  ## Rate Limits  - Authenticated: 1,000 requests per hour (per API key, JWT, or session) - Anonymous: 100 requests per hour  ## Webhook Verification  Outbound webhooks include HMAC-SHA256 signatures in `X-SF-Signature` header.  ## Support  - Documentation: https://docs.spatialflow.io - GitHub: https://github.com/spatialflow/spatialflow - Email: support@spatialflow.io     

API version: v1.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package generated

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ConfigurationUpdateResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ConfigurationUpdateResponse{}

// ConfigurationUpdateResponse Response for configuration update.
type ConfigurationUpdateResponse struct {
	Success bool `json:"success"`
	RequiresRestart bool `json:"requires_restart"`
	Error NullableString `json:"error,omitempty"`
	EffectiveValue NullableAnyOf `json:"effective_value,omitempty"`
}

type _ConfigurationUpdateResponse ConfigurationUpdateResponse

// NewConfigurationUpdateResponse instantiates a new ConfigurationUpdateResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewConfigurationUpdateResponse(success bool, requiresRestart bool) *ConfigurationUpdateResponse {
	this := ConfigurationUpdateResponse{}
	this.Success = success
	this.RequiresRestart = requiresRestart
	return &this
}

// NewConfigurationUpdateResponseWithDefaults instantiates a new ConfigurationUpdateResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewConfigurationUpdateResponseWithDefaults() *ConfigurationUpdateResponse {
	this := ConfigurationUpdateResponse{}
	return &this
}

// GetSuccess returns the Success field value
func (o *ConfigurationUpdateResponse) GetSuccess() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Success
}

// GetSuccessOk returns a tuple with the Success field value
// and a boolean to check if the value has been set.
func (o *ConfigurationUpdateResponse) GetSuccessOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Success, true
}

// SetSuccess sets field value
func (o *ConfigurationUpdateResponse) SetSuccess(v bool) {
	o.Success = v
}

// GetRequiresRestart returns the RequiresRestart field value
func (o *ConfigurationUpdateResponse) GetRequiresRestart() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.RequiresRestart
}

// GetRequiresRestartOk returns a tuple with the RequiresRestart field value
// and a boolean to check if the value has been set.
func (o *ConfigurationUpdateResponse) GetRequiresRestartOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RequiresRestart, true
}

// SetRequiresRestart sets field value
func (o *ConfigurationUpdateResponse) SetRequiresRestart(v bool) {
	o.RequiresRestart = v
}

// GetError returns the Error field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ConfigurationUpdateResponse) GetError() string {
	if o == nil || IsNil(o.Error.Get()) {
		var ret string
		return ret
	}
	return *o.Error.Get()
}

// GetErrorOk returns a tuple with the Error field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ConfigurationUpdateResponse) GetErrorOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Error.Get(), o.Error.IsSet()
}

// HasError returns a boolean if a field has been set.
func (o *ConfigurationUpdateResponse) HasError() bool {
	if o != nil && o.Error.IsSet() {
		return true
	}

	return false
}

// SetError gets a reference to the given NullableString and assigns it to the Error field.
func (o *ConfigurationUpdateResponse) SetError(v string) {
	o.Error.Set(&v)
}
// SetErrorNil sets the value for Error to be an explicit nil
func (o *ConfigurationUpdateResponse) SetErrorNil() {
	o.Error.Set(nil)
}

// UnsetError ensures that no value is present for Error, not even an explicit nil
func (o *ConfigurationUpdateResponse) UnsetError() {
	o.Error.Unset()
}

// GetEffectiveValue returns the EffectiveValue field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ConfigurationUpdateResponse) GetEffectiveValue() AnyOf {
	if o == nil || IsNil(o.EffectiveValue.Get()) {
		var ret AnyOf
		return ret
	}
	return *o.EffectiveValue.Get()
}

// GetEffectiveValueOk returns a tuple with the EffectiveValue field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ConfigurationUpdateResponse) GetEffectiveValueOk() (*AnyOf, bool) {
	if o == nil {
		return nil, false
	}
	return o.EffectiveValue.Get(), o.EffectiveValue.IsSet()
}

// HasEffectiveValue returns a boolean if a field has been set.
func (o *ConfigurationUpdateResponse) HasEffectiveValue() bool {
	if o != nil && o.EffectiveValue.IsSet() {
		return true
	}

	return false
}

// SetEffectiveValue gets a reference to the given NullableAnyOf and assigns it to the EffectiveValue field.
func (o *ConfigurationUpdateResponse) SetEffectiveValue(v AnyOf) {
	o.EffectiveValue.Set(&v)
}
// SetEffectiveValueNil sets the value for EffectiveValue to be an explicit nil
func (o *ConfigurationUpdateResponse) SetEffectiveValueNil() {
	o.EffectiveValue.Set(nil)
}

// UnsetEffectiveValue ensures that no value is present for EffectiveValue, not even an explicit nil
func (o *ConfigurationUpdateResponse) UnsetEffectiveValue() {
	o.EffectiveValue.Unset()
}

func (o ConfigurationUpdateResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ConfigurationUpdateResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["success"] = o.Success
	toSerialize["requires_restart"] = o.RequiresRestart
	if o.Error.IsSet() {
		toSerialize["error"] = o.Error.Get()
	}
	if o.EffectiveValue.IsSet() {
		toSerialize["effective_value"] = o.EffectiveValue.Get()
	}
	return toSerialize, nil
}

func (o *ConfigurationUpdateResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"success",
		"requires_restart",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varConfigurationUpdateResponse := _ConfigurationUpdateResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varConfigurationUpdateResponse)

	if err != nil {
		return err
	}

	*o = ConfigurationUpdateResponse(varConfigurationUpdateResponse)

	return err
}

type NullableConfigurationUpdateResponse struct {
	value *ConfigurationUpdateResponse
	isSet bool
}

func (v NullableConfigurationUpdateResponse) Get() *ConfigurationUpdateResponse {
	return v.value
}

func (v *NullableConfigurationUpdateResponse) Set(val *ConfigurationUpdateResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableConfigurationUpdateResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableConfigurationUpdateResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableConfigurationUpdateResponse(val *ConfigurationUpdateResponse) *NullableConfigurationUpdateResponse {
	return &NullableConfigurationUpdateResponse{value: val, isSet: true}
}

func (v NullableConfigurationUpdateResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableConfigurationUpdateResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


