/*
SpatialFlow API

Real-time geospatial automation platform API.  ## Authentication  **API Key:** Include `X-API-Key` header **JWT Token:** Include `Authorization: Bearer <token>` header  ## Rate Limits  - Authenticated: 1,000 requests per hour (per API key, JWT, or session) - Anonymous: 100 requests per hour  ## Webhook Verification  Outbound webhooks include HMAC-SHA256 signatures in `X-SF-Signature` header.  ## Support  - Documentation: https://docs.spatialflow.io/ - Email: support@spatialflow.io     

API version: v1.36.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package generated

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the DeviceOut type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DeviceOut{}

// DeviceOut struct for DeviceOut
type DeviceOut struct {
	Id string `json:"id"`
	DeviceId string `json:"device_id"`
	Name string `json:"name"`
	DeviceType string `json:"device_type"`
	RegistrationSource string `json:"registration_source"`
	IsActive bool `json:"is_active"`
	IsExample *bool `json:"is_example,omitempty"`
	ShiftStatus string `json:"shift_status"`
	ShiftStartedAt NullableTime `json:"shift_started_at,omitempty"`
	ShiftPausedAt NullableTime `json:"shift_paused_at,omitempty"`
	ShiftEndedAt NullableTime `json:"shift_ended_at,omitempty"`
	ShiftResumedAt NullableTime `json:"shift_resumed_at,omitempty"`
	LastLocation NullableLatLonOut `json:"last_location,omitempty"`
	LastLocationTime NullableTime `json:"last_location_time,omitempty"`
	LastAccuracy NullableFloat32 `json:"last_accuracy,omitempty"`
	LastHeading NullableFloat32 `json:"last_heading,omitempty"`
	LastBatteryLevel NullableInt32 `json:"last_battery_level,omitempty"`
	LastBatteryCharging NullableBool `json:"last_battery_charging,omitempty"`
	LastBatteryTime NullableTime `json:"last_battery_time,omitempty"`
	DriverName *string `json:"driver_name,omitempty"`
	VehicleLabel *string `json:"vehicle_label,omitempty"`
	EmployeeId *string `json:"employee_id,omitempty"`
	LicensePlate *string `json:"license_plate,omitempty"`
	Group *string `json:"group,omitempty"`
	Status string `json:"status"`
	LastSeenSeconds NullableInt32 `json:"last_seen_seconds,omitempty"`
	Parked *bool `json:"parked,omitempty"`
	TodayDistanceMeters NullableFloat32 `json:"today_distance_meters,omitempty"`
	CurrentSessionNotes *string `json:"current_session_notes,omitempty"`
	CurrentSession NullableCurrentSessionOut `json:"current_session,omitempty"`
	InGeofenceIds []string `json:"in_geofence_ids,omitempty"`
	InGeofenceEntries map[string]string `json:"in_geofence_entries,omitempty"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type _DeviceOut DeviceOut

// NewDeviceOut instantiates a new DeviceOut object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDeviceOut(id string, deviceId string, name string, deviceType string, registrationSource string, isActive bool, shiftStatus string, status string, createdAt time.Time, updatedAt time.Time) *DeviceOut {
	this := DeviceOut{}
	this.Id = id
	this.DeviceId = deviceId
	this.Name = name
	this.DeviceType = deviceType
	this.RegistrationSource = registrationSource
	this.IsActive = isActive
	var isExample bool = false
	this.IsExample = &isExample
	this.ShiftStatus = shiftStatus
	var driverName string = ""
	this.DriverName = &driverName
	var vehicleLabel string = ""
	this.VehicleLabel = &vehicleLabel
	var employeeId string = ""
	this.EmployeeId = &employeeId
	var licensePlate string = ""
	this.LicensePlate = &licensePlate
	var group string = ""
	this.Group = &group
	this.Status = status
	var parked bool = false
	this.Parked = &parked
	var currentSessionNotes string = ""
	this.CurrentSessionNotes = &currentSessionNotes
	this.CreatedAt = createdAt
	this.UpdatedAt = updatedAt
	return &this
}

// NewDeviceOutWithDefaults instantiates a new DeviceOut object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDeviceOutWithDefaults() *DeviceOut {
	this := DeviceOut{}
	var isExample bool = false
	this.IsExample = &isExample
	var driverName string = ""
	this.DriverName = &driverName
	var vehicleLabel string = ""
	this.VehicleLabel = &vehicleLabel
	var employeeId string = ""
	this.EmployeeId = &employeeId
	var licensePlate string = ""
	this.LicensePlate = &licensePlate
	var group string = ""
	this.Group = &group
	var parked bool = false
	this.Parked = &parked
	var currentSessionNotes string = ""
	this.CurrentSessionNotes = &currentSessionNotes
	return &this
}

// GetId returns the Id field value
func (o *DeviceOut) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *DeviceOut) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *DeviceOut) SetId(v string) {
	o.Id = v
}

// GetDeviceId returns the DeviceId field value
func (o *DeviceOut) GetDeviceId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DeviceId
}

// GetDeviceIdOk returns a tuple with the DeviceId field value
// and a boolean to check if the value has been set.
func (o *DeviceOut) GetDeviceIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DeviceId, true
}

// SetDeviceId sets field value
func (o *DeviceOut) SetDeviceId(v string) {
	o.DeviceId = v
}

// GetName returns the Name field value
func (o *DeviceOut) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *DeviceOut) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *DeviceOut) SetName(v string) {
	o.Name = v
}

// GetDeviceType returns the DeviceType field value
func (o *DeviceOut) GetDeviceType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DeviceType
}

// GetDeviceTypeOk returns a tuple with the DeviceType field value
// and a boolean to check if the value has been set.
func (o *DeviceOut) GetDeviceTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DeviceType, true
}

// SetDeviceType sets field value
func (o *DeviceOut) SetDeviceType(v string) {
	o.DeviceType = v
}

// GetRegistrationSource returns the RegistrationSource field value
func (o *DeviceOut) GetRegistrationSource() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.RegistrationSource
}

// GetRegistrationSourceOk returns a tuple with the RegistrationSource field value
// and a boolean to check if the value has been set.
func (o *DeviceOut) GetRegistrationSourceOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RegistrationSource, true
}

// SetRegistrationSource sets field value
func (o *DeviceOut) SetRegistrationSource(v string) {
	o.RegistrationSource = v
}

// GetIsActive returns the IsActive field value
func (o *DeviceOut) GetIsActive() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.IsActive
}

// GetIsActiveOk returns a tuple with the IsActive field value
// and a boolean to check if the value has been set.
func (o *DeviceOut) GetIsActiveOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IsActive, true
}

// SetIsActive sets field value
func (o *DeviceOut) SetIsActive(v bool) {
	o.IsActive = v
}

// GetIsExample returns the IsExample field value if set, zero value otherwise.
func (o *DeviceOut) GetIsExample() bool {
	if o == nil || IsNil(o.IsExample) {
		var ret bool
		return ret
	}
	return *o.IsExample
}

// GetIsExampleOk returns a tuple with the IsExample field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeviceOut) GetIsExampleOk() (*bool, bool) {
	if o == nil || IsNil(o.IsExample) {
		return nil, false
	}
	return o.IsExample, true
}

// HasIsExample returns a boolean if a field has been set.
func (o *DeviceOut) HasIsExample() bool {
	if o != nil && !IsNil(o.IsExample) {
		return true
	}

	return false
}

// SetIsExample gets a reference to the given bool and assigns it to the IsExample field.
func (o *DeviceOut) SetIsExample(v bool) {
	o.IsExample = &v
}

// GetShiftStatus returns the ShiftStatus field value
func (o *DeviceOut) GetShiftStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ShiftStatus
}

// GetShiftStatusOk returns a tuple with the ShiftStatus field value
// and a boolean to check if the value has been set.
func (o *DeviceOut) GetShiftStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ShiftStatus, true
}

// SetShiftStatus sets field value
func (o *DeviceOut) SetShiftStatus(v string) {
	o.ShiftStatus = v
}

// GetShiftStartedAt returns the ShiftStartedAt field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *DeviceOut) GetShiftStartedAt() time.Time {
	if o == nil || IsNil(o.ShiftStartedAt.Get()) {
		var ret time.Time
		return ret
	}
	return *o.ShiftStartedAt.Get()
}

// GetShiftStartedAtOk returns a tuple with the ShiftStartedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *DeviceOut) GetShiftStartedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.ShiftStartedAt.Get(), o.ShiftStartedAt.IsSet()
}

// HasShiftStartedAt returns a boolean if a field has been set.
func (o *DeviceOut) HasShiftStartedAt() bool {
	if o != nil && o.ShiftStartedAt.IsSet() {
		return true
	}

	return false
}

// SetShiftStartedAt gets a reference to the given NullableTime and assigns it to the ShiftStartedAt field.
func (o *DeviceOut) SetShiftStartedAt(v time.Time) {
	o.ShiftStartedAt.Set(&v)
}
// SetShiftStartedAtNil sets the value for ShiftStartedAt to be an explicit nil
func (o *DeviceOut) SetShiftStartedAtNil() {
	o.ShiftStartedAt.Set(nil)
}

// UnsetShiftStartedAt ensures that no value is present for ShiftStartedAt, not even an explicit nil
func (o *DeviceOut) UnsetShiftStartedAt() {
	o.ShiftStartedAt.Unset()
}

// GetShiftPausedAt returns the ShiftPausedAt field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *DeviceOut) GetShiftPausedAt() time.Time {
	if o == nil || IsNil(o.ShiftPausedAt.Get()) {
		var ret time.Time
		return ret
	}
	return *o.ShiftPausedAt.Get()
}

// GetShiftPausedAtOk returns a tuple with the ShiftPausedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *DeviceOut) GetShiftPausedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.ShiftPausedAt.Get(), o.ShiftPausedAt.IsSet()
}

// HasShiftPausedAt returns a boolean if a field has been set.
func (o *DeviceOut) HasShiftPausedAt() bool {
	if o != nil && o.ShiftPausedAt.IsSet() {
		return true
	}

	return false
}

// SetShiftPausedAt gets a reference to the given NullableTime and assigns it to the ShiftPausedAt field.
func (o *DeviceOut) SetShiftPausedAt(v time.Time) {
	o.ShiftPausedAt.Set(&v)
}
// SetShiftPausedAtNil sets the value for ShiftPausedAt to be an explicit nil
func (o *DeviceOut) SetShiftPausedAtNil() {
	o.ShiftPausedAt.Set(nil)
}

// UnsetShiftPausedAt ensures that no value is present for ShiftPausedAt, not even an explicit nil
func (o *DeviceOut) UnsetShiftPausedAt() {
	o.ShiftPausedAt.Unset()
}

// GetShiftEndedAt returns the ShiftEndedAt field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *DeviceOut) GetShiftEndedAt() time.Time {
	if o == nil || IsNil(o.ShiftEndedAt.Get()) {
		var ret time.Time
		return ret
	}
	return *o.ShiftEndedAt.Get()
}

// GetShiftEndedAtOk returns a tuple with the ShiftEndedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *DeviceOut) GetShiftEndedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.ShiftEndedAt.Get(), o.ShiftEndedAt.IsSet()
}

// HasShiftEndedAt returns a boolean if a field has been set.
func (o *DeviceOut) HasShiftEndedAt() bool {
	if o != nil && o.ShiftEndedAt.IsSet() {
		return true
	}

	return false
}

// SetShiftEndedAt gets a reference to the given NullableTime and assigns it to the ShiftEndedAt field.
func (o *DeviceOut) SetShiftEndedAt(v time.Time) {
	o.ShiftEndedAt.Set(&v)
}
// SetShiftEndedAtNil sets the value for ShiftEndedAt to be an explicit nil
func (o *DeviceOut) SetShiftEndedAtNil() {
	o.ShiftEndedAt.Set(nil)
}

// UnsetShiftEndedAt ensures that no value is present for ShiftEndedAt, not even an explicit nil
func (o *DeviceOut) UnsetShiftEndedAt() {
	o.ShiftEndedAt.Unset()
}

// GetShiftResumedAt returns the ShiftResumedAt field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *DeviceOut) GetShiftResumedAt() time.Time {
	if o == nil || IsNil(o.ShiftResumedAt.Get()) {
		var ret time.Time
		return ret
	}
	return *o.ShiftResumedAt.Get()
}

// GetShiftResumedAtOk returns a tuple with the ShiftResumedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *DeviceOut) GetShiftResumedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.ShiftResumedAt.Get(), o.ShiftResumedAt.IsSet()
}

// HasShiftResumedAt returns a boolean if a field has been set.
func (o *DeviceOut) HasShiftResumedAt() bool {
	if o != nil && o.ShiftResumedAt.IsSet() {
		return true
	}

	return false
}

// SetShiftResumedAt gets a reference to the given NullableTime and assigns it to the ShiftResumedAt field.
func (o *DeviceOut) SetShiftResumedAt(v time.Time) {
	o.ShiftResumedAt.Set(&v)
}
// SetShiftResumedAtNil sets the value for ShiftResumedAt to be an explicit nil
func (o *DeviceOut) SetShiftResumedAtNil() {
	o.ShiftResumedAt.Set(nil)
}

// UnsetShiftResumedAt ensures that no value is present for ShiftResumedAt, not even an explicit nil
func (o *DeviceOut) UnsetShiftResumedAt() {
	o.ShiftResumedAt.Unset()
}

// GetLastLocation returns the LastLocation field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *DeviceOut) GetLastLocation() LatLonOut {
	if o == nil || IsNil(o.LastLocation.Get()) {
		var ret LatLonOut
		return ret
	}
	return *o.LastLocation.Get()
}

// GetLastLocationOk returns a tuple with the LastLocation field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *DeviceOut) GetLastLocationOk() (*LatLonOut, bool) {
	if o == nil {
		return nil, false
	}
	return o.LastLocation.Get(), o.LastLocation.IsSet()
}

// HasLastLocation returns a boolean if a field has been set.
func (o *DeviceOut) HasLastLocation() bool {
	if o != nil && o.LastLocation.IsSet() {
		return true
	}

	return false
}

// SetLastLocation gets a reference to the given NullableLatLonOut and assigns it to the LastLocation field.
func (o *DeviceOut) SetLastLocation(v LatLonOut) {
	o.LastLocation.Set(&v)
}
// SetLastLocationNil sets the value for LastLocation to be an explicit nil
func (o *DeviceOut) SetLastLocationNil() {
	o.LastLocation.Set(nil)
}

// UnsetLastLocation ensures that no value is present for LastLocation, not even an explicit nil
func (o *DeviceOut) UnsetLastLocation() {
	o.LastLocation.Unset()
}

// GetLastLocationTime returns the LastLocationTime field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *DeviceOut) GetLastLocationTime() time.Time {
	if o == nil || IsNil(o.LastLocationTime.Get()) {
		var ret time.Time
		return ret
	}
	return *o.LastLocationTime.Get()
}

// GetLastLocationTimeOk returns a tuple with the LastLocationTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *DeviceOut) GetLastLocationTimeOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.LastLocationTime.Get(), o.LastLocationTime.IsSet()
}

// HasLastLocationTime returns a boolean if a field has been set.
func (o *DeviceOut) HasLastLocationTime() bool {
	if o != nil && o.LastLocationTime.IsSet() {
		return true
	}

	return false
}

// SetLastLocationTime gets a reference to the given NullableTime and assigns it to the LastLocationTime field.
func (o *DeviceOut) SetLastLocationTime(v time.Time) {
	o.LastLocationTime.Set(&v)
}
// SetLastLocationTimeNil sets the value for LastLocationTime to be an explicit nil
func (o *DeviceOut) SetLastLocationTimeNil() {
	o.LastLocationTime.Set(nil)
}

// UnsetLastLocationTime ensures that no value is present for LastLocationTime, not even an explicit nil
func (o *DeviceOut) UnsetLastLocationTime() {
	o.LastLocationTime.Unset()
}

// GetLastAccuracy returns the LastAccuracy field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *DeviceOut) GetLastAccuracy() float32 {
	if o == nil || IsNil(o.LastAccuracy.Get()) {
		var ret float32
		return ret
	}
	return *o.LastAccuracy.Get()
}

// GetLastAccuracyOk returns a tuple with the LastAccuracy field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *DeviceOut) GetLastAccuracyOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return o.LastAccuracy.Get(), o.LastAccuracy.IsSet()
}

// HasLastAccuracy returns a boolean if a field has been set.
func (o *DeviceOut) HasLastAccuracy() bool {
	if o != nil && o.LastAccuracy.IsSet() {
		return true
	}

	return false
}

// SetLastAccuracy gets a reference to the given NullableFloat32 and assigns it to the LastAccuracy field.
func (o *DeviceOut) SetLastAccuracy(v float32) {
	o.LastAccuracy.Set(&v)
}
// SetLastAccuracyNil sets the value for LastAccuracy to be an explicit nil
func (o *DeviceOut) SetLastAccuracyNil() {
	o.LastAccuracy.Set(nil)
}

// UnsetLastAccuracy ensures that no value is present for LastAccuracy, not even an explicit nil
func (o *DeviceOut) UnsetLastAccuracy() {
	o.LastAccuracy.Unset()
}

// GetLastHeading returns the LastHeading field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *DeviceOut) GetLastHeading() float32 {
	if o == nil || IsNil(o.LastHeading.Get()) {
		var ret float32
		return ret
	}
	return *o.LastHeading.Get()
}

// GetLastHeadingOk returns a tuple with the LastHeading field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *DeviceOut) GetLastHeadingOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return o.LastHeading.Get(), o.LastHeading.IsSet()
}

// HasLastHeading returns a boolean if a field has been set.
func (o *DeviceOut) HasLastHeading() bool {
	if o != nil && o.LastHeading.IsSet() {
		return true
	}

	return false
}

// SetLastHeading gets a reference to the given NullableFloat32 and assigns it to the LastHeading field.
func (o *DeviceOut) SetLastHeading(v float32) {
	o.LastHeading.Set(&v)
}
// SetLastHeadingNil sets the value for LastHeading to be an explicit nil
func (o *DeviceOut) SetLastHeadingNil() {
	o.LastHeading.Set(nil)
}

// UnsetLastHeading ensures that no value is present for LastHeading, not even an explicit nil
func (o *DeviceOut) UnsetLastHeading() {
	o.LastHeading.Unset()
}

// GetLastBatteryLevel returns the LastBatteryLevel field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *DeviceOut) GetLastBatteryLevel() int32 {
	if o == nil || IsNil(o.LastBatteryLevel.Get()) {
		var ret int32
		return ret
	}
	return *o.LastBatteryLevel.Get()
}

// GetLastBatteryLevelOk returns a tuple with the LastBatteryLevel field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *DeviceOut) GetLastBatteryLevelOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.LastBatteryLevel.Get(), o.LastBatteryLevel.IsSet()
}

// HasLastBatteryLevel returns a boolean if a field has been set.
func (o *DeviceOut) HasLastBatteryLevel() bool {
	if o != nil && o.LastBatteryLevel.IsSet() {
		return true
	}

	return false
}

// SetLastBatteryLevel gets a reference to the given NullableInt32 and assigns it to the LastBatteryLevel field.
func (o *DeviceOut) SetLastBatteryLevel(v int32) {
	o.LastBatteryLevel.Set(&v)
}
// SetLastBatteryLevelNil sets the value for LastBatteryLevel to be an explicit nil
func (o *DeviceOut) SetLastBatteryLevelNil() {
	o.LastBatteryLevel.Set(nil)
}

// UnsetLastBatteryLevel ensures that no value is present for LastBatteryLevel, not even an explicit nil
func (o *DeviceOut) UnsetLastBatteryLevel() {
	o.LastBatteryLevel.Unset()
}

// GetLastBatteryCharging returns the LastBatteryCharging field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *DeviceOut) GetLastBatteryCharging() bool {
	if o == nil || IsNil(o.LastBatteryCharging.Get()) {
		var ret bool
		return ret
	}
	return *o.LastBatteryCharging.Get()
}

// GetLastBatteryChargingOk returns a tuple with the LastBatteryCharging field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *DeviceOut) GetLastBatteryChargingOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return o.LastBatteryCharging.Get(), o.LastBatteryCharging.IsSet()
}

// HasLastBatteryCharging returns a boolean if a field has been set.
func (o *DeviceOut) HasLastBatteryCharging() bool {
	if o != nil && o.LastBatteryCharging.IsSet() {
		return true
	}

	return false
}

// SetLastBatteryCharging gets a reference to the given NullableBool and assigns it to the LastBatteryCharging field.
func (o *DeviceOut) SetLastBatteryCharging(v bool) {
	o.LastBatteryCharging.Set(&v)
}
// SetLastBatteryChargingNil sets the value for LastBatteryCharging to be an explicit nil
func (o *DeviceOut) SetLastBatteryChargingNil() {
	o.LastBatteryCharging.Set(nil)
}

// UnsetLastBatteryCharging ensures that no value is present for LastBatteryCharging, not even an explicit nil
func (o *DeviceOut) UnsetLastBatteryCharging() {
	o.LastBatteryCharging.Unset()
}

// GetLastBatteryTime returns the LastBatteryTime field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *DeviceOut) GetLastBatteryTime() time.Time {
	if o == nil || IsNil(o.LastBatteryTime.Get()) {
		var ret time.Time
		return ret
	}
	return *o.LastBatteryTime.Get()
}

// GetLastBatteryTimeOk returns a tuple with the LastBatteryTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *DeviceOut) GetLastBatteryTimeOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.LastBatteryTime.Get(), o.LastBatteryTime.IsSet()
}

// HasLastBatteryTime returns a boolean if a field has been set.
func (o *DeviceOut) HasLastBatteryTime() bool {
	if o != nil && o.LastBatteryTime.IsSet() {
		return true
	}

	return false
}

// SetLastBatteryTime gets a reference to the given NullableTime and assigns it to the LastBatteryTime field.
func (o *DeviceOut) SetLastBatteryTime(v time.Time) {
	o.LastBatteryTime.Set(&v)
}
// SetLastBatteryTimeNil sets the value for LastBatteryTime to be an explicit nil
func (o *DeviceOut) SetLastBatteryTimeNil() {
	o.LastBatteryTime.Set(nil)
}

// UnsetLastBatteryTime ensures that no value is present for LastBatteryTime, not even an explicit nil
func (o *DeviceOut) UnsetLastBatteryTime() {
	o.LastBatteryTime.Unset()
}

// GetDriverName returns the DriverName field value if set, zero value otherwise.
func (o *DeviceOut) GetDriverName() string {
	if o == nil || IsNil(o.DriverName) {
		var ret string
		return ret
	}
	return *o.DriverName
}

// GetDriverNameOk returns a tuple with the DriverName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeviceOut) GetDriverNameOk() (*string, bool) {
	if o == nil || IsNil(o.DriverName) {
		return nil, false
	}
	return o.DriverName, true
}

// HasDriverName returns a boolean if a field has been set.
func (o *DeviceOut) HasDriverName() bool {
	if o != nil && !IsNil(o.DriverName) {
		return true
	}

	return false
}

// SetDriverName gets a reference to the given string and assigns it to the DriverName field.
func (o *DeviceOut) SetDriverName(v string) {
	o.DriverName = &v
}

// GetVehicleLabel returns the VehicleLabel field value if set, zero value otherwise.
func (o *DeviceOut) GetVehicleLabel() string {
	if o == nil || IsNil(o.VehicleLabel) {
		var ret string
		return ret
	}
	return *o.VehicleLabel
}

// GetVehicleLabelOk returns a tuple with the VehicleLabel field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeviceOut) GetVehicleLabelOk() (*string, bool) {
	if o == nil || IsNil(o.VehicleLabel) {
		return nil, false
	}
	return o.VehicleLabel, true
}

// HasVehicleLabel returns a boolean if a field has been set.
func (o *DeviceOut) HasVehicleLabel() bool {
	if o != nil && !IsNil(o.VehicleLabel) {
		return true
	}

	return false
}

// SetVehicleLabel gets a reference to the given string and assigns it to the VehicleLabel field.
func (o *DeviceOut) SetVehicleLabel(v string) {
	o.VehicleLabel = &v
}

// GetEmployeeId returns the EmployeeId field value if set, zero value otherwise.
func (o *DeviceOut) GetEmployeeId() string {
	if o == nil || IsNil(o.EmployeeId) {
		var ret string
		return ret
	}
	return *o.EmployeeId
}

// GetEmployeeIdOk returns a tuple with the EmployeeId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeviceOut) GetEmployeeIdOk() (*string, bool) {
	if o == nil || IsNil(o.EmployeeId) {
		return nil, false
	}
	return o.EmployeeId, true
}

// HasEmployeeId returns a boolean if a field has been set.
func (o *DeviceOut) HasEmployeeId() bool {
	if o != nil && !IsNil(o.EmployeeId) {
		return true
	}

	return false
}

// SetEmployeeId gets a reference to the given string and assigns it to the EmployeeId field.
func (o *DeviceOut) SetEmployeeId(v string) {
	o.EmployeeId = &v
}

// GetLicensePlate returns the LicensePlate field value if set, zero value otherwise.
func (o *DeviceOut) GetLicensePlate() string {
	if o == nil || IsNil(o.LicensePlate) {
		var ret string
		return ret
	}
	return *o.LicensePlate
}

// GetLicensePlateOk returns a tuple with the LicensePlate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeviceOut) GetLicensePlateOk() (*string, bool) {
	if o == nil || IsNil(o.LicensePlate) {
		return nil, false
	}
	return o.LicensePlate, true
}

// HasLicensePlate returns a boolean if a field has been set.
func (o *DeviceOut) HasLicensePlate() bool {
	if o != nil && !IsNil(o.LicensePlate) {
		return true
	}

	return false
}

// SetLicensePlate gets a reference to the given string and assigns it to the LicensePlate field.
func (o *DeviceOut) SetLicensePlate(v string) {
	o.LicensePlate = &v
}

// GetGroup returns the Group field value if set, zero value otherwise.
func (o *DeviceOut) GetGroup() string {
	if o == nil || IsNil(o.Group) {
		var ret string
		return ret
	}
	return *o.Group
}

// GetGroupOk returns a tuple with the Group field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeviceOut) GetGroupOk() (*string, bool) {
	if o == nil || IsNil(o.Group) {
		return nil, false
	}
	return o.Group, true
}

// HasGroup returns a boolean if a field has been set.
func (o *DeviceOut) HasGroup() bool {
	if o != nil && !IsNil(o.Group) {
		return true
	}

	return false
}

// SetGroup gets a reference to the given string and assigns it to the Group field.
func (o *DeviceOut) SetGroup(v string) {
	o.Group = &v
}

// GetStatus returns the Status field value
func (o *DeviceOut) GetStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *DeviceOut) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *DeviceOut) SetStatus(v string) {
	o.Status = v
}

// GetLastSeenSeconds returns the LastSeenSeconds field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *DeviceOut) GetLastSeenSeconds() int32 {
	if o == nil || IsNil(o.LastSeenSeconds.Get()) {
		var ret int32
		return ret
	}
	return *o.LastSeenSeconds.Get()
}

// GetLastSeenSecondsOk returns a tuple with the LastSeenSeconds field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *DeviceOut) GetLastSeenSecondsOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.LastSeenSeconds.Get(), o.LastSeenSeconds.IsSet()
}

// HasLastSeenSeconds returns a boolean if a field has been set.
func (o *DeviceOut) HasLastSeenSeconds() bool {
	if o != nil && o.LastSeenSeconds.IsSet() {
		return true
	}

	return false
}

// SetLastSeenSeconds gets a reference to the given NullableInt32 and assigns it to the LastSeenSeconds field.
func (o *DeviceOut) SetLastSeenSeconds(v int32) {
	o.LastSeenSeconds.Set(&v)
}
// SetLastSeenSecondsNil sets the value for LastSeenSeconds to be an explicit nil
func (o *DeviceOut) SetLastSeenSecondsNil() {
	o.LastSeenSeconds.Set(nil)
}

// UnsetLastSeenSeconds ensures that no value is present for LastSeenSeconds, not even an explicit nil
func (o *DeviceOut) UnsetLastSeenSeconds() {
	o.LastSeenSeconds.Unset()
}

// GetParked returns the Parked field value if set, zero value otherwise.
func (o *DeviceOut) GetParked() bool {
	if o == nil || IsNil(o.Parked) {
		var ret bool
		return ret
	}
	return *o.Parked
}

// GetParkedOk returns a tuple with the Parked field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeviceOut) GetParkedOk() (*bool, bool) {
	if o == nil || IsNil(o.Parked) {
		return nil, false
	}
	return o.Parked, true
}

// HasParked returns a boolean if a field has been set.
func (o *DeviceOut) HasParked() bool {
	if o != nil && !IsNil(o.Parked) {
		return true
	}

	return false
}

// SetParked gets a reference to the given bool and assigns it to the Parked field.
func (o *DeviceOut) SetParked(v bool) {
	o.Parked = &v
}

// GetTodayDistanceMeters returns the TodayDistanceMeters field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *DeviceOut) GetTodayDistanceMeters() float32 {
	if o == nil || IsNil(o.TodayDistanceMeters.Get()) {
		var ret float32
		return ret
	}
	return *o.TodayDistanceMeters.Get()
}

// GetTodayDistanceMetersOk returns a tuple with the TodayDistanceMeters field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *DeviceOut) GetTodayDistanceMetersOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return o.TodayDistanceMeters.Get(), o.TodayDistanceMeters.IsSet()
}

// HasTodayDistanceMeters returns a boolean if a field has been set.
func (o *DeviceOut) HasTodayDistanceMeters() bool {
	if o != nil && o.TodayDistanceMeters.IsSet() {
		return true
	}

	return false
}

// SetTodayDistanceMeters gets a reference to the given NullableFloat32 and assigns it to the TodayDistanceMeters field.
func (o *DeviceOut) SetTodayDistanceMeters(v float32) {
	o.TodayDistanceMeters.Set(&v)
}
// SetTodayDistanceMetersNil sets the value for TodayDistanceMeters to be an explicit nil
func (o *DeviceOut) SetTodayDistanceMetersNil() {
	o.TodayDistanceMeters.Set(nil)
}

// UnsetTodayDistanceMeters ensures that no value is present for TodayDistanceMeters, not even an explicit nil
func (o *DeviceOut) UnsetTodayDistanceMeters() {
	o.TodayDistanceMeters.Unset()
}

// GetCurrentSessionNotes returns the CurrentSessionNotes field value if set, zero value otherwise.
func (o *DeviceOut) GetCurrentSessionNotes() string {
	if o == nil || IsNil(o.CurrentSessionNotes) {
		var ret string
		return ret
	}
	return *o.CurrentSessionNotes
}

// GetCurrentSessionNotesOk returns a tuple with the CurrentSessionNotes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeviceOut) GetCurrentSessionNotesOk() (*string, bool) {
	if o == nil || IsNil(o.CurrentSessionNotes) {
		return nil, false
	}
	return o.CurrentSessionNotes, true
}

// HasCurrentSessionNotes returns a boolean if a field has been set.
func (o *DeviceOut) HasCurrentSessionNotes() bool {
	if o != nil && !IsNil(o.CurrentSessionNotes) {
		return true
	}

	return false
}

// SetCurrentSessionNotes gets a reference to the given string and assigns it to the CurrentSessionNotes field.
func (o *DeviceOut) SetCurrentSessionNotes(v string) {
	o.CurrentSessionNotes = &v
}

// GetCurrentSession returns the CurrentSession field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *DeviceOut) GetCurrentSession() CurrentSessionOut {
	if o == nil || IsNil(o.CurrentSession.Get()) {
		var ret CurrentSessionOut
		return ret
	}
	return *o.CurrentSession.Get()
}

// GetCurrentSessionOk returns a tuple with the CurrentSession field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *DeviceOut) GetCurrentSessionOk() (*CurrentSessionOut, bool) {
	if o == nil {
		return nil, false
	}
	return o.CurrentSession.Get(), o.CurrentSession.IsSet()
}

// HasCurrentSession returns a boolean if a field has been set.
func (o *DeviceOut) HasCurrentSession() bool {
	if o != nil && o.CurrentSession.IsSet() {
		return true
	}

	return false
}

// SetCurrentSession gets a reference to the given NullableCurrentSessionOut and assigns it to the CurrentSession field.
func (o *DeviceOut) SetCurrentSession(v CurrentSessionOut) {
	o.CurrentSession.Set(&v)
}
// SetCurrentSessionNil sets the value for CurrentSession to be an explicit nil
func (o *DeviceOut) SetCurrentSessionNil() {
	o.CurrentSession.Set(nil)
}

// UnsetCurrentSession ensures that no value is present for CurrentSession, not even an explicit nil
func (o *DeviceOut) UnsetCurrentSession() {
	o.CurrentSession.Unset()
}

// GetInGeofenceIds returns the InGeofenceIds field value if set, zero value otherwise.
func (o *DeviceOut) GetInGeofenceIds() []string {
	if o == nil || IsNil(o.InGeofenceIds) {
		var ret []string
		return ret
	}
	return o.InGeofenceIds
}

// GetInGeofenceIdsOk returns a tuple with the InGeofenceIds field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeviceOut) GetInGeofenceIdsOk() ([]string, bool) {
	if o == nil || IsNil(o.InGeofenceIds) {
		return nil, false
	}
	return o.InGeofenceIds, true
}

// HasInGeofenceIds returns a boolean if a field has been set.
func (o *DeviceOut) HasInGeofenceIds() bool {
	if o != nil && !IsNil(o.InGeofenceIds) {
		return true
	}

	return false
}

// SetInGeofenceIds gets a reference to the given []string and assigns it to the InGeofenceIds field.
func (o *DeviceOut) SetInGeofenceIds(v []string) {
	o.InGeofenceIds = v
}

// GetInGeofenceEntries returns the InGeofenceEntries field value if set, zero value otherwise.
func (o *DeviceOut) GetInGeofenceEntries() map[string]string {
	if o == nil || IsNil(o.InGeofenceEntries) {
		var ret map[string]string
		return ret
	}
	return o.InGeofenceEntries
}

// GetInGeofenceEntriesOk returns a tuple with the InGeofenceEntries field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeviceOut) GetInGeofenceEntriesOk() (map[string]string, bool) {
	if o == nil || IsNil(o.InGeofenceEntries) {
		return map[string]string{}, false
	}
	return o.InGeofenceEntries, true
}

// HasInGeofenceEntries returns a boolean if a field has been set.
func (o *DeviceOut) HasInGeofenceEntries() bool {
	if o != nil && !IsNil(o.InGeofenceEntries) {
		return true
	}

	return false
}

// SetInGeofenceEntries gets a reference to the given map[string]string and assigns it to the InGeofenceEntries field.
func (o *DeviceOut) SetInGeofenceEntries(v map[string]string) {
	o.InGeofenceEntries = v
}

// GetCreatedAt returns the CreatedAt field value
func (o *DeviceOut) GetCreatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *DeviceOut) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *DeviceOut) SetCreatedAt(v time.Time) {
	o.CreatedAt = v
}

// GetUpdatedAt returns the UpdatedAt field value
func (o *DeviceOut) GetUpdatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value
// and a boolean to check if the value has been set.
func (o *DeviceOut) GetUpdatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UpdatedAt, true
}

// SetUpdatedAt sets field value
func (o *DeviceOut) SetUpdatedAt(v time.Time) {
	o.UpdatedAt = v
}

func (o DeviceOut) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DeviceOut) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["device_id"] = o.DeviceId
	toSerialize["name"] = o.Name
	toSerialize["device_type"] = o.DeviceType
	toSerialize["registration_source"] = o.RegistrationSource
	toSerialize["is_active"] = o.IsActive
	if !IsNil(o.IsExample) {
		toSerialize["is_example"] = o.IsExample
	}
	toSerialize["shift_status"] = o.ShiftStatus
	if o.ShiftStartedAt.IsSet() {
		toSerialize["shift_started_at"] = o.ShiftStartedAt.Get()
	}
	if o.ShiftPausedAt.IsSet() {
		toSerialize["shift_paused_at"] = o.ShiftPausedAt.Get()
	}
	if o.ShiftEndedAt.IsSet() {
		toSerialize["shift_ended_at"] = o.ShiftEndedAt.Get()
	}
	if o.ShiftResumedAt.IsSet() {
		toSerialize["shift_resumed_at"] = o.ShiftResumedAt.Get()
	}
	if o.LastLocation.IsSet() {
		toSerialize["last_location"] = o.LastLocation.Get()
	}
	if o.LastLocationTime.IsSet() {
		toSerialize["last_location_time"] = o.LastLocationTime.Get()
	}
	if o.LastAccuracy.IsSet() {
		toSerialize["last_accuracy"] = o.LastAccuracy.Get()
	}
	if o.LastHeading.IsSet() {
		toSerialize["last_heading"] = o.LastHeading.Get()
	}
	if o.LastBatteryLevel.IsSet() {
		toSerialize["last_battery_level"] = o.LastBatteryLevel.Get()
	}
	if o.LastBatteryCharging.IsSet() {
		toSerialize["last_battery_charging"] = o.LastBatteryCharging.Get()
	}
	if o.LastBatteryTime.IsSet() {
		toSerialize["last_battery_time"] = o.LastBatteryTime.Get()
	}
	if !IsNil(o.DriverName) {
		toSerialize["driver_name"] = o.DriverName
	}
	if !IsNil(o.VehicleLabel) {
		toSerialize["vehicle_label"] = o.VehicleLabel
	}
	if !IsNil(o.EmployeeId) {
		toSerialize["employee_id"] = o.EmployeeId
	}
	if !IsNil(o.LicensePlate) {
		toSerialize["license_plate"] = o.LicensePlate
	}
	if !IsNil(o.Group) {
		toSerialize["group"] = o.Group
	}
	toSerialize["status"] = o.Status
	if o.LastSeenSeconds.IsSet() {
		toSerialize["last_seen_seconds"] = o.LastSeenSeconds.Get()
	}
	if !IsNil(o.Parked) {
		toSerialize["parked"] = o.Parked
	}
	if o.TodayDistanceMeters.IsSet() {
		toSerialize["today_distance_meters"] = o.TodayDistanceMeters.Get()
	}
	if !IsNil(o.CurrentSessionNotes) {
		toSerialize["current_session_notes"] = o.CurrentSessionNotes
	}
	if o.CurrentSession.IsSet() {
		toSerialize["current_session"] = o.CurrentSession.Get()
	}
	if !IsNil(o.InGeofenceIds) {
		toSerialize["in_geofence_ids"] = o.InGeofenceIds
	}
	if !IsNil(o.InGeofenceEntries) {
		toSerialize["in_geofence_entries"] = o.InGeofenceEntries
	}
	toSerialize["created_at"] = o.CreatedAt
	toSerialize["updated_at"] = o.UpdatedAt
	return toSerialize, nil
}

func (o *DeviceOut) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"device_id",
		"name",
		"device_type",
		"registration_source",
		"is_active",
		"shift_status",
		"status",
		"created_at",
		"updated_at",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDeviceOut := _DeviceOut{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDeviceOut)

	if err != nil {
		return err
	}

	*o = DeviceOut(varDeviceOut)

	return err
}

type NullableDeviceOut struct {
	value *DeviceOut
	isSet bool
}

func (v NullableDeviceOut) Get() *DeviceOut {
	return v.value
}

func (v *NullableDeviceOut) Set(val *DeviceOut) {
	v.value = val
	v.isSet = true
}

func (v NullableDeviceOut) IsSet() bool {
	return v.isSet
}

func (v *NullableDeviceOut) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDeviceOut(val *DeviceOut) *NullableDeviceOut {
	return &NullableDeviceOut{value: val, isSet: true}
}

func (v NullableDeviceOut) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDeviceOut) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


