/*
SpatialFlow API

Real-time geospatial automation platform API.  ## Authentication  **API Key:** Include `X-API-Key` header **JWT Token:** Include `Authorization: Bearer <token>` header  ## Rate Limits  - Authenticated: 1,000 requests per hour (per API key, JWT, or session) - Anonymous: 100 requests per hour  ## Webhook Verification  Outbound webhooks include HMAC-SHA256 signatures in `X-SF-Signature` header.  ## Support  - Documentation: https://docs.spatialflow.io/ - Email: support@spatialflow.io     

API version: v1.36.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package generated

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the InvitationIssuedOut type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &InvitationIssuedOut{}

// InvitationIssuedOut Response for the two endpoints that MINT a token: create and resend.  Carries `invite_link` -- byte for byte the same link the invitation email contains -- so the caller who just created the invitation can render it as a QR code for on-site check-in without a second token transport. The token is stored hashed and is unrecoverable afterwards, which is why the listing schema deliberately still omits it: `InvitationOut` never exposes a token, and only the authenticated owner/manager making this very request sees it.
type InvitationIssuedOut struct {
	Id string `json:"id"`
	Email string `json:"email"`
	Role string `json:"role"`
	Status string `json:"status"`
	CreatedAt time.Time `json:"created_at"`
	ExpiresAt time.Time `json:"expires_at"`
	InvitedByEmail NullableString `json:"invited_by_email,omitempty"`
	InviteLink string `json:"invite_link"`
	InviteTtlHours int32 `json:"invite_ttl_hours"`
}

type _InvitationIssuedOut InvitationIssuedOut

// NewInvitationIssuedOut instantiates a new InvitationIssuedOut object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInvitationIssuedOut(id string, email string, role string, status string, createdAt time.Time, expiresAt time.Time, inviteLink string, inviteTtlHours int32) *InvitationIssuedOut {
	this := InvitationIssuedOut{}
	this.Id = id
	this.Email = email
	this.Role = role
	this.Status = status
	this.CreatedAt = createdAt
	this.ExpiresAt = expiresAt
	this.InviteLink = inviteLink
	this.InviteTtlHours = inviteTtlHours
	return &this
}

// NewInvitationIssuedOutWithDefaults instantiates a new InvitationIssuedOut object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInvitationIssuedOutWithDefaults() *InvitationIssuedOut {
	this := InvitationIssuedOut{}
	return &this
}

// GetId returns the Id field value
func (o *InvitationIssuedOut) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *InvitationIssuedOut) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *InvitationIssuedOut) SetId(v string) {
	o.Id = v
}

// GetEmail returns the Email field value
func (o *InvitationIssuedOut) GetEmail() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Email
}

// GetEmailOk returns a tuple with the Email field value
// and a boolean to check if the value has been set.
func (o *InvitationIssuedOut) GetEmailOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Email, true
}

// SetEmail sets field value
func (o *InvitationIssuedOut) SetEmail(v string) {
	o.Email = v
}

// GetRole returns the Role field value
func (o *InvitationIssuedOut) GetRole() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Role
}

// GetRoleOk returns a tuple with the Role field value
// and a boolean to check if the value has been set.
func (o *InvitationIssuedOut) GetRoleOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Role, true
}

// SetRole sets field value
func (o *InvitationIssuedOut) SetRole(v string) {
	o.Role = v
}

// GetStatus returns the Status field value
func (o *InvitationIssuedOut) GetStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *InvitationIssuedOut) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *InvitationIssuedOut) SetStatus(v string) {
	o.Status = v
}

// GetCreatedAt returns the CreatedAt field value
func (o *InvitationIssuedOut) GetCreatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *InvitationIssuedOut) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *InvitationIssuedOut) SetCreatedAt(v time.Time) {
	o.CreatedAt = v
}

// GetExpiresAt returns the ExpiresAt field value
func (o *InvitationIssuedOut) GetExpiresAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.ExpiresAt
}

// GetExpiresAtOk returns a tuple with the ExpiresAt field value
// and a boolean to check if the value has been set.
func (o *InvitationIssuedOut) GetExpiresAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ExpiresAt, true
}

// SetExpiresAt sets field value
func (o *InvitationIssuedOut) SetExpiresAt(v time.Time) {
	o.ExpiresAt = v
}

// GetInvitedByEmail returns the InvitedByEmail field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *InvitationIssuedOut) GetInvitedByEmail() string {
	if o == nil || IsNil(o.InvitedByEmail.Get()) {
		var ret string
		return ret
	}
	return *o.InvitedByEmail.Get()
}

// GetInvitedByEmailOk returns a tuple with the InvitedByEmail field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *InvitationIssuedOut) GetInvitedByEmailOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.InvitedByEmail.Get(), o.InvitedByEmail.IsSet()
}

// HasInvitedByEmail returns a boolean if a field has been set.
func (o *InvitationIssuedOut) HasInvitedByEmail() bool {
	if o != nil && o.InvitedByEmail.IsSet() {
		return true
	}

	return false
}

// SetInvitedByEmail gets a reference to the given NullableString and assigns it to the InvitedByEmail field.
func (o *InvitationIssuedOut) SetInvitedByEmail(v string) {
	o.InvitedByEmail.Set(&v)
}
// SetInvitedByEmailNil sets the value for InvitedByEmail to be an explicit nil
func (o *InvitationIssuedOut) SetInvitedByEmailNil() {
	o.InvitedByEmail.Set(nil)
}

// UnsetInvitedByEmail ensures that no value is present for InvitedByEmail, not even an explicit nil
func (o *InvitationIssuedOut) UnsetInvitedByEmail() {
	o.InvitedByEmail.Unset()
}

// GetInviteLink returns the InviteLink field value
func (o *InvitationIssuedOut) GetInviteLink() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.InviteLink
}

// GetInviteLinkOk returns a tuple with the InviteLink field value
// and a boolean to check if the value has been set.
func (o *InvitationIssuedOut) GetInviteLinkOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.InviteLink, true
}

// SetInviteLink sets field value
func (o *InvitationIssuedOut) SetInviteLink(v string) {
	o.InviteLink = v
}

// GetInviteTtlHours returns the InviteTtlHours field value
func (o *InvitationIssuedOut) GetInviteTtlHours() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.InviteTtlHours
}

// GetInviteTtlHoursOk returns a tuple with the InviteTtlHours field value
// and a boolean to check if the value has been set.
func (o *InvitationIssuedOut) GetInviteTtlHoursOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.InviteTtlHours, true
}

// SetInviteTtlHours sets field value
func (o *InvitationIssuedOut) SetInviteTtlHours(v int32) {
	o.InviteTtlHours = v
}

func (o InvitationIssuedOut) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o InvitationIssuedOut) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["email"] = o.Email
	toSerialize["role"] = o.Role
	toSerialize["status"] = o.Status
	toSerialize["created_at"] = o.CreatedAt
	toSerialize["expires_at"] = o.ExpiresAt
	if o.InvitedByEmail.IsSet() {
		toSerialize["invited_by_email"] = o.InvitedByEmail.Get()
	}
	toSerialize["invite_link"] = o.InviteLink
	toSerialize["invite_ttl_hours"] = o.InviteTtlHours
	return toSerialize, nil
}

func (o *InvitationIssuedOut) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"email",
		"role",
		"status",
		"created_at",
		"expires_at",
		"invite_link",
		"invite_ttl_hours",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varInvitationIssuedOut := _InvitationIssuedOut{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varInvitationIssuedOut)

	if err != nil {
		return err
	}

	*o = InvitationIssuedOut(varInvitationIssuedOut)

	return err
}

type NullableInvitationIssuedOut struct {
	value *InvitationIssuedOut
	isSet bool
}

func (v NullableInvitationIssuedOut) Get() *InvitationIssuedOut {
	return v.value
}

func (v *NullableInvitationIssuedOut) Set(val *InvitationIssuedOut) {
	v.value = val
	v.isSet = true
}

func (v NullableInvitationIssuedOut) IsSet() bool {
	return v.isSet
}

func (v *NullableInvitationIssuedOut) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInvitationIssuedOut(val *InvitationIssuedOut) *NullableInvitationIssuedOut {
	return &NullableInvitationIssuedOut{value: val, isSet: true}
}

func (v NullableInvitationIssuedOut) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInvitationIssuedOut) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


