/*
SpatialFlow API

Real-time geospatial automation platform API.  ## Authentication  **API Key:** Include `X-API-Key` header **JWT Token:** Include `Authorization: Bearer <token>` header  ## Rate Limits  - Authenticated: 1,000 requests per hour (per API key, JWT, or session) - Anonymous: 100 requests per hour  ## Webhook Verification  Outbound webhooks include HMAC-SHA256 signatures in `X-SF-Signature` header.  ## Support  - Documentation: https://docs.spatialflow.io - GitHub: https://github.com/spatialflow/spatialflow - Email: support@spatialflow.io     

API version: v1.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package generated

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the PrivacyErasureRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PrivacyErasureRequest{}

// PrivacyErasureRequest Request schema for creating privacy erasure job.
type PrivacyErasureRequest struct {
	// Erasure scope: org, device, date_range, tag
	Scope string `json:"scope"`
	FromDate NullableTime `json:"from_date,omitempty"`
	ToDate NullableTime `json:"to_date,omitempty"`
	DeviceIds []string `json:"device_ids,omitempty"`
	Tags []string `json:"tags,omitempty"`
	// If true, estimate deletions without actually deleting
	DryRun *bool `json:"dry_run,omitempty"`
}

type _PrivacyErasureRequest PrivacyErasureRequest

// NewPrivacyErasureRequest instantiates a new PrivacyErasureRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPrivacyErasureRequest(scope string) *PrivacyErasureRequest {
	this := PrivacyErasureRequest{}
	this.Scope = scope
	var dryRun bool = false
	this.DryRun = &dryRun
	return &this
}

// NewPrivacyErasureRequestWithDefaults instantiates a new PrivacyErasureRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPrivacyErasureRequestWithDefaults() *PrivacyErasureRequest {
	this := PrivacyErasureRequest{}
	var dryRun bool = false
	this.DryRun = &dryRun
	return &this
}

// GetScope returns the Scope field value
func (o *PrivacyErasureRequest) GetScope() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Scope
}

// GetScopeOk returns a tuple with the Scope field value
// and a boolean to check if the value has been set.
func (o *PrivacyErasureRequest) GetScopeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Scope, true
}

// SetScope sets field value
func (o *PrivacyErasureRequest) SetScope(v string) {
	o.Scope = v
}

// GetFromDate returns the FromDate field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PrivacyErasureRequest) GetFromDate() time.Time {
	if o == nil || IsNil(o.FromDate.Get()) {
		var ret time.Time
		return ret
	}
	return *o.FromDate.Get()
}

// GetFromDateOk returns a tuple with the FromDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PrivacyErasureRequest) GetFromDateOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.FromDate.Get(), o.FromDate.IsSet()
}

// HasFromDate returns a boolean if a field has been set.
func (o *PrivacyErasureRequest) HasFromDate() bool {
	if o != nil && o.FromDate.IsSet() {
		return true
	}

	return false
}

// SetFromDate gets a reference to the given NullableTime and assigns it to the FromDate field.
func (o *PrivacyErasureRequest) SetFromDate(v time.Time) {
	o.FromDate.Set(&v)
}
// SetFromDateNil sets the value for FromDate to be an explicit nil
func (o *PrivacyErasureRequest) SetFromDateNil() {
	o.FromDate.Set(nil)
}

// UnsetFromDate ensures that no value is present for FromDate, not even an explicit nil
func (o *PrivacyErasureRequest) UnsetFromDate() {
	o.FromDate.Unset()
}

// GetToDate returns the ToDate field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PrivacyErasureRequest) GetToDate() time.Time {
	if o == nil || IsNil(o.ToDate.Get()) {
		var ret time.Time
		return ret
	}
	return *o.ToDate.Get()
}

// GetToDateOk returns a tuple with the ToDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PrivacyErasureRequest) GetToDateOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.ToDate.Get(), o.ToDate.IsSet()
}

// HasToDate returns a boolean if a field has been set.
func (o *PrivacyErasureRequest) HasToDate() bool {
	if o != nil && o.ToDate.IsSet() {
		return true
	}

	return false
}

// SetToDate gets a reference to the given NullableTime and assigns it to the ToDate field.
func (o *PrivacyErasureRequest) SetToDate(v time.Time) {
	o.ToDate.Set(&v)
}
// SetToDateNil sets the value for ToDate to be an explicit nil
func (o *PrivacyErasureRequest) SetToDateNil() {
	o.ToDate.Set(nil)
}

// UnsetToDate ensures that no value is present for ToDate, not even an explicit nil
func (o *PrivacyErasureRequest) UnsetToDate() {
	o.ToDate.Unset()
}

// GetDeviceIds returns the DeviceIds field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PrivacyErasureRequest) GetDeviceIds() []string {
	if o == nil {
		var ret []string
		return ret
	}
	return o.DeviceIds
}

// GetDeviceIdsOk returns a tuple with the DeviceIds field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PrivacyErasureRequest) GetDeviceIdsOk() ([]string, bool) {
	if o == nil || IsNil(o.DeviceIds) {
		return nil, false
	}
	return o.DeviceIds, true
}

// HasDeviceIds returns a boolean if a field has been set.
func (o *PrivacyErasureRequest) HasDeviceIds() bool {
	if o != nil && !IsNil(o.DeviceIds) {
		return true
	}

	return false
}

// SetDeviceIds gets a reference to the given []string and assigns it to the DeviceIds field.
func (o *PrivacyErasureRequest) SetDeviceIds(v []string) {
	o.DeviceIds = v
}

// GetTags returns the Tags field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PrivacyErasureRequest) GetTags() []string {
	if o == nil {
		var ret []string
		return ret
	}
	return o.Tags
}

// GetTagsOk returns a tuple with the Tags field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PrivacyErasureRequest) GetTagsOk() ([]string, bool) {
	if o == nil || IsNil(o.Tags) {
		return nil, false
	}
	return o.Tags, true
}

// HasTags returns a boolean if a field has been set.
func (o *PrivacyErasureRequest) HasTags() bool {
	if o != nil && !IsNil(o.Tags) {
		return true
	}

	return false
}

// SetTags gets a reference to the given []string and assigns it to the Tags field.
func (o *PrivacyErasureRequest) SetTags(v []string) {
	o.Tags = v
}

// GetDryRun returns the DryRun field value if set, zero value otherwise.
func (o *PrivacyErasureRequest) GetDryRun() bool {
	if o == nil || IsNil(o.DryRun) {
		var ret bool
		return ret
	}
	return *o.DryRun
}

// GetDryRunOk returns a tuple with the DryRun field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PrivacyErasureRequest) GetDryRunOk() (*bool, bool) {
	if o == nil || IsNil(o.DryRun) {
		return nil, false
	}
	return o.DryRun, true
}

// HasDryRun returns a boolean if a field has been set.
func (o *PrivacyErasureRequest) HasDryRun() bool {
	if o != nil && !IsNil(o.DryRun) {
		return true
	}

	return false
}

// SetDryRun gets a reference to the given bool and assigns it to the DryRun field.
func (o *PrivacyErasureRequest) SetDryRun(v bool) {
	o.DryRun = &v
}

func (o PrivacyErasureRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PrivacyErasureRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["scope"] = o.Scope
	if o.FromDate.IsSet() {
		toSerialize["from_date"] = o.FromDate.Get()
	}
	if o.ToDate.IsSet() {
		toSerialize["to_date"] = o.ToDate.Get()
	}
	if o.DeviceIds != nil {
		toSerialize["device_ids"] = o.DeviceIds
	}
	if o.Tags != nil {
		toSerialize["tags"] = o.Tags
	}
	if !IsNil(o.DryRun) {
		toSerialize["dry_run"] = o.DryRun
	}
	return toSerialize, nil
}

func (o *PrivacyErasureRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"scope",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPrivacyErasureRequest := _PrivacyErasureRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varPrivacyErasureRequest)

	if err != nil {
		return err
	}

	*o = PrivacyErasureRequest(varPrivacyErasureRequest)

	return err
}

type NullablePrivacyErasureRequest struct {
	value *PrivacyErasureRequest
	isSet bool
}

func (v NullablePrivacyErasureRequest) Get() *PrivacyErasureRequest {
	return v.value
}

func (v *NullablePrivacyErasureRequest) Set(val *PrivacyErasureRequest) {
	v.value = val
	v.isSet = true
}

func (v NullablePrivacyErasureRequest) IsSet() bool {
	return v.isSet
}

func (v *NullablePrivacyErasureRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePrivacyErasureRequest(val *PrivacyErasureRequest) *NullablePrivacyErasureRequest {
	return &NullablePrivacyErasureRequest{value: val, isSet: true}
}

func (v NullablePrivacyErasureRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePrivacyErasureRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


