/*
SpatialFlow API

Real-time geospatial automation platform API.  ## Authentication  **API Key:** Include `X-API-Key` header **JWT Token:** Include `Authorization: Bearer <token>` header  ## Rate Limits  - Authenticated: 1,000 requests per hour (per API key, JWT, or session) - Anonymous: 100 requests per hour  ## Webhook Verification  Outbound webhooks include HMAC-SHA256 signatures in `X-SF-Signature` header.  ## Support  - Documentation: https://docs.spatialflow.io - GitHub: https://github.com/spatialflow/spatialflow - Email: support@spatialflow.io     

API version: v1.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package generated

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the NotesUpdateOut type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &NotesUpdateOut{}

// NotesUpdateOut Response after updating session notes.
type NotesUpdateOut struct {
	Success bool `json:"success"`
	Notes string `json:"notes"`
}

type _NotesUpdateOut NotesUpdateOut

// NewNotesUpdateOut instantiates a new NotesUpdateOut object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewNotesUpdateOut(success bool, notes string) *NotesUpdateOut {
	this := NotesUpdateOut{}
	this.Success = success
	this.Notes = notes
	return &this
}

// NewNotesUpdateOutWithDefaults instantiates a new NotesUpdateOut object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewNotesUpdateOutWithDefaults() *NotesUpdateOut {
	this := NotesUpdateOut{}
	return &this
}

// GetSuccess returns the Success field value
func (o *NotesUpdateOut) GetSuccess() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Success
}

// GetSuccessOk returns a tuple with the Success field value
// and a boolean to check if the value has been set.
func (o *NotesUpdateOut) GetSuccessOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Success, true
}

// SetSuccess sets field value
func (o *NotesUpdateOut) SetSuccess(v bool) {
	o.Success = v
}

// GetNotes returns the Notes field value
func (o *NotesUpdateOut) GetNotes() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Notes
}

// GetNotesOk returns a tuple with the Notes field value
// and a boolean to check if the value has been set.
func (o *NotesUpdateOut) GetNotesOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Notes, true
}

// SetNotes sets field value
func (o *NotesUpdateOut) SetNotes(v string) {
	o.Notes = v
}

func (o NotesUpdateOut) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o NotesUpdateOut) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["success"] = o.Success
	toSerialize["notes"] = o.Notes
	return toSerialize, nil
}

func (o *NotesUpdateOut) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"success",
		"notes",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varNotesUpdateOut := _NotesUpdateOut{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varNotesUpdateOut)

	if err != nil {
		return err
	}

	*o = NotesUpdateOut(varNotesUpdateOut)

	return err
}

type NullableNotesUpdateOut struct {
	value *NotesUpdateOut
	isSet bool
}

func (v NullableNotesUpdateOut) Get() *NotesUpdateOut {
	return v.value
}

func (v *NullableNotesUpdateOut) Set(val *NotesUpdateOut) {
	v.value = val
	v.isSet = true
}

func (v NullableNotesUpdateOut) IsSet() bool {
	return v.isSet
}

func (v *NullableNotesUpdateOut) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNotesUpdateOut(val *NotesUpdateOut) *NullableNotesUpdateOut {
	return &NullableNotesUpdateOut{value: val, isSet: true}
}

func (v NullableNotesUpdateOut) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNotesUpdateOut) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


