/*
SpatialFlow API

Real-time geospatial automation platform API.  ## Authentication  **API Key:** Include `X-API-Key` header **JWT Token:** Include `Authorization: Bearer <token>` header  ## Rate Limits  - Authenticated: 1,000 requests per hour (per API key, JWT, or session) - Anonymous: 100 requests per hour  ## Webhook Verification  Outbound webhooks include HMAC-SHA256 signatures in `X-SF-Signature` header.  ## Support  - Documentation: https://docs.spatialflow.io/ - Email: support@spatialflow.io     

API version: v1.36.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package generated

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the GeofenceWorkflowReferenceOut type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GeofenceWorkflowReferenceOut{}

// GeofenceWorkflowReferenceOut struct for GeofenceWorkflowReferenceOut
type GeofenceWorkflowReferenceOut struct {
	Id string `json:"id"`
	Name string `json:"name"`
	Status string `json:"status"`
	References []string `json:"references"`
}

type _GeofenceWorkflowReferenceOut GeofenceWorkflowReferenceOut

// NewGeofenceWorkflowReferenceOut instantiates a new GeofenceWorkflowReferenceOut object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGeofenceWorkflowReferenceOut(id string, name string, status string, references []string) *GeofenceWorkflowReferenceOut {
	this := GeofenceWorkflowReferenceOut{}
	this.Id = id
	this.Name = name
	this.Status = status
	this.References = references
	return &this
}

// NewGeofenceWorkflowReferenceOutWithDefaults instantiates a new GeofenceWorkflowReferenceOut object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGeofenceWorkflowReferenceOutWithDefaults() *GeofenceWorkflowReferenceOut {
	this := GeofenceWorkflowReferenceOut{}
	return &this
}

// GetId returns the Id field value
func (o *GeofenceWorkflowReferenceOut) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *GeofenceWorkflowReferenceOut) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *GeofenceWorkflowReferenceOut) SetId(v string) {
	o.Id = v
}

// GetName returns the Name field value
func (o *GeofenceWorkflowReferenceOut) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *GeofenceWorkflowReferenceOut) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *GeofenceWorkflowReferenceOut) SetName(v string) {
	o.Name = v
}

// GetStatus returns the Status field value
func (o *GeofenceWorkflowReferenceOut) GetStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *GeofenceWorkflowReferenceOut) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *GeofenceWorkflowReferenceOut) SetStatus(v string) {
	o.Status = v
}

// GetReferences returns the References field value
func (o *GeofenceWorkflowReferenceOut) GetReferences() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.References
}

// GetReferencesOk returns a tuple with the References field value
// and a boolean to check if the value has been set.
func (o *GeofenceWorkflowReferenceOut) GetReferencesOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.References, true
}

// SetReferences sets field value
func (o *GeofenceWorkflowReferenceOut) SetReferences(v []string) {
	o.References = v
}

func (o GeofenceWorkflowReferenceOut) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GeofenceWorkflowReferenceOut) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["name"] = o.Name
	toSerialize["status"] = o.Status
	toSerialize["references"] = o.References
	return toSerialize, nil
}

func (o *GeofenceWorkflowReferenceOut) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"name",
		"status",
		"references",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGeofenceWorkflowReferenceOut := _GeofenceWorkflowReferenceOut{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varGeofenceWorkflowReferenceOut)

	if err != nil {
		return err
	}

	*o = GeofenceWorkflowReferenceOut(varGeofenceWorkflowReferenceOut)

	return err
}

type NullableGeofenceWorkflowReferenceOut struct {
	value *GeofenceWorkflowReferenceOut
	isSet bool
}

func (v NullableGeofenceWorkflowReferenceOut) Get() *GeofenceWorkflowReferenceOut {
	return v.value
}

func (v *NullableGeofenceWorkflowReferenceOut) Set(val *GeofenceWorkflowReferenceOut) {
	v.value = val
	v.isSet = true
}

func (v NullableGeofenceWorkflowReferenceOut) IsSet() bool {
	return v.isSet
}

func (v *NullableGeofenceWorkflowReferenceOut) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGeofenceWorkflowReferenceOut(val *GeofenceWorkflowReferenceOut) *NullableGeofenceWorkflowReferenceOut {
	return &NullableGeofenceWorkflowReferenceOut{value: val, isSet: true}
}

func (v NullableGeofenceWorkflowReferenceOut) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGeofenceWorkflowReferenceOut) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


