/*
SpatialFlow API

Real-time geospatial automation platform API.  ## Authentication  **API Key:** Include `X-API-Key` header **JWT Token:** Include `Authorization: Bearer <token>` header  ## Rate Limits  - Authenticated: 1,000 requests per hour (per API key, JWT, or session) - Anonymous: 100 requests per hour  ## Webhook Verification  Outbound webhooks include HMAC-SHA256 signatures in `X-SF-Signature` header.  ## Support  - Documentation: https://docs.spatialflow.io/ - Email: support@spatialflow.io     

API version: v1.36.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package generated

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the BulkItemInput type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BulkItemInput{}

// BulkItemInput Input item for bulk preview requests.
type BulkItemInput struct {
	Address string `json:"address"`
	Name NullableString `json:"name,omitempty"`
	BufferMeters NullableInt32 `json:"buffer_meters,omitempty"`
	Tags []string `json:"tags,omitempty"`
}

type _BulkItemInput BulkItemInput

// NewBulkItemInput instantiates a new BulkItemInput object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBulkItemInput(address string) *BulkItemInput {
	this := BulkItemInput{}
	this.Address = address
	return &this
}

// NewBulkItemInputWithDefaults instantiates a new BulkItemInput object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBulkItemInputWithDefaults() *BulkItemInput {
	this := BulkItemInput{}
	return &this
}

// GetAddress returns the Address field value
func (o *BulkItemInput) GetAddress() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Address
}

// GetAddressOk returns a tuple with the Address field value
// and a boolean to check if the value has been set.
func (o *BulkItemInput) GetAddressOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Address, true
}

// SetAddress sets field value
func (o *BulkItemInput) SetAddress(v string) {
	o.Address = v
}

// GetName returns the Name field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *BulkItemInput) GetName() string {
	if o == nil || IsNil(o.Name.Get()) {
		var ret string
		return ret
	}
	return *o.Name.Get()
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *BulkItemInput) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Name.Get(), o.Name.IsSet()
}

// HasName returns a boolean if a field has been set.
func (o *BulkItemInput) HasName() bool {
	if o != nil && o.Name.IsSet() {
		return true
	}

	return false
}

// SetName gets a reference to the given NullableString and assigns it to the Name field.
func (o *BulkItemInput) SetName(v string) {
	o.Name.Set(&v)
}
// SetNameNil sets the value for Name to be an explicit nil
func (o *BulkItemInput) SetNameNil() {
	o.Name.Set(nil)
}

// UnsetName ensures that no value is present for Name, not even an explicit nil
func (o *BulkItemInput) UnsetName() {
	o.Name.Unset()
}

// GetBufferMeters returns the BufferMeters field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *BulkItemInput) GetBufferMeters() int32 {
	if o == nil || IsNil(o.BufferMeters.Get()) {
		var ret int32
		return ret
	}
	return *o.BufferMeters.Get()
}

// GetBufferMetersOk returns a tuple with the BufferMeters field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *BulkItemInput) GetBufferMetersOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.BufferMeters.Get(), o.BufferMeters.IsSet()
}

// HasBufferMeters returns a boolean if a field has been set.
func (o *BulkItemInput) HasBufferMeters() bool {
	if o != nil && o.BufferMeters.IsSet() {
		return true
	}

	return false
}

// SetBufferMeters gets a reference to the given NullableInt32 and assigns it to the BufferMeters field.
func (o *BulkItemInput) SetBufferMeters(v int32) {
	o.BufferMeters.Set(&v)
}
// SetBufferMetersNil sets the value for BufferMeters to be an explicit nil
func (o *BulkItemInput) SetBufferMetersNil() {
	o.BufferMeters.Set(nil)
}

// UnsetBufferMeters ensures that no value is present for BufferMeters, not even an explicit nil
func (o *BulkItemInput) UnsetBufferMeters() {
	o.BufferMeters.Unset()
}

// GetTags returns the Tags field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *BulkItemInput) GetTags() []string {
	if o == nil {
		var ret []string
		return ret
	}
	return o.Tags
}

// GetTagsOk returns a tuple with the Tags field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *BulkItemInput) GetTagsOk() ([]string, bool) {
	if o == nil || IsNil(o.Tags) {
		return nil, false
	}
	return o.Tags, true
}

// HasTags returns a boolean if a field has been set.
func (o *BulkItemInput) HasTags() bool {
	if o != nil && !IsNil(o.Tags) {
		return true
	}

	return false
}

// SetTags gets a reference to the given []string and assigns it to the Tags field.
func (o *BulkItemInput) SetTags(v []string) {
	o.Tags = v
}

func (o BulkItemInput) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BulkItemInput) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["address"] = o.Address
	if o.Name.IsSet() {
		toSerialize["name"] = o.Name.Get()
	}
	if o.BufferMeters.IsSet() {
		toSerialize["buffer_meters"] = o.BufferMeters.Get()
	}
	if o.Tags != nil {
		toSerialize["tags"] = o.Tags
	}
	return toSerialize, nil
}

func (o *BulkItemInput) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"address",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varBulkItemInput := _BulkItemInput{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varBulkItemInput)

	if err != nil {
		return err
	}

	*o = BulkItemInput(varBulkItemInput)

	return err
}

type NullableBulkItemInput struct {
	value *BulkItemInput
	isSet bool
}

func (v NullableBulkItemInput) Get() *BulkItemInput {
	return v.value
}

func (v *NullableBulkItemInput) Set(val *BulkItemInput) {
	v.value = val
	v.isSet = true
}

func (v NullableBulkItemInput) IsSet() bool {
	return v.isSet
}

func (v *NullableBulkItemInput) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBulkItemInput(val *BulkItemInput) *NullableBulkItemInput {
	return &NullableBulkItemInput{value: val, isSet: true}
}

func (v NullableBulkItemInput) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBulkItemInput) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


