/*
SpatialFlow API

Real-time geospatial automation platform API.  ## Authentication  **API Key:** Include `X-API-Key` header **JWT Token:** Include `Authorization: Bearer <token>` header  ## Rate Limits  - Authenticated: 1,000 requests per hour (per API key, JWT, or session) - Anonymous: 100 requests per hour  ## Webhook Verification  Outbound webhooks include HMAC-SHA256 signatures in `X-SF-Signature` header.  ## Support  - Documentation: https://docs.spatialflow.io - GitHub: https://github.com/spatialflow/spatialflow - Email: support@spatialflow.io     

API version: v1.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package generated

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the NotesUpdateIn type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &NotesUpdateIn{}

// NotesUpdateIn Request to update session notes.
type NotesUpdateIn struct {
	Notes string `json:"notes"`
}

type _NotesUpdateIn NotesUpdateIn

// NewNotesUpdateIn instantiates a new NotesUpdateIn object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewNotesUpdateIn(notes string) *NotesUpdateIn {
	this := NotesUpdateIn{}
	this.Notes = notes
	return &this
}

// NewNotesUpdateInWithDefaults instantiates a new NotesUpdateIn object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewNotesUpdateInWithDefaults() *NotesUpdateIn {
	this := NotesUpdateIn{}
	return &this
}

// GetNotes returns the Notes field value
func (o *NotesUpdateIn) GetNotes() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Notes
}

// GetNotesOk returns a tuple with the Notes field value
// and a boolean to check if the value has been set.
func (o *NotesUpdateIn) GetNotesOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Notes, true
}

// SetNotes sets field value
func (o *NotesUpdateIn) SetNotes(v string) {
	o.Notes = v
}

func (o NotesUpdateIn) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o NotesUpdateIn) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["notes"] = o.Notes
	return toSerialize, nil
}

func (o *NotesUpdateIn) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"notes",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varNotesUpdateIn := _NotesUpdateIn{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varNotesUpdateIn)

	if err != nil {
		return err
	}

	*o = NotesUpdateIn(varNotesUpdateIn)

	return err
}

type NullableNotesUpdateIn struct {
	value *NotesUpdateIn
	isSet bool
}

func (v NullableNotesUpdateIn) Get() *NotesUpdateIn {
	return v.value
}

func (v *NullableNotesUpdateIn) Set(val *NotesUpdateIn) {
	v.value = val
	v.isSet = true
}

func (v NullableNotesUpdateIn) IsSet() bool {
	return v.isSet
}

func (v *NullableNotesUpdateIn) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNotesUpdateIn(val *NotesUpdateIn) *NullableNotesUpdateIn {
	return &NullableNotesUpdateIn{value: val, isSet: true}
}

func (v NullableNotesUpdateIn) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNotesUpdateIn) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


