/*
SpatialFlow API

Real-time geospatial automation platform API.  ## Authentication  **API Key:** Include `X-API-Key` header **JWT Token:** Include `Authorization: Bearer <token>` header  ## Rate Limits  - Authenticated: 1,000 requests per hour (per API key, JWT, or session) - Anonymous: 100 requests per hour  ## Webhook Verification  Outbound webhooks include HMAC-SHA256 signatures in `X-SF-Signature` header.  ## Support  - Documentation: https://docs.spatialflow.io/ - Email: support@spatialflow.io     

API version: v1.36.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package generated

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the WebhookSecretResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &WebhookSecretResponse{}

// WebhookSecretResponse A webhook plus its signing secret.  Only create and rotate-secret return this; list, get and update never include the secret.
type WebhookSecretResponse struct {
	Id string `json:"id"`
	Name string `json:"name"`
	Description NullableString `json:"description"`
	Url string `json:"url"`
	Events []string `json:"events"`
	Headers map[string]string `json:"headers"`
	SensitiveHeadersConfigured []string `json:"sensitive_headers_configured,omitempty"`
	AuthType string `json:"auth_type"`
	Method string `json:"method"`
	ContentType string `json:"content_type"`
	CustomPayloadTemplate NullableString `json:"custom_payload_template"`
	IsActive bool `json:"is_active"`
	MaxRetries int32 `json:"max_retries"`
	TimeoutSeconds int32 `json:"timeout_seconds"`
	RateLimitPerMinute int32 `json:"rate_limit_per_minute"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
	LastTriggeredAt NullableTime `json:"last_triggered_at"`
	TotalDeliveries int32 `json:"total_deliveries"`
	SuccessfulDeliveries int32 `json:"successful_deliveries"`
	FailedDeliveries int32 `json:"failed_deliveries"`
	SuccessRate NullableFloat32 `json:"success_rate"`
	AttachedGeofenceCount *int32 `json:"attached_geofence_count,omitempty"`
	// HMAC-SHA256 key that signs every delivery's X-SF-Signature header. Shown only in this response; store it now, or rotate the secret to get a new one.
	Secret string `json:"secret"`
}

type _WebhookSecretResponse WebhookSecretResponse

// NewWebhookSecretResponse instantiates a new WebhookSecretResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWebhookSecretResponse(id string, name string, description NullableString, url string, events []string, headers map[string]string, authType string, method string, contentType string, customPayloadTemplate NullableString, isActive bool, maxRetries int32, timeoutSeconds int32, rateLimitPerMinute int32, createdAt time.Time, updatedAt time.Time, lastTriggeredAt NullableTime, totalDeliveries int32, successfulDeliveries int32, failedDeliveries int32, successRate NullableFloat32, secret string) *WebhookSecretResponse {
	this := WebhookSecretResponse{}
	this.Id = id
	this.Name = name
	this.Description = description
	this.Url = url
	this.Events = events
	this.Headers = headers
	this.AuthType = authType
	this.Method = method
	this.ContentType = contentType
	this.CustomPayloadTemplate = customPayloadTemplate
	this.IsActive = isActive
	this.MaxRetries = maxRetries
	this.TimeoutSeconds = timeoutSeconds
	this.RateLimitPerMinute = rateLimitPerMinute
	this.CreatedAt = createdAt
	this.UpdatedAt = updatedAt
	this.LastTriggeredAt = lastTriggeredAt
	this.TotalDeliveries = totalDeliveries
	this.SuccessfulDeliveries = successfulDeliveries
	this.FailedDeliveries = failedDeliveries
	this.SuccessRate = successRate
	var attachedGeofenceCount int32 = 0
	this.AttachedGeofenceCount = &attachedGeofenceCount
	this.Secret = secret
	return &this
}

// NewWebhookSecretResponseWithDefaults instantiates a new WebhookSecretResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWebhookSecretResponseWithDefaults() *WebhookSecretResponse {
	this := WebhookSecretResponse{}
	var attachedGeofenceCount int32 = 0
	this.AttachedGeofenceCount = &attachedGeofenceCount
	return &this
}

// GetId returns the Id field value
func (o *WebhookSecretResponse) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *WebhookSecretResponse) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *WebhookSecretResponse) SetId(v string) {
	o.Id = v
}

// GetName returns the Name field value
func (o *WebhookSecretResponse) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *WebhookSecretResponse) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *WebhookSecretResponse) SetName(v string) {
	o.Name = v
}

// GetDescription returns the Description field value
// If the value is explicit nil, the zero value for string will be returned
func (o *WebhookSecretResponse) GetDescription() string {
	if o == nil || o.Description.Get() == nil {
		var ret string
		return ret
	}

	return *o.Description.Get()
}

// GetDescriptionOk returns a tuple with the Description field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *WebhookSecretResponse) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Description.Get(), o.Description.IsSet()
}

// SetDescription sets field value
func (o *WebhookSecretResponse) SetDescription(v string) {
	o.Description.Set(&v)
}

// GetUrl returns the Url field value
func (o *WebhookSecretResponse) GetUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Url
}

// GetUrlOk returns a tuple with the Url field value
// and a boolean to check if the value has been set.
func (o *WebhookSecretResponse) GetUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Url, true
}

// SetUrl sets field value
func (o *WebhookSecretResponse) SetUrl(v string) {
	o.Url = v
}

// GetEvents returns the Events field value
func (o *WebhookSecretResponse) GetEvents() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.Events
}

// GetEventsOk returns a tuple with the Events field value
// and a boolean to check if the value has been set.
func (o *WebhookSecretResponse) GetEventsOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Events, true
}

// SetEvents sets field value
func (o *WebhookSecretResponse) SetEvents(v []string) {
	o.Events = v
}

// GetHeaders returns the Headers field value
func (o *WebhookSecretResponse) GetHeaders() map[string]string {
	if o == nil {
		var ret map[string]string
		return ret
	}

	return o.Headers
}

// GetHeadersOk returns a tuple with the Headers field value
// and a boolean to check if the value has been set.
func (o *WebhookSecretResponse) GetHeadersOk() (map[string]string, bool) {
	if o == nil {
		return map[string]string{}, false
	}
	return o.Headers, true
}

// SetHeaders sets field value
func (o *WebhookSecretResponse) SetHeaders(v map[string]string) {
	o.Headers = v
}

// GetSensitiveHeadersConfigured returns the SensitiveHeadersConfigured field value if set, zero value otherwise.
func (o *WebhookSecretResponse) GetSensitiveHeadersConfigured() []string {
	if o == nil || IsNil(o.SensitiveHeadersConfigured) {
		var ret []string
		return ret
	}
	return o.SensitiveHeadersConfigured
}

// GetSensitiveHeadersConfiguredOk returns a tuple with the SensitiveHeadersConfigured field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebhookSecretResponse) GetSensitiveHeadersConfiguredOk() ([]string, bool) {
	if o == nil || IsNil(o.SensitiveHeadersConfigured) {
		return nil, false
	}
	return o.SensitiveHeadersConfigured, true
}

// HasSensitiveHeadersConfigured returns a boolean if a field has been set.
func (o *WebhookSecretResponse) HasSensitiveHeadersConfigured() bool {
	if o != nil && !IsNil(o.SensitiveHeadersConfigured) {
		return true
	}

	return false
}

// SetSensitiveHeadersConfigured gets a reference to the given []string and assigns it to the SensitiveHeadersConfigured field.
func (o *WebhookSecretResponse) SetSensitiveHeadersConfigured(v []string) {
	o.SensitiveHeadersConfigured = v
}

// GetAuthType returns the AuthType field value
func (o *WebhookSecretResponse) GetAuthType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AuthType
}

// GetAuthTypeOk returns a tuple with the AuthType field value
// and a boolean to check if the value has been set.
func (o *WebhookSecretResponse) GetAuthTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AuthType, true
}

// SetAuthType sets field value
func (o *WebhookSecretResponse) SetAuthType(v string) {
	o.AuthType = v
}

// GetMethod returns the Method field value
func (o *WebhookSecretResponse) GetMethod() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Method
}

// GetMethodOk returns a tuple with the Method field value
// and a boolean to check if the value has been set.
func (o *WebhookSecretResponse) GetMethodOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Method, true
}

// SetMethod sets field value
func (o *WebhookSecretResponse) SetMethod(v string) {
	o.Method = v
}

// GetContentType returns the ContentType field value
func (o *WebhookSecretResponse) GetContentType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ContentType
}

// GetContentTypeOk returns a tuple with the ContentType field value
// and a boolean to check if the value has been set.
func (o *WebhookSecretResponse) GetContentTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ContentType, true
}

// SetContentType sets field value
func (o *WebhookSecretResponse) SetContentType(v string) {
	o.ContentType = v
}

// GetCustomPayloadTemplate returns the CustomPayloadTemplate field value
// If the value is explicit nil, the zero value for string will be returned
func (o *WebhookSecretResponse) GetCustomPayloadTemplate() string {
	if o == nil || o.CustomPayloadTemplate.Get() == nil {
		var ret string
		return ret
	}

	return *o.CustomPayloadTemplate.Get()
}

// GetCustomPayloadTemplateOk returns a tuple with the CustomPayloadTemplate field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *WebhookSecretResponse) GetCustomPayloadTemplateOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.CustomPayloadTemplate.Get(), o.CustomPayloadTemplate.IsSet()
}

// SetCustomPayloadTemplate sets field value
func (o *WebhookSecretResponse) SetCustomPayloadTemplate(v string) {
	o.CustomPayloadTemplate.Set(&v)
}

// GetIsActive returns the IsActive field value
func (o *WebhookSecretResponse) GetIsActive() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.IsActive
}

// GetIsActiveOk returns a tuple with the IsActive field value
// and a boolean to check if the value has been set.
func (o *WebhookSecretResponse) GetIsActiveOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IsActive, true
}

// SetIsActive sets field value
func (o *WebhookSecretResponse) SetIsActive(v bool) {
	o.IsActive = v
}

// GetMaxRetries returns the MaxRetries field value
func (o *WebhookSecretResponse) GetMaxRetries() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.MaxRetries
}

// GetMaxRetriesOk returns a tuple with the MaxRetries field value
// and a boolean to check if the value has been set.
func (o *WebhookSecretResponse) GetMaxRetriesOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MaxRetries, true
}

// SetMaxRetries sets field value
func (o *WebhookSecretResponse) SetMaxRetries(v int32) {
	o.MaxRetries = v
}

// GetTimeoutSeconds returns the TimeoutSeconds field value
func (o *WebhookSecretResponse) GetTimeoutSeconds() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.TimeoutSeconds
}

// GetTimeoutSecondsOk returns a tuple with the TimeoutSeconds field value
// and a boolean to check if the value has been set.
func (o *WebhookSecretResponse) GetTimeoutSecondsOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TimeoutSeconds, true
}

// SetTimeoutSeconds sets field value
func (o *WebhookSecretResponse) SetTimeoutSeconds(v int32) {
	o.TimeoutSeconds = v
}

// GetRateLimitPerMinute returns the RateLimitPerMinute field value
func (o *WebhookSecretResponse) GetRateLimitPerMinute() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.RateLimitPerMinute
}

// GetRateLimitPerMinuteOk returns a tuple with the RateLimitPerMinute field value
// and a boolean to check if the value has been set.
func (o *WebhookSecretResponse) GetRateLimitPerMinuteOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RateLimitPerMinute, true
}

// SetRateLimitPerMinute sets field value
func (o *WebhookSecretResponse) SetRateLimitPerMinute(v int32) {
	o.RateLimitPerMinute = v
}

// GetCreatedAt returns the CreatedAt field value
func (o *WebhookSecretResponse) GetCreatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *WebhookSecretResponse) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *WebhookSecretResponse) SetCreatedAt(v time.Time) {
	o.CreatedAt = v
}

// GetUpdatedAt returns the UpdatedAt field value
func (o *WebhookSecretResponse) GetUpdatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value
// and a boolean to check if the value has been set.
func (o *WebhookSecretResponse) GetUpdatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UpdatedAt, true
}

// SetUpdatedAt sets field value
func (o *WebhookSecretResponse) SetUpdatedAt(v time.Time) {
	o.UpdatedAt = v
}

// GetLastTriggeredAt returns the LastTriggeredAt field value
// If the value is explicit nil, the zero value for time.Time will be returned
func (o *WebhookSecretResponse) GetLastTriggeredAt() time.Time {
	if o == nil || o.LastTriggeredAt.Get() == nil {
		var ret time.Time
		return ret
	}

	return *o.LastTriggeredAt.Get()
}

// GetLastTriggeredAtOk returns a tuple with the LastTriggeredAt field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *WebhookSecretResponse) GetLastTriggeredAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.LastTriggeredAt.Get(), o.LastTriggeredAt.IsSet()
}

// SetLastTriggeredAt sets field value
func (o *WebhookSecretResponse) SetLastTriggeredAt(v time.Time) {
	o.LastTriggeredAt.Set(&v)
}

// GetTotalDeliveries returns the TotalDeliveries field value
func (o *WebhookSecretResponse) GetTotalDeliveries() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.TotalDeliveries
}

// GetTotalDeliveriesOk returns a tuple with the TotalDeliveries field value
// and a boolean to check if the value has been set.
func (o *WebhookSecretResponse) GetTotalDeliveriesOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TotalDeliveries, true
}

// SetTotalDeliveries sets field value
func (o *WebhookSecretResponse) SetTotalDeliveries(v int32) {
	o.TotalDeliveries = v
}

// GetSuccessfulDeliveries returns the SuccessfulDeliveries field value
func (o *WebhookSecretResponse) GetSuccessfulDeliveries() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.SuccessfulDeliveries
}

// GetSuccessfulDeliveriesOk returns a tuple with the SuccessfulDeliveries field value
// and a boolean to check if the value has been set.
func (o *WebhookSecretResponse) GetSuccessfulDeliveriesOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SuccessfulDeliveries, true
}

// SetSuccessfulDeliveries sets field value
func (o *WebhookSecretResponse) SetSuccessfulDeliveries(v int32) {
	o.SuccessfulDeliveries = v
}

// GetFailedDeliveries returns the FailedDeliveries field value
func (o *WebhookSecretResponse) GetFailedDeliveries() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.FailedDeliveries
}

// GetFailedDeliveriesOk returns a tuple with the FailedDeliveries field value
// and a boolean to check if the value has been set.
func (o *WebhookSecretResponse) GetFailedDeliveriesOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.FailedDeliveries, true
}

// SetFailedDeliveries sets field value
func (o *WebhookSecretResponse) SetFailedDeliveries(v int32) {
	o.FailedDeliveries = v
}

// GetSuccessRate returns the SuccessRate field value
// If the value is explicit nil, the zero value for float32 will be returned
func (o *WebhookSecretResponse) GetSuccessRate() float32 {
	if o == nil || o.SuccessRate.Get() == nil {
		var ret float32
		return ret
	}

	return *o.SuccessRate.Get()
}

// GetSuccessRateOk returns a tuple with the SuccessRate field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *WebhookSecretResponse) GetSuccessRateOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return o.SuccessRate.Get(), o.SuccessRate.IsSet()
}

// SetSuccessRate sets field value
func (o *WebhookSecretResponse) SetSuccessRate(v float32) {
	o.SuccessRate.Set(&v)
}

// GetAttachedGeofenceCount returns the AttachedGeofenceCount field value if set, zero value otherwise.
func (o *WebhookSecretResponse) GetAttachedGeofenceCount() int32 {
	if o == nil || IsNil(o.AttachedGeofenceCount) {
		var ret int32
		return ret
	}
	return *o.AttachedGeofenceCount
}

// GetAttachedGeofenceCountOk returns a tuple with the AttachedGeofenceCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebhookSecretResponse) GetAttachedGeofenceCountOk() (*int32, bool) {
	if o == nil || IsNil(o.AttachedGeofenceCount) {
		return nil, false
	}
	return o.AttachedGeofenceCount, true
}

// HasAttachedGeofenceCount returns a boolean if a field has been set.
func (o *WebhookSecretResponse) HasAttachedGeofenceCount() bool {
	if o != nil && !IsNil(o.AttachedGeofenceCount) {
		return true
	}

	return false
}

// SetAttachedGeofenceCount gets a reference to the given int32 and assigns it to the AttachedGeofenceCount field.
func (o *WebhookSecretResponse) SetAttachedGeofenceCount(v int32) {
	o.AttachedGeofenceCount = &v
}

// GetSecret returns the Secret field value
func (o *WebhookSecretResponse) GetSecret() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Secret
}

// GetSecretOk returns a tuple with the Secret field value
// and a boolean to check if the value has been set.
func (o *WebhookSecretResponse) GetSecretOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Secret, true
}

// SetSecret sets field value
func (o *WebhookSecretResponse) SetSecret(v string) {
	o.Secret = v
}

func (o WebhookSecretResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o WebhookSecretResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["name"] = o.Name
	toSerialize["description"] = o.Description.Get()
	toSerialize["url"] = o.Url
	toSerialize["events"] = o.Events
	toSerialize["headers"] = o.Headers
	if !IsNil(o.SensitiveHeadersConfigured) {
		toSerialize["sensitive_headers_configured"] = o.SensitiveHeadersConfigured
	}
	toSerialize["auth_type"] = o.AuthType
	toSerialize["method"] = o.Method
	toSerialize["content_type"] = o.ContentType
	toSerialize["custom_payload_template"] = o.CustomPayloadTemplate.Get()
	toSerialize["is_active"] = o.IsActive
	toSerialize["max_retries"] = o.MaxRetries
	toSerialize["timeout_seconds"] = o.TimeoutSeconds
	toSerialize["rate_limit_per_minute"] = o.RateLimitPerMinute
	toSerialize["created_at"] = o.CreatedAt
	toSerialize["updated_at"] = o.UpdatedAt
	toSerialize["last_triggered_at"] = o.LastTriggeredAt.Get()
	toSerialize["total_deliveries"] = o.TotalDeliveries
	toSerialize["successful_deliveries"] = o.SuccessfulDeliveries
	toSerialize["failed_deliveries"] = o.FailedDeliveries
	toSerialize["success_rate"] = o.SuccessRate.Get()
	if !IsNil(o.AttachedGeofenceCount) {
		toSerialize["attached_geofence_count"] = o.AttachedGeofenceCount
	}
	toSerialize["secret"] = o.Secret
	return toSerialize, nil
}

func (o *WebhookSecretResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"name",
		"description",
		"url",
		"events",
		"headers",
		"auth_type",
		"method",
		"content_type",
		"custom_payload_template",
		"is_active",
		"max_retries",
		"timeout_seconds",
		"rate_limit_per_minute",
		"created_at",
		"updated_at",
		"last_triggered_at",
		"total_deliveries",
		"successful_deliveries",
		"failed_deliveries",
		"success_rate",
		"secret",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varWebhookSecretResponse := _WebhookSecretResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varWebhookSecretResponse)

	if err != nil {
		return err
	}

	*o = WebhookSecretResponse(varWebhookSecretResponse)

	return err
}

type NullableWebhookSecretResponse struct {
	value *WebhookSecretResponse
	isSet bool
}

func (v NullableWebhookSecretResponse) Get() *WebhookSecretResponse {
	return v.value
}

func (v *NullableWebhookSecretResponse) Set(val *WebhookSecretResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableWebhookSecretResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableWebhookSecretResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWebhookSecretResponse(val *WebhookSecretResponse) *NullableWebhookSecretResponse {
	return &NullableWebhookSecretResponse{value: val, isSet: true}
}

func (v NullableWebhookSecretResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWebhookSecretResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


