/*
SpatialFlow API

Real-time geospatial automation platform API.  ## Authentication  **API Key:** Include `X-API-Key` header **JWT Token:** Include `Authorization: Bearer <token>` header  ## Rate Limits  - Authenticated: 1,000 requests per hour (per API key, JWT, or session) - Anonymous: 100 requests per hour  ## Webhook Verification  Outbound webhooks include HMAC-SHA256 signatures in `X-SF-Signature` header.  ## Support  - Documentation: https://docs.spatialflow.io - GitHub: https://github.com/spatialflow/spatialflow - Email: support@spatialflow.io     

API version: v1.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package generated

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the BulkInviteRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BulkInviteRequest{}

// BulkInviteRequest Request to bulk invite users.
type BulkInviteRequest struct {
	Invites []BulkInviteItem `json:"invites"`
}

type _BulkInviteRequest BulkInviteRequest

// NewBulkInviteRequest instantiates a new BulkInviteRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBulkInviteRequest(invites []BulkInviteItem) *BulkInviteRequest {
	this := BulkInviteRequest{}
	this.Invites = invites
	return &this
}

// NewBulkInviteRequestWithDefaults instantiates a new BulkInviteRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBulkInviteRequestWithDefaults() *BulkInviteRequest {
	this := BulkInviteRequest{}
	return &this
}

// GetInvites returns the Invites field value
func (o *BulkInviteRequest) GetInvites() []BulkInviteItem {
	if o == nil {
		var ret []BulkInviteItem
		return ret
	}

	return o.Invites
}

// GetInvitesOk returns a tuple with the Invites field value
// and a boolean to check if the value has been set.
func (o *BulkInviteRequest) GetInvitesOk() ([]BulkInviteItem, bool) {
	if o == nil {
		return nil, false
	}
	return o.Invites, true
}

// SetInvites sets field value
func (o *BulkInviteRequest) SetInvites(v []BulkInviteItem) {
	o.Invites = v
}

func (o BulkInviteRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BulkInviteRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["invites"] = o.Invites
	return toSerialize, nil
}

func (o *BulkInviteRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"invites",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varBulkInviteRequest := _BulkInviteRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varBulkInviteRequest)

	if err != nil {
		return err
	}

	*o = BulkInviteRequest(varBulkInviteRequest)

	return err
}

type NullableBulkInviteRequest struct {
	value *BulkInviteRequest
	isSet bool
}

func (v NullableBulkInviteRequest) Get() *BulkInviteRequest {
	return v.value
}

func (v *NullableBulkInviteRequest) Set(val *BulkInviteRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableBulkInviteRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableBulkInviteRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBulkInviteRequest(val *BulkInviteRequest) *NullableBulkInviteRequest {
	return &NullableBulkInviteRequest{value: val, isSet: true}
}

func (v NullableBulkInviteRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBulkInviteRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


