/*
SpatialFlow API

Real-time geospatial automation platform API.  ## Authentication  **API Key:** Include `X-API-Key` header **JWT Token:** Include `Authorization: Bearer <token>` header  ## Rate Limits  - Authenticated: 1,000 requests per hour (per API key, JWT, or session) - Anonymous: 100 requests per hour  ## Webhook Verification  Outbound webhooks include HMAC-SHA256 signatures in `X-SF-Signature` header.  ## Support  - Documentation: https://docs.spatialflow.io/ - Email: support@spatialflow.io     

API version: v1.36.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package generated

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the CaptureActivityOut type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CaptureActivityOut{}

// CaptureActivityOut Photos or a note the device's worker added to one session.
type CaptureActivityOut struct {
	Kind string `json:"kind"`
	DeviceUuid string `json:"device_uuid"`
	DeviceName string `json:"device_name"`
	WorkerName string `json:"worker_name"`
	SessionId string `json:"session_id"`
	Count int32 `json:"count"`
	// Latest upload or note time in the group.
	At time.Time `json:"at"`
}

type _CaptureActivityOut CaptureActivityOut

// NewCaptureActivityOut instantiates a new CaptureActivityOut object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCaptureActivityOut(kind string, deviceUuid string, deviceName string, workerName string, sessionId string, count int32, at time.Time) *CaptureActivityOut {
	this := CaptureActivityOut{}
	this.Kind = kind
	this.DeviceUuid = deviceUuid
	this.DeviceName = deviceName
	this.WorkerName = workerName
	this.SessionId = sessionId
	this.Count = count
	this.At = at
	return &this
}

// NewCaptureActivityOutWithDefaults instantiates a new CaptureActivityOut object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCaptureActivityOutWithDefaults() *CaptureActivityOut {
	this := CaptureActivityOut{}
	return &this
}

// GetKind returns the Kind field value
func (o *CaptureActivityOut) GetKind() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Kind
}

// GetKindOk returns a tuple with the Kind field value
// and a boolean to check if the value has been set.
func (o *CaptureActivityOut) GetKindOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Kind, true
}

// SetKind sets field value
func (o *CaptureActivityOut) SetKind(v string) {
	o.Kind = v
}

// GetDeviceUuid returns the DeviceUuid field value
func (o *CaptureActivityOut) GetDeviceUuid() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DeviceUuid
}

// GetDeviceUuidOk returns a tuple with the DeviceUuid field value
// and a boolean to check if the value has been set.
func (o *CaptureActivityOut) GetDeviceUuidOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DeviceUuid, true
}

// SetDeviceUuid sets field value
func (o *CaptureActivityOut) SetDeviceUuid(v string) {
	o.DeviceUuid = v
}

// GetDeviceName returns the DeviceName field value
func (o *CaptureActivityOut) GetDeviceName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DeviceName
}

// GetDeviceNameOk returns a tuple with the DeviceName field value
// and a boolean to check if the value has been set.
func (o *CaptureActivityOut) GetDeviceNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DeviceName, true
}

// SetDeviceName sets field value
func (o *CaptureActivityOut) SetDeviceName(v string) {
	o.DeviceName = v
}

// GetWorkerName returns the WorkerName field value
func (o *CaptureActivityOut) GetWorkerName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.WorkerName
}

// GetWorkerNameOk returns a tuple with the WorkerName field value
// and a boolean to check if the value has been set.
func (o *CaptureActivityOut) GetWorkerNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.WorkerName, true
}

// SetWorkerName sets field value
func (o *CaptureActivityOut) SetWorkerName(v string) {
	o.WorkerName = v
}

// GetSessionId returns the SessionId field value
func (o *CaptureActivityOut) GetSessionId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SessionId
}

// GetSessionIdOk returns a tuple with the SessionId field value
// and a boolean to check if the value has been set.
func (o *CaptureActivityOut) GetSessionIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SessionId, true
}

// SetSessionId sets field value
func (o *CaptureActivityOut) SetSessionId(v string) {
	o.SessionId = v
}

// GetCount returns the Count field value
func (o *CaptureActivityOut) GetCount() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Count
}

// GetCountOk returns a tuple with the Count field value
// and a boolean to check if the value has been set.
func (o *CaptureActivityOut) GetCountOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Count, true
}

// SetCount sets field value
func (o *CaptureActivityOut) SetCount(v int32) {
	o.Count = v
}

// GetAt returns the At field value
func (o *CaptureActivityOut) GetAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.At
}

// GetAtOk returns a tuple with the At field value
// and a boolean to check if the value has been set.
func (o *CaptureActivityOut) GetAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.At, true
}

// SetAt sets field value
func (o *CaptureActivityOut) SetAt(v time.Time) {
	o.At = v
}

func (o CaptureActivityOut) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CaptureActivityOut) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["kind"] = o.Kind
	toSerialize["device_uuid"] = o.DeviceUuid
	toSerialize["device_name"] = o.DeviceName
	toSerialize["worker_name"] = o.WorkerName
	toSerialize["session_id"] = o.SessionId
	toSerialize["count"] = o.Count
	toSerialize["at"] = o.At
	return toSerialize, nil
}

func (o *CaptureActivityOut) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"kind",
		"device_uuid",
		"device_name",
		"worker_name",
		"session_id",
		"count",
		"at",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCaptureActivityOut := _CaptureActivityOut{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCaptureActivityOut)

	if err != nil {
		return err
	}

	*o = CaptureActivityOut(varCaptureActivityOut)

	return err
}

type NullableCaptureActivityOut struct {
	value *CaptureActivityOut
	isSet bool
}

func (v NullableCaptureActivityOut) Get() *CaptureActivityOut {
	return v.value
}

func (v *NullableCaptureActivityOut) Set(val *CaptureActivityOut) {
	v.value = val
	v.isSet = true
}

func (v NullableCaptureActivityOut) IsSet() bool {
	return v.isSet
}

func (v *NullableCaptureActivityOut) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCaptureActivityOut(val *CaptureActivityOut) *NullableCaptureActivityOut {
	return &NullableCaptureActivityOut{value: val, isSet: true}
}

func (v NullableCaptureActivityOut) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCaptureActivityOut) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


