/*
SpatialFlow API

Real-time geospatial automation platform API.  ## Authentication  **API Key:** Include `X-API-Key` header **JWT Token:** Include `Authorization: Bearer <token>` header  ## Rate Limits  - Authenticated: 1,000 requests per hour (per API key, JWT, or session) - Anonymous: 100 requests per hour  ## Webhook Verification  Outbound webhooks include HMAC-SHA256 signatures in `X-SF-Signature` header.  ## Support  - Documentation: https://docs.spatialflow.io - GitHub: https://github.com/spatialflow/spatialflow - Email: support@spatialflow.io     

API version: v1.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package generated

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the PlanLimits type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PlanLimits{}

// PlanLimits Usage limits for a subscription plan.
type PlanLimits struct {
	// Monthly API call limit (-1 for unlimited)
	ApiCalls int32 `json:"api_calls"`
	// Maximum number of geofences (-1 for unlimited)
	Geofences int32 `json:"geofences"`
	// Monthly webhook delivery limit (-1 for unlimited)
	WebhooksDelivered int32 `json:"webhooks_delivered"`
	// Monthly test point limit (-1 for unlimited)
	TestPoints int32 `json:"test_points"`
	// Hourly rate limit
	RateLimitPerHour int32 `json:"rate_limit_per_hour"`
	// Log retention in days (-1 for unlimited)
	LogRetentionDays *int32 `json:"log_retention_days,omitempty"`
	// Location data retention in days
	LocationRetentionDays *int32 `json:"location_retention_days,omitempty"`
}

type _PlanLimits PlanLimits

// NewPlanLimits instantiates a new PlanLimits object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPlanLimits(apiCalls int32, geofences int32, webhooksDelivered int32, testPoints int32, rateLimitPerHour int32) *PlanLimits {
	this := PlanLimits{}
	this.ApiCalls = apiCalls
	this.Geofences = geofences
	this.WebhooksDelivered = webhooksDelivered
	this.TestPoints = testPoints
	this.RateLimitPerHour = rateLimitPerHour
	var logRetentionDays int32 = 7
	this.LogRetentionDays = &logRetentionDays
	var locationRetentionDays int32 = 90
	this.LocationRetentionDays = &locationRetentionDays
	return &this
}

// NewPlanLimitsWithDefaults instantiates a new PlanLimits object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPlanLimitsWithDefaults() *PlanLimits {
	this := PlanLimits{}
	var logRetentionDays int32 = 7
	this.LogRetentionDays = &logRetentionDays
	var locationRetentionDays int32 = 90
	this.LocationRetentionDays = &locationRetentionDays
	return &this
}

// GetApiCalls returns the ApiCalls field value
func (o *PlanLimits) GetApiCalls() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.ApiCalls
}

// GetApiCallsOk returns a tuple with the ApiCalls field value
// and a boolean to check if the value has been set.
func (o *PlanLimits) GetApiCallsOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ApiCalls, true
}

// SetApiCalls sets field value
func (o *PlanLimits) SetApiCalls(v int32) {
	o.ApiCalls = v
}

// GetGeofences returns the Geofences field value
func (o *PlanLimits) GetGeofences() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Geofences
}

// GetGeofencesOk returns a tuple with the Geofences field value
// and a boolean to check if the value has been set.
func (o *PlanLimits) GetGeofencesOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Geofences, true
}

// SetGeofences sets field value
func (o *PlanLimits) SetGeofences(v int32) {
	o.Geofences = v
}

// GetWebhooksDelivered returns the WebhooksDelivered field value
func (o *PlanLimits) GetWebhooksDelivered() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.WebhooksDelivered
}

// GetWebhooksDeliveredOk returns a tuple with the WebhooksDelivered field value
// and a boolean to check if the value has been set.
func (o *PlanLimits) GetWebhooksDeliveredOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.WebhooksDelivered, true
}

// SetWebhooksDelivered sets field value
func (o *PlanLimits) SetWebhooksDelivered(v int32) {
	o.WebhooksDelivered = v
}

// GetTestPoints returns the TestPoints field value
func (o *PlanLimits) GetTestPoints() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.TestPoints
}

// GetTestPointsOk returns a tuple with the TestPoints field value
// and a boolean to check if the value has been set.
func (o *PlanLimits) GetTestPointsOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TestPoints, true
}

// SetTestPoints sets field value
func (o *PlanLimits) SetTestPoints(v int32) {
	o.TestPoints = v
}

// GetRateLimitPerHour returns the RateLimitPerHour field value
func (o *PlanLimits) GetRateLimitPerHour() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.RateLimitPerHour
}

// GetRateLimitPerHourOk returns a tuple with the RateLimitPerHour field value
// and a boolean to check if the value has been set.
func (o *PlanLimits) GetRateLimitPerHourOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RateLimitPerHour, true
}

// SetRateLimitPerHour sets field value
func (o *PlanLimits) SetRateLimitPerHour(v int32) {
	o.RateLimitPerHour = v
}

// GetLogRetentionDays returns the LogRetentionDays field value if set, zero value otherwise.
func (o *PlanLimits) GetLogRetentionDays() int32 {
	if o == nil || IsNil(o.LogRetentionDays) {
		var ret int32
		return ret
	}
	return *o.LogRetentionDays
}

// GetLogRetentionDaysOk returns a tuple with the LogRetentionDays field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PlanLimits) GetLogRetentionDaysOk() (*int32, bool) {
	if o == nil || IsNil(o.LogRetentionDays) {
		return nil, false
	}
	return o.LogRetentionDays, true
}

// HasLogRetentionDays returns a boolean if a field has been set.
func (o *PlanLimits) HasLogRetentionDays() bool {
	if o != nil && !IsNil(o.LogRetentionDays) {
		return true
	}

	return false
}

// SetLogRetentionDays gets a reference to the given int32 and assigns it to the LogRetentionDays field.
func (o *PlanLimits) SetLogRetentionDays(v int32) {
	o.LogRetentionDays = &v
}

// GetLocationRetentionDays returns the LocationRetentionDays field value if set, zero value otherwise.
func (o *PlanLimits) GetLocationRetentionDays() int32 {
	if o == nil || IsNil(o.LocationRetentionDays) {
		var ret int32
		return ret
	}
	return *o.LocationRetentionDays
}

// GetLocationRetentionDaysOk returns a tuple with the LocationRetentionDays field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PlanLimits) GetLocationRetentionDaysOk() (*int32, bool) {
	if o == nil || IsNil(o.LocationRetentionDays) {
		return nil, false
	}
	return o.LocationRetentionDays, true
}

// HasLocationRetentionDays returns a boolean if a field has been set.
func (o *PlanLimits) HasLocationRetentionDays() bool {
	if o != nil && !IsNil(o.LocationRetentionDays) {
		return true
	}

	return false
}

// SetLocationRetentionDays gets a reference to the given int32 and assigns it to the LocationRetentionDays field.
func (o *PlanLimits) SetLocationRetentionDays(v int32) {
	o.LocationRetentionDays = &v
}

func (o PlanLimits) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PlanLimits) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["api_calls"] = o.ApiCalls
	toSerialize["geofences"] = o.Geofences
	toSerialize["webhooks_delivered"] = o.WebhooksDelivered
	toSerialize["test_points"] = o.TestPoints
	toSerialize["rate_limit_per_hour"] = o.RateLimitPerHour
	if !IsNil(o.LogRetentionDays) {
		toSerialize["log_retention_days"] = o.LogRetentionDays
	}
	if !IsNil(o.LocationRetentionDays) {
		toSerialize["location_retention_days"] = o.LocationRetentionDays
	}
	return toSerialize, nil
}

func (o *PlanLimits) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"api_calls",
		"geofences",
		"webhooks_delivered",
		"test_points",
		"rate_limit_per_hour",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPlanLimits := _PlanLimits{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varPlanLimits)

	if err != nil {
		return err
	}

	*o = PlanLimits(varPlanLimits)

	return err
}

type NullablePlanLimits struct {
	value *PlanLimits
	isSet bool
}

func (v NullablePlanLimits) Get() *PlanLimits {
	return v.value
}

func (v *NullablePlanLimits) Set(val *PlanLimits) {
	v.value = val
	v.isSet = true
}

func (v NullablePlanLimits) IsSet() bool {
	return v.isSet
}

func (v *NullablePlanLimits) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePlanLimits(val *PlanLimits) *NullablePlanLimits {
	return &NullablePlanLimits{value: val, isSet: true}
}

func (v NullablePlanLimits) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePlanLimits) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


