/*
SpatialFlow API

Real-time geospatial automation platform API.  ## Authentication  **API Key:** Include `X-API-Key` header **JWT Token:** Include `Authorization: Bearer <token>` header  ## Rate Limits  - Authenticated: 1,000 requests per hour (per API key, JWT, or session) - Anonymous: 100 requests per hour  ## Webhook Verification  Outbound webhooks include HMAC-SHA256 signatures in `X-SF-Signature` header.  ## Support  - Documentation: https://docs.spatialflow.io - GitHub: https://github.com/spatialflow/spatialflow - Email: support@spatialflow.io     

API version: v1.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package generated

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the PolicyOut type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PolicyOut{}

// PolicyOut struct for PolicyOut
type PolicyOut struct {
	Id string `json:"id"`
	Name string `json:"name"`
	Description string `json:"description"`
	IsEnabled bool `json:"is_enabled"`
	GeofenceId string `json:"geofence_id"`
	GeofenceName string `json:"geofence_name"`
	TimeWindow map[string]interface{} `json:"time_window,omitempty"`
	DeviceFilter map[string]interface{} `json:"device_filter,omitempty"`
	RoleFilter []string `json:"role_filter,omitempty"`
	TemplateId *string `json:"template_id,omitempty"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type _PolicyOut PolicyOut

// NewPolicyOut instantiates a new PolicyOut object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPolicyOut(id string, name string, description string, isEnabled bool, geofenceId string, geofenceName string, createdAt time.Time, updatedAt time.Time) *PolicyOut {
	this := PolicyOut{}
	this.Id = id
	this.Name = name
	this.Description = description
	this.IsEnabled = isEnabled
	this.GeofenceId = geofenceId
	this.GeofenceName = geofenceName
	var templateId string = ""
	this.TemplateId = &templateId
	this.CreatedAt = createdAt
	this.UpdatedAt = updatedAt
	return &this
}

// NewPolicyOutWithDefaults instantiates a new PolicyOut object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPolicyOutWithDefaults() *PolicyOut {
	this := PolicyOut{}
	var templateId string = ""
	this.TemplateId = &templateId
	return &this
}

// GetId returns the Id field value
func (o *PolicyOut) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *PolicyOut) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *PolicyOut) SetId(v string) {
	o.Id = v
}

// GetName returns the Name field value
func (o *PolicyOut) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *PolicyOut) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *PolicyOut) SetName(v string) {
	o.Name = v
}

// GetDescription returns the Description field value
func (o *PolicyOut) GetDescription() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Description
}

// GetDescriptionOk returns a tuple with the Description field value
// and a boolean to check if the value has been set.
func (o *PolicyOut) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Description, true
}

// SetDescription sets field value
func (o *PolicyOut) SetDescription(v string) {
	o.Description = v
}

// GetIsEnabled returns the IsEnabled field value
func (o *PolicyOut) GetIsEnabled() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.IsEnabled
}

// GetIsEnabledOk returns a tuple with the IsEnabled field value
// and a boolean to check if the value has been set.
func (o *PolicyOut) GetIsEnabledOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IsEnabled, true
}

// SetIsEnabled sets field value
func (o *PolicyOut) SetIsEnabled(v bool) {
	o.IsEnabled = v
}

// GetGeofenceId returns the GeofenceId field value
func (o *PolicyOut) GetGeofenceId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.GeofenceId
}

// GetGeofenceIdOk returns a tuple with the GeofenceId field value
// and a boolean to check if the value has been set.
func (o *PolicyOut) GetGeofenceIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.GeofenceId, true
}

// SetGeofenceId sets field value
func (o *PolicyOut) SetGeofenceId(v string) {
	o.GeofenceId = v
}

// GetGeofenceName returns the GeofenceName field value
func (o *PolicyOut) GetGeofenceName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.GeofenceName
}

// GetGeofenceNameOk returns a tuple with the GeofenceName field value
// and a boolean to check if the value has been set.
func (o *PolicyOut) GetGeofenceNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.GeofenceName, true
}

// SetGeofenceName sets field value
func (o *PolicyOut) SetGeofenceName(v string) {
	o.GeofenceName = v
}

// GetTimeWindow returns the TimeWindow field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PolicyOut) GetTimeWindow() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}
	return o.TimeWindow
}

// GetTimeWindowOk returns a tuple with the TimeWindow field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PolicyOut) GetTimeWindowOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.TimeWindow) {
		return map[string]interface{}{}, false
	}
	return o.TimeWindow, true
}

// HasTimeWindow returns a boolean if a field has been set.
func (o *PolicyOut) HasTimeWindow() bool {
	if o != nil && !IsNil(o.TimeWindow) {
		return true
	}

	return false
}

// SetTimeWindow gets a reference to the given map[string]interface{} and assigns it to the TimeWindow field.
func (o *PolicyOut) SetTimeWindow(v map[string]interface{}) {
	o.TimeWindow = v
}

// GetDeviceFilter returns the DeviceFilter field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PolicyOut) GetDeviceFilter() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}
	return o.DeviceFilter
}

// GetDeviceFilterOk returns a tuple with the DeviceFilter field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PolicyOut) GetDeviceFilterOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.DeviceFilter) {
		return map[string]interface{}{}, false
	}
	return o.DeviceFilter, true
}

// HasDeviceFilter returns a boolean if a field has been set.
func (o *PolicyOut) HasDeviceFilter() bool {
	if o != nil && !IsNil(o.DeviceFilter) {
		return true
	}

	return false
}

// SetDeviceFilter gets a reference to the given map[string]interface{} and assigns it to the DeviceFilter field.
func (o *PolicyOut) SetDeviceFilter(v map[string]interface{}) {
	o.DeviceFilter = v
}

// GetRoleFilter returns the RoleFilter field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PolicyOut) GetRoleFilter() []string {
	if o == nil {
		var ret []string
		return ret
	}
	return o.RoleFilter
}

// GetRoleFilterOk returns a tuple with the RoleFilter field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PolicyOut) GetRoleFilterOk() ([]string, bool) {
	if o == nil || IsNil(o.RoleFilter) {
		return nil, false
	}
	return o.RoleFilter, true
}

// HasRoleFilter returns a boolean if a field has been set.
func (o *PolicyOut) HasRoleFilter() bool {
	if o != nil && !IsNil(o.RoleFilter) {
		return true
	}

	return false
}

// SetRoleFilter gets a reference to the given []string and assigns it to the RoleFilter field.
func (o *PolicyOut) SetRoleFilter(v []string) {
	o.RoleFilter = v
}

// GetTemplateId returns the TemplateId field value if set, zero value otherwise.
func (o *PolicyOut) GetTemplateId() string {
	if o == nil || IsNil(o.TemplateId) {
		var ret string
		return ret
	}
	return *o.TemplateId
}

// GetTemplateIdOk returns a tuple with the TemplateId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PolicyOut) GetTemplateIdOk() (*string, bool) {
	if o == nil || IsNil(o.TemplateId) {
		return nil, false
	}
	return o.TemplateId, true
}

// HasTemplateId returns a boolean if a field has been set.
func (o *PolicyOut) HasTemplateId() bool {
	if o != nil && !IsNil(o.TemplateId) {
		return true
	}

	return false
}

// SetTemplateId gets a reference to the given string and assigns it to the TemplateId field.
func (o *PolicyOut) SetTemplateId(v string) {
	o.TemplateId = &v
}

// GetCreatedAt returns the CreatedAt field value
func (o *PolicyOut) GetCreatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *PolicyOut) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *PolicyOut) SetCreatedAt(v time.Time) {
	o.CreatedAt = v
}

// GetUpdatedAt returns the UpdatedAt field value
func (o *PolicyOut) GetUpdatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value
// and a boolean to check if the value has been set.
func (o *PolicyOut) GetUpdatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UpdatedAt, true
}

// SetUpdatedAt sets field value
func (o *PolicyOut) SetUpdatedAt(v time.Time) {
	o.UpdatedAt = v
}

func (o PolicyOut) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PolicyOut) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["name"] = o.Name
	toSerialize["description"] = o.Description
	toSerialize["is_enabled"] = o.IsEnabled
	toSerialize["geofence_id"] = o.GeofenceId
	toSerialize["geofence_name"] = o.GeofenceName
	if o.TimeWindow != nil {
		toSerialize["time_window"] = o.TimeWindow
	}
	if o.DeviceFilter != nil {
		toSerialize["device_filter"] = o.DeviceFilter
	}
	if o.RoleFilter != nil {
		toSerialize["role_filter"] = o.RoleFilter
	}
	if !IsNil(o.TemplateId) {
		toSerialize["template_id"] = o.TemplateId
	}
	toSerialize["created_at"] = o.CreatedAt
	toSerialize["updated_at"] = o.UpdatedAt
	return toSerialize, nil
}

func (o *PolicyOut) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"name",
		"description",
		"is_enabled",
		"geofence_id",
		"geofence_name",
		"created_at",
		"updated_at",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPolicyOut := _PolicyOut{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varPolicyOut)

	if err != nil {
		return err
	}

	*o = PolicyOut(varPolicyOut)

	return err
}

type NullablePolicyOut struct {
	value *PolicyOut
	isSet bool
}

func (v NullablePolicyOut) Get() *PolicyOut {
	return v.value
}

func (v *NullablePolicyOut) Set(val *PolicyOut) {
	v.value = val
	v.isSet = true
}

func (v NullablePolicyOut) IsSet() bool {
	return v.isSet
}

func (v *NullablePolicyOut) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePolicyOut(val *PolicyOut) *NullablePolicyOut {
	return &NullablePolicyOut{value: val, isSet: true}
}

func (v NullablePolicyOut) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePolicyOut) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


