/*
SpatialFlow API

Real-time geospatial automation platform API.  ## Authentication  **API Key:** Include `X-API-Key` header **JWT Token:** Include `Authorization: Bearer <token>` header  ## Rate Limits  - Authenticated: 1,000 requests per hour (per API key, JWT, or session) - Anonymous: 100 requests per hour  ## Webhook Verification  Outbound webhooks include HMAC-SHA256 signatures in `X-SF-Signature` header.  ## Support  - Documentation: https://docs.spatialflow.io - GitHub: https://github.com/spatialflow/spatialflow - Email: support@spatialflow.io     

API version: v1.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package generated

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the GPXPlaybackOut type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GPXPlaybackOut{}

// GPXPlaybackOut struct for GPXPlaybackOut
type GPXPlaybackOut struct {
	Id string `json:"id"`
	RouteId string `json:"route_id"`
	RouteName string `json:"route_name"`
	DeviceId string `json:"device_id"`
	Status string `json:"status"`
	SpeedMultiplier float32 `json:"speed_multiplier"`
	LoopEnabled bool `json:"loop_enabled"`
	CurrentPointIndex int32 `json:"current_point_index"`
	ProgressPercent float32 `json:"progress_percent"`
	EventsTriggered int32 `json:"events_triggered"`
	StartedAt NullableString `json:"started_at"`
	PausedAt NullableString `json:"paused_at"`
	CompletedAt NullableString `json:"completed_at"`
	ErrorMessage string `json:"error_message"`
}

type _GPXPlaybackOut GPXPlaybackOut

// NewGPXPlaybackOut instantiates a new GPXPlaybackOut object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGPXPlaybackOut(id string, routeId string, routeName string, deviceId string, status string, speedMultiplier float32, loopEnabled bool, currentPointIndex int32, progressPercent float32, eventsTriggered int32, startedAt NullableString, pausedAt NullableString, completedAt NullableString, errorMessage string) *GPXPlaybackOut {
	this := GPXPlaybackOut{}
	this.Id = id
	this.RouteId = routeId
	this.RouteName = routeName
	this.DeviceId = deviceId
	this.Status = status
	this.SpeedMultiplier = speedMultiplier
	this.LoopEnabled = loopEnabled
	this.CurrentPointIndex = currentPointIndex
	this.ProgressPercent = progressPercent
	this.EventsTriggered = eventsTriggered
	this.StartedAt = startedAt
	this.PausedAt = pausedAt
	this.CompletedAt = completedAt
	this.ErrorMessage = errorMessage
	return &this
}

// NewGPXPlaybackOutWithDefaults instantiates a new GPXPlaybackOut object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGPXPlaybackOutWithDefaults() *GPXPlaybackOut {
	this := GPXPlaybackOut{}
	return &this
}

// GetId returns the Id field value
func (o *GPXPlaybackOut) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *GPXPlaybackOut) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *GPXPlaybackOut) SetId(v string) {
	o.Id = v
}

// GetRouteId returns the RouteId field value
func (o *GPXPlaybackOut) GetRouteId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.RouteId
}

// GetRouteIdOk returns a tuple with the RouteId field value
// and a boolean to check if the value has been set.
func (o *GPXPlaybackOut) GetRouteIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RouteId, true
}

// SetRouteId sets field value
func (o *GPXPlaybackOut) SetRouteId(v string) {
	o.RouteId = v
}

// GetRouteName returns the RouteName field value
func (o *GPXPlaybackOut) GetRouteName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.RouteName
}

// GetRouteNameOk returns a tuple with the RouteName field value
// and a boolean to check if the value has been set.
func (o *GPXPlaybackOut) GetRouteNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RouteName, true
}

// SetRouteName sets field value
func (o *GPXPlaybackOut) SetRouteName(v string) {
	o.RouteName = v
}

// GetDeviceId returns the DeviceId field value
func (o *GPXPlaybackOut) GetDeviceId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DeviceId
}

// GetDeviceIdOk returns a tuple with the DeviceId field value
// and a boolean to check if the value has been set.
func (o *GPXPlaybackOut) GetDeviceIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DeviceId, true
}

// SetDeviceId sets field value
func (o *GPXPlaybackOut) SetDeviceId(v string) {
	o.DeviceId = v
}

// GetStatus returns the Status field value
func (o *GPXPlaybackOut) GetStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *GPXPlaybackOut) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *GPXPlaybackOut) SetStatus(v string) {
	o.Status = v
}

// GetSpeedMultiplier returns the SpeedMultiplier field value
func (o *GPXPlaybackOut) GetSpeedMultiplier() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.SpeedMultiplier
}

// GetSpeedMultiplierOk returns a tuple with the SpeedMultiplier field value
// and a boolean to check if the value has been set.
func (o *GPXPlaybackOut) GetSpeedMultiplierOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SpeedMultiplier, true
}

// SetSpeedMultiplier sets field value
func (o *GPXPlaybackOut) SetSpeedMultiplier(v float32) {
	o.SpeedMultiplier = v
}

// GetLoopEnabled returns the LoopEnabled field value
func (o *GPXPlaybackOut) GetLoopEnabled() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.LoopEnabled
}

// GetLoopEnabledOk returns a tuple with the LoopEnabled field value
// and a boolean to check if the value has been set.
func (o *GPXPlaybackOut) GetLoopEnabledOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.LoopEnabled, true
}

// SetLoopEnabled sets field value
func (o *GPXPlaybackOut) SetLoopEnabled(v bool) {
	o.LoopEnabled = v
}

// GetCurrentPointIndex returns the CurrentPointIndex field value
func (o *GPXPlaybackOut) GetCurrentPointIndex() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.CurrentPointIndex
}

// GetCurrentPointIndexOk returns a tuple with the CurrentPointIndex field value
// and a boolean to check if the value has been set.
func (o *GPXPlaybackOut) GetCurrentPointIndexOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CurrentPointIndex, true
}

// SetCurrentPointIndex sets field value
func (o *GPXPlaybackOut) SetCurrentPointIndex(v int32) {
	o.CurrentPointIndex = v
}

// GetProgressPercent returns the ProgressPercent field value
func (o *GPXPlaybackOut) GetProgressPercent() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.ProgressPercent
}

// GetProgressPercentOk returns a tuple with the ProgressPercent field value
// and a boolean to check if the value has been set.
func (o *GPXPlaybackOut) GetProgressPercentOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ProgressPercent, true
}

// SetProgressPercent sets field value
func (o *GPXPlaybackOut) SetProgressPercent(v float32) {
	o.ProgressPercent = v
}

// GetEventsTriggered returns the EventsTriggered field value
func (o *GPXPlaybackOut) GetEventsTriggered() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.EventsTriggered
}

// GetEventsTriggeredOk returns a tuple with the EventsTriggered field value
// and a boolean to check if the value has been set.
func (o *GPXPlaybackOut) GetEventsTriggeredOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.EventsTriggered, true
}

// SetEventsTriggered sets field value
func (o *GPXPlaybackOut) SetEventsTriggered(v int32) {
	o.EventsTriggered = v
}

// GetStartedAt returns the StartedAt field value
// If the value is explicit nil, the zero value for string will be returned
func (o *GPXPlaybackOut) GetStartedAt() string {
	if o == nil || o.StartedAt.Get() == nil {
		var ret string
		return ret
	}

	return *o.StartedAt.Get()
}

// GetStartedAtOk returns a tuple with the StartedAt field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GPXPlaybackOut) GetStartedAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.StartedAt.Get(), o.StartedAt.IsSet()
}

// SetStartedAt sets field value
func (o *GPXPlaybackOut) SetStartedAt(v string) {
	o.StartedAt.Set(&v)
}

// GetPausedAt returns the PausedAt field value
// If the value is explicit nil, the zero value for string will be returned
func (o *GPXPlaybackOut) GetPausedAt() string {
	if o == nil || o.PausedAt.Get() == nil {
		var ret string
		return ret
	}

	return *o.PausedAt.Get()
}

// GetPausedAtOk returns a tuple with the PausedAt field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GPXPlaybackOut) GetPausedAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.PausedAt.Get(), o.PausedAt.IsSet()
}

// SetPausedAt sets field value
func (o *GPXPlaybackOut) SetPausedAt(v string) {
	o.PausedAt.Set(&v)
}

// GetCompletedAt returns the CompletedAt field value
// If the value is explicit nil, the zero value for string will be returned
func (o *GPXPlaybackOut) GetCompletedAt() string {
	if o == nil || o.CompletedAt.Get() == nil {
		var ret string
		return ret
	}

	return *o.CompletedAt.Get()
}

// GetCompletedAtOk returns a tuple with the CompletedAt field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GPXPlaybackOut) GetCompletedAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.CompletedAt.Get(), o.CompletedAt.IsSet()
}

// SetCompletedAt sets field value
func (o *GPXPlaybackOut) SetCompletedAt(v string) {
	o.CompletedAt.Set(&v)
}

// GetErrorMessage returns the ErrorMessage field value
func (o *GPXPlaybackOut) GetErrorMessage() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ErrorMessage
}

// GetErrorMessageOk returns a tuple with the ErrorMessage field value
// and a boolean to check if the value has been set.
func (o *GPXPlaybackOut) GetErrorMessageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ErrorMessage, true
}

// SetErrorMessage sets field value
func (o *GPXPlaybackOut) SetErrorMessage(v string) {
	o.ErrorMessage = v
}

func (o GPXPlaybackOut) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GPXPlaybackOut) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["route_id"] = o.RouteId
	toSerialize["route_name"] = o.RouteName
	toSerialize["device_id"] = o.DeviceId
	toSerialize["status"] = o.Status
	toSerialize["speed_multiplier"] = o.SpeedMultiplier
	toSerialize["loop_enabled"] = o.LoopEnabled
	toSerialize["current_point_index"] = o.CurrentPointIndex
	toSerialize["progress_percent"] = o.ProgressPercent
	toSerialize["events_triggered"] = o.EventsTriggered
	toSerialize["started_at"] = o.StartedAt.Get()
	toSerialize["paused_at"] = o.PausedAt.Get()
	toSerialize["completed_at"] = o.CompletedAt.Get()
	toSerialize["error_message"] = o.ErrorMessage
	return toSerialize, nil
}

func (o *GPXPlaybackOut) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"route_id",
		"route_name",
		"device_id",
		"status",
		"speed_multiplier",
		"loop_enabled",
		"current_point_index",
		"progress_percent",
		"events_triggered",
		"started_at",
		"paused_at",
		"completed_at",
		"error_message",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGPXPlaybackOut := _GPXPlaybackOut{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varGPXPlaybackOut)

	if err != nil {
		return err
	}

	*o = GPXPlaybackOut(varGPXPlaybackOut)

	return err
}

type NullableGPXPlaybackOut struct {
	value *GPXPlaybackOut
	isSet bool
}

func (v NullableGPXPlaybackOut) Get() *GPXPlaybackOut {
	return v.value
}

func (v *NullableGPXPlaybackOut) Set(val *GPXPlaybackOut) {
	v.value = val
	v.isSet = true
}

func (v NullableGPXPlaybackOut) IsSet() bool {
	return v.isSet
}

func (v *NullableGPXPlaybackOut) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGPXPlaybackOut(val *GPXPlaybackOut) *NullableGPXPlaybackOut {
	return &NullableGPXPlaybackOut{value: val, isSet: true}
}

func (v NullableGPXPlaybackOut) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGPXPlaybackOut) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


