/*
SpatialFlow API

Real-time geospatial automation platform API.  ## Authentication  **API Key:** Include `X-API-Key` header **JWT Token:** Include `Authorization: Bearer <token>` header  ## Rate Limits  - Authenticated: 1,000 requests per hour (per API key, JWT, or session) - Anonymous: 100 requests per hour  ## Webhook Verification  Outbound webhooks include HMAC-SHA256 signatures in `X-SF-Signature` header.  ## Support  - Documentation: https://docs.spatialflow.io - GitHub: https://github.com/spatialflow/spatialflow - Email: support@spatialflow.io     

API version: v1.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package generated

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ConfigurationResetResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ConfigurationResetResponse{}

// ConfigurationResetResponse Response for configuration reset.
type ConfigurationResetResponse struct {
	Success bool `json:"success"`
	NewSource string `json:"new_source"`
	EffectiveValue NullableAnyOf `json:"effective_value,omitempty"`
	Error NullableString `json:"error,omitempty"`
}

type _ConfigurationResetResponse ConfigurationResetResponse

// NewConfigurationResetResponse instantiates a new ConfigurationResetResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewConfigurationResetResponse(success bool, newSource string) *ConfigurationResetResponse {
	this := ConfigurationResetResponse{}
	this.Success = success
	this.NewSource = newSource
	return &this
}

// NewConfigurationResetResponseWithDefaults instantiates a new ConfigurationResetResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewConfigurationResetResponseWithDefaults() *ConfigurationResetResponse {
	this := ConfigurationResetResponse{}
	return &this
}

// GetSuccess returns the Success field value
func (o *ConfigurationResetResponse) GetSuccess() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Success
}

// GetSuccessOk returns a tuple with the Success field value
// and a boolean to check if the value has been set.
func (o *ConfigurationResetResponse) GetSuccessOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Success, true
}

// SetSuccess sets field value
func (o *ConfigurationResetResponse) SetSuccess(v bool) {
	o.Success = v
}

// GetNewSource returns the NewSource field value
func (o *ConfigurationResetResponse) GetNewSource() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.NewSource
}

// GetNewSourceOk returns a tuple with the NewSource field value
// and a boolean to check if the value has been set.
func (o *ConfigurationResetResponse) GetNewSourceOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.NewSource, true
}

// SetNewSource sets field value
func (o *ConfigurationResetResponse) SetNewSource(v string) {
	o.NewSource = v
}

// GetEffectiveValue returns the EffectiveValue field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ConfigurationResetResponse) GetEffectiveValue() AnyOf {
	if o == nil || IsNil(o.EffectiveValue.Get()) {
		var ret AnyOf
		return ret
	}
	return *o.EffectiveValue.Get()
}

// GetEffectiveValueOk returns a tuple with the EffectiveValue field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ConfigurationResetResponse) GetEffectiveValueOk() (*AnyOf, bool) {
	if o == nil {
		return nil, false
	}
	return o.EffectiveValue.Get(), o.EffectiveValue.IsSet()
}

// HasEffectiveValue returns a boolean if a field has been set.
func (o *ConfigurationResetResponse) HasEffectiveValue() bool {
	if o != nil && o.EffectiveValue.IsSet() {
		return true
	}

	return false
}

// SetEffectiveValue gets a reference to the given NullableAnyOf and assigns it to the EffectiveValue field.
func (o *ConfigurationResetResponse) SetEffectiveValue(v AnyOf) {
	o.EffectiveValue.Set(&v)
}
// SetEffectiveValueNil sets the value for EffectiveValue to be an explicit nil
func (o *ConfigurationResetResponse) SetEffectiveValueNil() {
	o.EffectiveValue.Set(nil)
}

// UnsetEffectiveValue ensures that no value is present for EffectiveValue, not even an explicit nil
func (o *ConfigurationResetResponse) UnsetEffectiveValue() {
	o.EffectiveValue.Unset()
}

// GetError returns the Error field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ConfigurationResetResponse) GetError() string {
	if o == nil || IsNil(o.Error.Get()) {
		var ret string
		return ret
	}
	return *o.Error.Get()
}

// GetErrorOk returns a tuple with the Error field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ConfigurationResetResponse) GetErrorOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Error.Get(), o.Error.IsSet()
}

// HasError returns a boolean if a field has been set.
func (o *ConfigurationResetResponse) HasError() bool {
	if o != nil && o.Error.IsSet() {
		return true
	}

	return false
}

// SetError gets a reference to the given NullableString and assigns it to the Error field.
func (o *ConfigurationResetResponse) SetError(v string) {
	o.Error.Set(&v)
}
// SetErrorNil sets the value for Error to be an explicit nil
func (o *ConfigurationResetResponse) SetErrorNil() {
	o.Error.Set(nil)
}

// UnsetError ensures that no value is present for Error, not even an explicit nil
func (o *ConfigurationResetResponse) UnsetError() {
	o.Error.Unset()
}

func (o ConfigurationResetResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ConfigurationResetResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["success"] = o.Success
	toSerialize["new_source"] = o.NewSource
	if o.EffectiveValue.IsSet() {
		toSerialize["effective_value"] = o.EffectiveValue.Get()
	}
	if o.Error.IsSet() {
		toSerialize["error"] = o.Error.Get()
	}
	return toSerialize, nil
}

func (o *ConfigurationResetResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"success",
		"new_source",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varConfigurationResetResponse := _ConfigurationResetResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varConfigurationResetResponse)

	if err != nil {
		return err
	}

	*o = ConfigurationResetResponse(varConfigurationResetResponse)

	return err
}

type NullableConfigurationResetResponse struct {
	value *ConfigurationResetResponse
	isSet bool
}

func (v NullableConfigurationResetResponse) Get() *ConfigurationResetResponse {
	return v.value
}

func (v *NullableConfigurationResetResponse) Set(val *ConfigurationResetResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableConfigurationResetResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableConfigurationResetResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableConfigurationResetResponse(val *ConfigurationResetResponse) *NullableConfigurationResetResponse {
	return &NullableConfigurationResetResponse{value: val, isSet: true}
}

func (v NullableConfigurationResetResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableConfigurationResetResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


