/*
SpatialFlow API

Real-time geospatial automation platform API.  ## Authentication  **API Key:** Include `X-API-Key` header **JWT Token:** Include `Authorization: Bearer <token>` header  ## Rate Limits  - Authenticated: 1,000 requests per hour (per API key, JWT, or session) - Anonymous: 100 requests per hour  ## Webhook Verification  Outbound webhooks include HMAC-SHA256 signatures in `X-SF-Signature` header.  ## Support  - Documentation: https://docs.spatialflow.io/ - Email: support@spatialflow.io     

API version: v1.36.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package generated

import (
	"encoding/json"
)

// checks if the BatchResendIn type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BatchResendIn{}

// BatchResendIn Request payload for POST /invitations/resend-missing.  `invitation_ids` names exactly which invitations to reissue -- what the print sheet sends, since it already knows which rows have no link in this tab. Omitted (or null), it selects the newest pending page in the caller's workspace. If that page is capped, pass the returned `next_cursor` as `before` to continue through the original keyset window without selecting the newer replacement rows created by earlier pages.
type BatchResendIn struct {
	InvitationIds []string `json:"invitation_ids,omitempty"`
	Before NullableString `json:"before,omitempty"`
}

// NewBatchResendIn instantiates a new BatchResendIn object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBatchResendIn() *BatchResendIn {
	this := BatchResendIn{}
	return &this
}

// NewBatchResendInWithDefaults instantiates a new BatchResendIn object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBatchResendInWithDefaults() *BatchResendIn {
	this := BatchResendIn{}
	return &this
}

// GetInvitationIds returns the InvitationIds field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *BatchResendIn) GetInvitationIds() []string {
	if o == nil {
		var ret []string
		return ret
	}
	return o.InvitationIds
}

// GetInvitationIdsOk returns a tuple with the InvitationIds field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *BatchResendIn) GetInvitationIdsOk() ([]string, bool) {
	if o == nil || IsNil(o.InvitationIds) {
		return nil, false
	}
	return o.InvitationIds, true
}

// HasInvitationIds returns a boolean if a field has been set.
func (o *BatchResendIn) HasInvitationIds() bool {
	if o != nil && !IsNil(o.InvitationIds) {
		return true
	}

	return false
}

// SetInvitationIds gets a reference to the given []string and assigns it to the InvitationIds field.
func (o *BatchResendIn) SetInvitationIds(v []string) {
	o.InvitationIds = v
}

// GetBefore returns the Before field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *BatchResendIn) GetBefore() string {
	if o == nil || IsNil(o.Before.Get()) {
		var ret string
		return ret
	}
	return *o.Before.Get()
}

// GetBeforeOk returns a tuple with the Before field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *BatchResendIn) GetBeforeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Before.Get(), o.Before.IsSet()
}

// HasBefore returns a boolean if a field has been set.
func (o *BatchResendIn) HasBefore() bool {
	if o != nil && o.Before.IsSet() {
		return true
	}

	return false
}

// SetBefore gets a reference to the given NullableString and assigns it to the Before field.
func (o *BatchResendIn) SetBefore(v string) {
	o.Before.Set(&v)
}
// SetBeforeNil sets the value for Before to be an explicit nil
func (o *BatchResendIn) SetBeforeNil() {
	o.Before.Set(nil)
}

// UnsetBefore ensures that no value is present for Before, not even an explicit nil
func (o *BatchResendIn) UnsetBefore() {
	o.Before.Unset()
}

func (o BatchResendIn) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BatchResendIn) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.InvitationIds != nil {
		toSerialize["invitation_ids"] = o.InvitationIds
	}
	if o.Before.IsSet() {
		toSerialize["before"] = o.Before.Get()
	}
	return toSerialize, nil
}

type NullableBatchResendIn struct {
	value *BatchResendIn
	isSet bool
}

func (v NullableBatchResendIn) Get() *BatchResendIn {
	return v.value
}

func (v *NullableBatchResendIn) Set(val *BatchResendIn) {
	v.value = val
	v.isSet = true
}

func (v NullableBatchResendIn) IsSet() bool {
	return v.isSet
}

func (v *NullableBatchResendIn) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBatchResendIn(val *BatchResendIn) *NullableBatchResendIn {
	return &NullableBatchResendIn{value: val, isSet: true}
}

func (v NullableBatchResendIn) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBatchResendIn) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


