/*
SpatialFlow API

Real-time geospatial automation platform API.  ## Authentication  **API Key:** Include `X-API-Key` header **JWT Token:** Include `Authorization: Bearer <token>` header  ## Rate Limits  - Authenticated: 1,000 requests per hour (per API key, JWT, or session) - Anonymous: 100 requests per hour  ## Webhook Verification  Outbound webhooks include HMAC-SHA256 signatures in `X-SF-Signature` header.  ## Support  - Documentation: https://docs.spatialflow.io - GitHub: https://github.com/spatialflow/spatialflow - Email: support@spatialflow.io     

API version: v1.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package generated

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the GeofenceEventOut type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GeofenceEventOut{}

// GeofenceEventOut struct for GeofenceEventOut
type GeofenceEventOut struct {
	Id string `json:"id"`
	EventType string `json:"event_type"`
	Device EventDeviceOut `json:"device"`
	Geofence EventGeofenceOut `json:"geofence"`
	Timestamp string `json:"timestamp"`
	Location EventLocationOut `json:"location"`
	WorkflowsTriggered []string `json:"workflows_triggered,omitempty"`
	WebhooksTriggered []string `json:"webhooks_triggered,omitempty"`
	CreatedAt string `json:"created_at"`
}

type _GeofenceEventOut GeofenceEventOut

// NewGeofenceEventOut instantiates a new GeofenceEventOut object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGeofenceEventOut(id string, eventType string, device EventDeviceOut, geofence EventGeofenceOut, timestamp string, location EventLocationOut, createdAt string) *GeofenceEventOut {
	this := GeofenceEventOut{}
	this.Id = id
	this.EventType = eventType
	this.Device = device
	this.Geofence = geofence
	this.Timestamp = timestamp
	this.Location = location
	this.CreatedAt = createdAt
	return &this
}

// NewGeofenceEventOutWithDefaults instantiates a new GeofenceEventOut object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGeofenceEventOutWithDefaults() *GeofenceEventOut {
	this := GeofenceEventOut{}
	return &this
}

// GetId returns the Id field value
func (o *GeofenceEventOut) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *GeofenceEventOut) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *GeofenceEventOut) SetId(v string) {
	o.Id = v
}

// GetEventType returns the EventType field value
func (o *GeofenceEventOut) GetEventType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.EventType
}

// GetEventTypeOk returns a tuple with the EventType field value
// and a boolean to check if the value has been set.
func (o *GeofenceEventOut) GetEventTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.EventType, true
}

// SetEventType sets field value
func (o *GeofenceEventOut) SetEventType(v string) {
	o.EventType = v
}

// GetDevice returns the Device field value
func (o *GeofenceEventOut) GetDevice() EventDeviceOut {
	if o == nil {
		var ret EventDeviceOut
		return ret
	}

	return o.Device
}

// GetDeviceOk returns a tuple with the Device field value
// and a boolean to check if the value has been set.
func (o *GeofenceEventOut) GetDeviceOk() (*EventDeviceOut, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Device, true
}

// SetDevice sets field value
func (o *GeofenceEventOut) SetDevice(v EventDeviceOut) {
	o.Device = v
}

// GetGeofence returns the Geofence field value
func (o *GeofenceEventOut) GetGeofence() EventGeofenceOut {
	if o == nil {
		var ret EventGeofenceOut
		return ret
	}

	return o.Geofence
}

// GetGeofenceOk returns a tuple with the Geofence field value
// and a boolean to check if the value has been set.
func (o *GeofenceEventOut) GetGeofenceOk() (*EventGeofenceOut, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Geofence, true
}

// SetGeofence sets field value
func (o *GeofenceEventOut) SetGeofence(v EventGeofenceOut) {
	o.Geofence = v
}

// GetTimestamp returns the Timestamp field value
func (o *GeofenceEventOut) GetTimestamp() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Timestamp
}

// GetTimestampOk returns a tuple with the Timestamp field value
// and a boolean to check if the value has been set.
func (o *GeofenceEventOut) GetTimestampOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Timestamp, true
}

// SetTimestamp sets field value
func (o *GeofenceEventOut) SetTimestamp(v string) {
	o.Timestamp = v
}

// GetLocation returns the Location field value
func (o *GeofenceEventOut) GetLocation() EventLocationOut {
	if o == nil {
		var ret EventLocationOut
		return ret
	}

	return o.Location
}

// GetLocationOk returns a tuple with the Location field value
// and a boolean to check if the value has been set.
func (o *GeofenceEventOut) GetLocationOk() (*EventLocationOut, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Location, true
}

// SetLocation sets field value
func (o *GeofenceEventOut) SetLocation(v EventLocationOut) {
	o.Location = v
}

// GetWorkflowsTriggered returns the WorkflowsTriggered field value if set, zero value otherwise.
func (o *GeofenceEventOut) GetWorkflowsTriggered() []string {
	if o == nil || IsNil(o.WorkflowsTriggered) {
		var ret []string
		return ret
	}
	return o.WorkflowsTriggered
}

// GetWorkflowsTriggeredOk returns a tuple with the WorkflowsTriggered field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GeofenceEventOut) GetWorkflowsTriggeredOk() ([]string, bool) {
	if o == nil || IsNil(o.WorkflowsTriggered) {
		return nil, false
	}
	return o.WorkflowsTriggered, true
}

// HasWorkflowsTriggered returns a boolean if a field has been set.
func (o *GeofenceEventOut) HasWorkflowsTriggered() bool {
	if o != nil && !IsNil(o.WorkflowsTriggered) {
		return true
	}

	return false
}

// SetWorkflowsTriggered gets a reference to the given []string and assigns it to the WorkflowsTriggered field.
func (o *GeofenceEventOut) SetWorkflowsTriggered(v []string) {
	o.WorkflowsTriggered = v
}

// GetWebhooksTriggered returns the WebhooksTriggered field value if set, zero value otherwise.
func (o *GeofenceEventOut) GetWebhooksTriggered() []string {
	if o == nil || IsNil(o.WebhooksTriggered) {
		var ret []string
		return ret
	}
	return o.WebhooksTriggered
}

// GetWebhooksTriggeredOk returns a tuple with the WebhooksTriggered field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GeofenceEventOut) GetWebhooksTriggeredOk() ([]string, bool) {
	if o == nil || IsNil(o.WebhooksTriggered) {
		return nil, false
	}
	return o.WebhooksTriggered, true
}

// HasWebhooksTriggered returns a boolean if a field has been set.
func (o *GeofenceEventOut) HasWebhooksTriggered() bool {
	if o != nil && !IsNil(o.WebhooksTriggered) {
		return true
	}

	return false
}

// SetWebhooksTriggered gets a reference to the given []string and assigns it to the WebhooksTriggered field.
func (o *GeofenceEventOut) SetWebhooksTriggered(v []string) {
	o.WebhooksTriggered = v
}

// GetCreatedAt returns the CreatedAt field value
func (o *GeofenceEventOut) GetCreatedAt() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *GeofenceEventOut) GetCreatedAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *GeofenceEventOut) SetCreatedAt(v string) {
	o.CreatedAt = v
}

func (o GeofenceEventOut) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GeofenceEventOut) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["event_type"] = o.EventType
	toSerialize["device"] = o.Device
	toSerialize["geofence"] = o.Geofence
	toSerialize["timestamp"] = o.Timestamp
	toSerialize["location"] = o.Location
	if !IsNil(o.WorkflowsTriggered) {
		toSerialize["workflows_triggered"] = o.WorkflowsTriggered
	}
	if !IsNil(o.WebhooksTriggered) {
		toSerialize["webhooks_triggered"] = o.WebhooksTriggered
	}
	toSerialize["created_at"] = o.CreatedAt
	return toSerialize, nil
}

func (o *GeofenceEventOut) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"event_type",
		"device",
		"geofence",
		"timestamp",
		"location",
		"created_at",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGeofenceEventOut := _GeofenceEventOut{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varGeofenceEventOut)

	if err != nil {
		return err
	}

	*o = GeofenceEventOut(varGeofenceEventOut)

	return err
}

type NullableGeofenceEventOut struct {
	value *GeofenceEventOut
	isSet bool
}

func (v NullableGeofenceEventOut) Get() *GeofenceEventOut {
	return v.value
}

func (v *NullableGeofenceEventOut) Set(val *GeofenceEventOut) {
	v.value = val
	v.isSet = true
}

func (v NullableGeofenceEventOut) IsSet() bool {
	return v.isSet
}

func (v *NullableGeofenceEventOut) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGeofenceEventOut(val *GeofenceEventOut) *NullableGeofenceEventOut {
	return &NullableGeofenceEventOut{value: val, isSet: true}
}

func (v NullableGeofenceEventOut) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGeofenceEventOut) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


