/*
SpatialFlow API

Real-time geospatial automation platform API.  ## Authentication  **API Key:** Include `X-API-Key` header **JWT Token:** Include `Authorization: Bearer <token>` header  ## Rate Limits  - Authenticated: 1,000 requests per hour (per API key, JWT, or session) - Anonymous: 100 requests per hour  ## Webhook Verification  Outbound webhooks include HMAC-SHA256 signatures in `X-SF-Signature` header.  ## Support  - Documentation: https://docs.spatialflow.io - GitHub: https://github.com/spatialflow/spatialflow - Email: support@spatialflow.io     

API version: v1.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package generated

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the AdminUserStatsResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AdminUserStatsResponse{}

// AdminUserStatsResponse Response for admin user stats endpoint.  Returns aggregated API call counts per user within a date range. Default: last 30 days, max 90 days. Max 100 results per page.
type AdminUserStatsResponse struct {
	Users []UserApiStats `json:"users"`
	Total int32 `json:"total"`
	Days int32 `json:"days"`
	Offset int32 `json:"offset"`
	Limit int32 `json:"limit"`
	HasMore bool `json:"has_more"`
}

type _AdminUserStatsResponse AdminUserStatsResponse

// NewAdminUserStatsResponse instantiates a new AdminUserStatsResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAdminUserStatsResponse(users []UserApiStats, total int32, days int32, offset int32, limit int32, hasMore bool) *AdminUserStatsResponse {
	this := AdminUserStatsResponse{}
	this.Users = users
	this.Total = total
	this.Days = days
	this.Offset = offset
	this.Limit = limit
	this.HasMore = hasMore
	return &this
}

// NewAdminUserStatsResponseWithDefaults instantiates a new AdminUserStatsResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAdminUserStatsResponseWithDefaults() *AdminUserStatsResponse {
	this := AdminUserStatsResponse{}
	return &this
}

// GetUsers returns the Users field value
func (o *AdminUserStatsResponse) GetUsers() []UserApiStats {
	if o == nil {
		var ret []UserApiStats
		return ret
	}

	return o.Users
}

// GetUsersOk returns a tuple with the Users field value
// and a boolean to check if the value has been set.
func (o *AdminUserStatsResponse) GetUsersOk() ([]UserApiStats, bool) {
	if o == nil {
		return nil, false
	}
	return o.Users, true
}

// SetUsers sets field value
func (o *AdminUserStatsResponse) SetUsers(v []UserApiStats) {
	o.Users = v
}

// GetTotal returns the Total field value
func (o *AdminUserStatsResponse) GetTotal() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Total
}

// GetTotalOk returns a tuple with the Total field value
// and a boolean to check if the value has been set.
func (o *AdminUserStatsResponse) GetTotalOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Total, true
}

// SetTotal sets field value
func (o *AdminUserStatsResponse) SetTotal(v int32) {
	o.Total = v
}

// GetDays returns the Days field value
func (o *AdminUserStatsResponse) GetDays() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Days
}

// GetDaysOk returns a tuple with the Days field value
// and a boolean to check if the value has been set.
func (o *AdminUserStatsResponse) GetDaysOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Days, true
}

// SetDays sets field value
func (o *AdminUserStatsResponse) SetDays(v int32) {
	o.Days = v
}

// GetOffset returns the Offset field value
func (o *AdminUserStatsResponse) GetOffset() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Offset
}

// GetOffsetOk returns a tuple with the Offset field value
// and a boolean to check if the value has been set.
func (o *AdminUserStatsResponse) GetOffsetOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Offset, true
}

// SetOffset sets field value
func (o *AdminUserStatsResponse) SetOffset(v int32) {
	o.Offset = v
}

// GetLimit returns the Limit field value
func (o *AdminUserStatsResponse) GetLimit() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Limit
}

// GetLimitOk returns a tuple with the Limit field value
// and a boolean to check if the value has been set.
func (o *AdminUserStatsResponse) GetLimitOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Limit, true
}

// SetLimit sets field value
func (o *AdminUserStatsResponse) SetLimit(v int32) {
	o.Limit = v
}

// GetHasMore returns the HasMore field value
func (o *AdminUserStatsResponse) GetHasMore() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.HasMore
}

// GetHasMoreOk returns a tuple with the HasMore field value
// and a boolean to check if the value has been set.
func (o *AdminUserStatsResponse) GetHasMoreOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.HasMore, true
}

// SetHasMore sets field value
func (o *AdminUserStatsResponse) SetHasMore(v bool) {
	o.HasMore = v
}

func (o AdminUserStatsResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AdminUserStatsResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["users"] = o.Users
	toSerialize["total"] = o.Total
	toSerialize["days"] = o.Days
	toSerialize["offset"] = o.Offset
	toSerialize["limit"] = o.Limit
	toSerialize["has_more"] = o.HasMore
	return toSerialize, nil
}

func (o *AdminUserStatsResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"users",
		"total",
		"days",
		"offset",
		"limit",
		"has_more",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAdminUserStatsResponse := _AdminUserStatsResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAdminUserStatsResponse)

	if err != nil {
		return err
	}

	*o = AdminUserStatsResponse(varAdminUserStatsResponse)

	return err
}

type NullableAdminUserStatsResponse struct {
	value *AdminUserStatsResponse
	isSet bool
}

func (v NullableAdminUserStatsResponse) Get() *AdminUserStatsResponse {
	return v.value
}

func (v *NullableAdminUserStatsResponse) Set(val *AdminUserStatsResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableAdminUserStatsResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableAdminUserStatsResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAdminUserStatsResponse(val *AdminUserStatsResponse) *NullableAdminUserStatsResponse {
	return &NullableAdminUserStatsResponse{value: val, isSet: true}
}

func (v NullableAdminUserStatsResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAdminUserStatsResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


