/*
SpatialFlow API

Real-time geospatial automation platform API.  ## Authentication  **API Key:** Include `X-API-Key` header **JWT Token:** Include `Authorization: Bearer <token>` header  ## Rate Limits  - Authenticated: 1,000 requests per hour (per API key, JWT, or session) - Anonymous: 100 requests per hour  ## Webhook Verification  Outbound webhooks include HMAC-SHA256 signatures in `X-SF-Signature` header.  ## Support  - Documentation: https://docs.spatialflow.io - GitHub: https://github.com/spatialflow/spatialflow - Email: support@spatialflow.io     

API version: v1.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package generated

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CreateFromTemplateIn type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateFromTemplateIn{}

// CreateFromTemplateIn struct for CreateFromTemplateIn
type CreateFromTemplateIn struct {
	Name string `json:"name"`
	Customizations map[string]interface{} `json:"customizations,omitempty"`
}

type _CreateFromTemplateIn CreateFromTemplateIn

// NewCreateFromTemplateIn instantiates a new CreateFromTemplateIn object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateFromTemplateIn(name string) *CreateFromTemplateIn {
	this := CreateFromTemplateIn{}
	this.Name = name
	return &this
}

// NewCreateFromTemplateInWithDefaults instantiates a new CreateFromTemplateIn object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateFromTemplateInWithDefaults() *CreateFromTemplateIn {
	this := CreateFromTemplateIn{}
	return &this
}

// GetName returns the Name field value
func (o *CreateFromTemplateIn) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *CreateFromTemplateIn) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *CreateFromTemplateIn) SetName(v string) {
	o.Name = v
}

// GetCustomizations returns the Customizations field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CreateFromTemplateIn) GetCustomizations() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}
	return o.Customizations
}

// GetCustomizationsOk returns a tuple with the Customizations field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreateFromTemplateIn) GetCustomizationsOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Customizations) {
		return map[string]interface{}{}, false
	}
	return o.Customizations, true
}

// HasCustomizations returns a boolean if a field has been set.
func (o *CreateFromTemplateIn) HasCustomizations() bool {
	if o != nil && !IsNil(o.Customizations) {
		return true
	}

	return false
}

// SetCustomizations gets a reference to the given map[string]interface{} and assigns it to the Customizations field.
func (o *CreateFromTemplateIn) SetCustomizations(v map[string]interface{}) {
	o.Customizations = v
}

func (o CreateFromTemplateIn) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateFromTemplateIn) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	if o.Customizations != nil {
		toSerialize["customizations"] = o.Customizations
	}
	return toSerialize, nil
}

func (o *CreateFromTemplateIn) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateFromTemplateIn := _CreateFromTemplateIn{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreateFromTemplateIn)

	if err != nil {
		return err
	}

	*o = CreateFromTemplateIn(varCreateFromTemplateIn)

	return err
}

type NullableCreateFromTemplateIn struct {
	value *CreateFromTemplateIn
	isSet bool
}

func (v NullableCreateFromTemplateIn) Get() *CreateFromTemplateIn {
	return v.value
}

func (v *NullableCreateFromTemplateIn) Set(val *CreateFromTemplateIn) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateFromTemplateIn) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateFromTemplateIn) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateFromTemplateIn(val *CreateFromTemplateIn) *NullableCreateFromTemplateIn {
	return &NullableCreateFromTemplateIn{value: val, isSet: true}
}

func (v NullableCreateFromTemplateIn) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateFromTemplateIn) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


