/*
SpatialFlow API

Real-time geospatial automation platform API.  ## Authentication  **API Key:** Include `X-API-Key` header **JWT Token:** Include `Authorization: Bearer <token>` header  ## Rate Limits  - Authenticated: 1,000 requests per hour (per API key, JWT, or session) - Anonymous: 100 requests per hour  ## Webhook Verification  Outbound webhooks include HMAC-SHA256 signatures in `X-SF-Signature` header.  ## Support  - Documentation: https://docs.spatialflow.io - GitHub: https://github.com/spatialflow/spatialflow - Email: support@spatialflow.io     

API version: v1.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package generated

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the AuditLogListResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AuditLogListResponse{}

// AuditLogListResponse struct for AuditLogListResponse
type AuditLogListResponse struct {
	Logs []AuditLogOut `json:"logs"`
	Total int32 `json:"total"`
	Page int32 `json:"page"`
	PageSize int32 `json:"page_size"`
	HasMore bool `json:"has_more"`
}

type _AuditLogListResponse AuditLogListResponse

// NewAuditLogListResponse instantiates a new AuditLogListResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAuditLogListResponse(logs []AuditLogOut, total int32, page int32, pageSize int32, hasMore bool) *AuditLogListResponse {
	this := AuditLogListResponse{}
	this.Logs = logs
	this.Total = total
	this.Page = page
	this.PageSize = pageSize
	this.HasMore = hasMore
	return &this
}

// NewAuditLogListResponseWithDefaults instantiates a new AuditLogListResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAuditLogListResponseWithDefaults() *AuditLogListResponse {
	this := AuditLogListResponse{}
	return &this
}

// GetLogs returns the Logs field value
func (o *AuditLogListResponse) GetLogs() []AuditLogOut {
	if o == nil {
		var ret []AuditLogOut
		return ret
	}

	return o.Logs
}

// GetLogsOk returns a tuple with the Logs field value
// and a boolean to check if the value has been set.
func (o *AuditLogListResponse) GetLogsOk() ([]AuditLogOut, bool) {
	if o == nil {
		return nil, false
	}
	return o.Logs, true
}

// SetLogs sets field value
func (o *AuditLogListResponse) SetLogs(v []AuditLogOut) {
	o.Logs = v
}

// GetTotal returns the Total field value
func (o *AuditLogListResponse) GetTotal() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Total
}

// GetTotalOk returns a tuple with the Total field value
// and a boolean to check if the value has been set.
func (o *AuditLogListResponse) GetTotalOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Total, true
}

// SetTotal sets field value
func (o *AuditLogListResponse) SetTotal(v int32) {
	o.Total = v
}

// GetPage returns the Page field value
func (o *AuditLogListResponse) GetPage() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Page
}

// GetPageOk returns a tuple with the Page field value
// and a boolean to check if the value has been set.
func (o *AuditLogListResponse) GetPageOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Page, true
}

// SetPage sets field value
func (o *AuditLogListResponse) SetPage(v int32) {
	o.Page = v
}

// GetPageSize returns the PageSize field value
func (o *AuditLogListResponse) GetPageSize() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.PageSize
}

// GetPageSizeOk returns a tuple with the PageSize field value
// and a boolean to check if the value has been set.
func (o *AuditLogListResponse) GetPageSizeOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PageSize, true
}

// SetPageSize sets field value
func (o *AuditLogListResponse) SetPageSize(v int32) {
	o.PageSize = v
}

// GetHasMore returns the HasMore field value
func (o *AuditLogListResponse) GetHasMore() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.HasMore
}

// GetHasMoreOk returns a tuple with the HasMore field value
// and a boolean to check if the value has been set.
func (o *AuditLogListResponse) GetHasMoreOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.HasMore, true
}

// SetHasMore sets field value
func (o *AuditLogListResponse) SetHasMore(v bool) {
	o.HasMore = v
}

func (o AuditLogListResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AuditLogListResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["logs"] = o.Logs
	toSerialize["total"] = o.Total
	toSerialize["page"] = o.Page
	toSerialize["page_size"] = o.PageSize
	toSerialize["has_more"] = o.HasMore
	return toSerialize, nil
}

func (o *AuditLogListResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"logs",
		"total",
		"page",
		"page_size",
		"has_more",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAuditLogListResponse := _AuditLogListResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAuditLogListResponse)

	if err != nil {
		return err
	}

	*o = AuditLogListResponse(varAuditLogListResponse)

	return err
}

type NullableAuditLogListResponse struct {
	value *AuditLogListResponse
	isSet bool
}

func (v NullableAuditLogListResponse) Get() *AuditLogListResponse {
	return v.value
}

func (v *NullableAuditLogListResponse) Set(val *AuditLogListResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableAuditLogListResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableAuditLogListResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAuditLogListResponse(val *AuditLogListResponse) *NullableAuditLogListResponse {
	return &NullableAuditLogListResponse{value: val, isSet: true}
}

func (v NullableAuditLogListResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAuditLogListResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


