/*
SpatialFlow API

Real-time geospatial automation platform API.  ## Authentication  **API Key:** Include `X-API-Key` header **JWT Token:** Include `Authorization: Bearer <token>` header  ## Rate Limits  - Authenticated: 1,000 requests per hour (per API key, JWT, or session) - Anonymous: 100 requests per hour  ## Webhook Verification  Outbound webhooks include HMAC-SHA256 signatures in `X-SF-Signature` header.  ## Support  - Documentation: https://docs.spatialflow.io - GitHub: https://github.com/spatialflow/spatialflow - Email: support@spatialflow.io     

API version: v1.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package generated

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the EnhancedWorkspaceListItem type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EnhancedWorkspaceListItem{}

// EnhancedWorkspaceListItem Workspace item with subscription and usage data.
type EnhancedWorkspaceListItem struct {
	Id string `json:"id"`
	Name string `json:"name"`
	Slug string `json:"slug"`
	BillingEmail NullableString `json:"billing_email"`
	Website NullableString `json:"website"`
	LogoUrl NullableString `json:"logo_url"`
	Timezone string `json:"timezone"`
	MemberCount int32 `json:"member_count"`
	SubscriptionTier *string `json:"subscription_tier,omitempty"`
	SubscriptionStatus *string `json:"subscription_status,omitempty"`
	UsageThisMonth *float32 `json:"usage_this_month,omitempty"`
	LastActivity NullableString `json:"last_activity,omitempty"`
	CreatedAt NullableString `json:"created_at"`
	UpdatedAt NullableString `json:"updated_at"`
}

type _EnhancedWorkspaceListItem EnhancedWorkspaceListItem

// NewEnhancedWorkspaceListItem instantiates a new EnhancedWorkspaceListItem object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEnhancedWorkspaceListItem(id string, name string, slug string, billingEmail NullableString, website NullableString, logoUrl NullableString, timezone string, memberCount int32, createdAt NullableString, updatedAt NullableString) *EnhancedWorkspaceListItem {
	this := EnhancedWorkspaceListItem{}
	this.Id = id
	this.Name = name
	this.Slug = slug
	this.BillingEmail = billingEmail
	this.Website = website
	this.LogoUrl = logoUrl
	this.Timezone = timezone
	this.MemberCount = memberCount
	var subscriptionTier string = "free"
	this.SubscriptionTier = &subscriptionTier
	var subscriptionStatus string = "none"
	this.SubscriptionStatus = &subscriptionStatus
	var usageThisMonth float32 = 0.0
	this.UsageThisMonth = &usageThisMonth
	this.CreatedAt = createdAt
	this.UpdatedAt = updatedAt
	return &this
}

// NewEnhancedWorkspaceListItemWithDefaults instantiates a new EnhancedWorkspaceListItem object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEnhancedWorkspaceListItemWithDefaults() *EnhancedWorkspaceListItem {
	this := EnhancedWorkspaceListItem{}
	var subscriptionTier string = "free"
	this.SubscriptionTier = &subscriptionTier
	var subscriptionStatus string = "none"
	this.SubscriptionStatus = &subscriptionStatus
	var usageThisMonth float32 = 0.0
	this.UsageThisMonth = &usageThisMonth
	return &this
}

// GetId returns the Id field value
func (o *EnhancedWorkspaceListItem) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *EnhancedWorkspaceListItem) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *EnhancedWorkspaceListItem) SetId(v string) {
	o.Id = v
}

// GetName returns the Name field value
func (o *EnhancedWorkspaceListItem) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *EnhancedWorkspaceListItem) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *EnhancedWorkspaceListItem) SetName(v string) {
	o.Name = v
}

// GetSlug returns the Slug field value
func (o *EnhancedWorkspaceListItem) GetSlug() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Slug
}

// GetSlugOk returns a tuple with the Slug field value
// and a boolean to check if the value has been set.
func (o *EnhancedWorkspaceListItem) GetSlugOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Slug, true
}

// SetSlug sets field value
func (o *EnhancedWorkspaceListItem) SetSlug(v string) {
	o.Slug = v
}

// GetBillingEmail returns the BillingEmail field value
// If the value is explicit nil, the zero value for string will be returned
func (o *EnhancedWorkspaceListItem) GetBillingEmail() string {
	if o == nil || o.BillingEmail.Get() == nil {
		var ret string
		return ret
	}

	return *o.BillingEmail.Get()
}

// GetBillingEmailOk returns a tuple with the BillingEmail field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *EnhancedWorkspaceListItem) GetBillingEmailOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.BillingEmail.Get(), o.BillingEmail.IsSet()
}

// SetBillingEmail sets field value
func (o *EnhancedWorkspaceListItem) SetBillingEmail(v string) {
	o.BillingEmail.Set(&v)
}

// GetWebsite returns the Website field value
// If the value is explicit nil, the zero value for string will be returned
func (o *EnhancedWorkspaceListItem) GetWebsite() string {
	if o == nil || o.Website.Get() == nil {
		var ret string
		return ret
	}

	return *o.Website.Get()
}

// GetWebsiteOk returns a tuple with the Website field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *EnhancedWorkspaceListItem) GetWebsiteOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Website.Get(), o.Website.IsSet()
}

// SetWebsite sets field value
func (o *EnhancedWorkspaceListItem) SetWebsite(v string) {
	o.Website.Set(&v)
}

// GetLogoUrl returns the LogoUrl field value
// If the value is explicit nil, the zero value for string will be returned
func (o *EnhancedWorkspaceListItem) GetLogoUrl() string {
	if o == nil || o.LogoUrl.Get() == nil {
		var ret string
		return ret
	}

	return *o.LogoUrl.Get()
}

// GetLogoUrlOk returns a tuple with the LogoUrl field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *EnhancedWorkspaceListItem) GetLogoUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.LogoUrl.Get(), o.LogoUrl.IsSet()
}

// SetLogoUrl sets field value
func (o *EnhancedWorkspaceListItem) SetLogoUrl(v string) {
	o.LogoUrl.Set(&v)
}

// GetTimezone returns the Timezone field value
func (o *EnhancedWorkspaceListItem) GetTimezone() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Timezone
}

// GetTimezoneOk returns a tuple with the Timezone field value
// and a boolean to check if the value has been set.
func (o *EnhancedWorkspaceListItem) GetTimezoneOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Timezone, true
}

// SetTimezone sets field value
func (o *EnhancedWorkspaceListItem) SetTimezone(v string) {
	o.Timezone = v
}

// GetMemberCount returns the MemberCount field value
func (o *EnhancedWorkspaceListItem) GetMemberCount() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.MemberCount
}

// GetMemberCountOk returns a tuple with the MemberCount field value
// and a boolean to check if the value has been set.
func (o *EnhancedWorkspaceListItem) GetMemberCountOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MemberCount, true
}

// SetMemberCount sets field value
func (o *EnhancedWorkspaceListItem) SetMemberCount(v int32) {
	o.MemberCount = v
}

// GetSubscriptionTier returns the SubscriptionTier field value if set, zero value otherwise.
func (o *EnhancedWorkspaceListItem) GetSubscriptionTier() string {
	if o == nil || IsNil(o.SubscriptionTier) {
		var ret string
		return ret
	}
	return *o.SubscriptionTier
}

// GetSubscriptionTierOk returns a tuple with the SubscriptionTier field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EnhancedWorkspaceListItem) GetSubscriptionTierOk() (*string, bool) {
	if o == nil || IsNil(o.SubscriptionTier) {
		return nil, false
	}
	return o.SubscriptionTier, true
}

// HasSubscriptionTier returns a boolean if a field has been set.
func (o *EnhancedWorkspaceListItem) HasSubscriptionTier() bool {
	if o != nil && !IsNil(o.SubscriptionTier) {
		return true
	}

	return false
}

// SetSubscriptionTier gets a reference to the given string and assigns it to the SubscriptionTier field.
func (o *EnhancedWorkspaceListItem) SetSubscriptionTier(v string) {
	o.SubscriptionTier = &v
}

// GetSubscriptionStatus returns the SubscriptionStatus field value if set, zero value otherwise.
func (o *EnhancedWorkspaceListItem) GetSubscriptionStatus() string {
	if o == nil || IsNil(o.SubscriptionStatus) {
		var ret string
		return ret
	}
	return *o.SubscriptionStatus
}

// GetSubscriptionStatusOk returns a tuple with the SubscriptionStatus field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EnhancedWorkspaceListItem) GetSubscriptionStatusOk() (*string, bool) {
	if o == nil || IsNil(o.SubscriptionStatus) {
		return nil, false
	}
	return o.SubscriptionStatus, true
}

// HasSubscriptionStatus returns a boolean if a field has been set.
func (o *EnhancedWorkspaceListItem) HasSubscriptionStatus() bool {
	if o != nil && !IsNil(o.SubscriptionStatus) {
		return true
	}

	return false
}

// SetSubscriptionStatus gets a reference to the given string and assigns it to the SubscriptionStatus field.
func (o *EnhancedWorkspaceListItem) SetSubscriptionStatus(v string) {
	o.SubscriptionStatus = &v
}

// GetUsageThisMonth returns the UsageThisMonth field value if set, zero value otherwise.
func (o *EnhancedWorkspaceListItem) GetUsageThisMonth() float32 {
	if o == nil || IsNil(o.UsageThisMonth) {
		var ret float32
		return ret
	}
	return *o.UsageThisMonth
}

// GetUsageThisMonthOk returns a tuple with the UsageThisMonth field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EnhancedWorkspaceListItem) GetUsageThisMonthOk() (*float32, bool) {
	if o == nil || IsNil(o.UsageThisMonth) {
		return nil, false
	}
	return o.UsageThisMonth, true
}

// HasUsageThisMonth returns a boolean if a field has been set.
func (o *EnhancedWorkspaceListItem) HasUsageThisMonth() bool {
	if o != nil && !IsNil(o.UsageThisMonth) {
		return true
	}

	return false
}

// SetUsageThisMonth gets a reference to the given float32 and assigns it to the UsageThisMonth field.
func (o *EnhancedWorkspaceListItem) SetUsageThisMonth(v float32) {
	o.UsageThisMonth = &v
}

// GetLastActivity returns the LastActivity field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *EnhancedWorkspaceListItem) GetLastActivity() string {
	if o == nil || IsNil(o.LastActivity.Get()) {
		var ret string
		return ret
	}
	return *o.LastActivity.Get()
}

// GetLastActivityOk returns a tuple with the LastActivity field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *EnhancedWorkspaceListItem) GetLastActivityOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.LastActivity.Get(), o.LastActivity.IsSet()
}

// HasLastActivity returns a boolean if a field has been set.
func (o *EnhancedWorkspaceListItem) HasLastActivity() bool {
	if o != nil && o.LastActivity.IsSet() {
		return true
	}

	return false
}

// SetLastActivity gets a reference to the given NullableString and assigns it to the LastActivity field.
func (o *EnhancedWorkspaceListItem) SetLastActivity(v string) {
	o.LastActivity.Set(&v)
}
// SetLastActivityNil sets the value for LastActivity to be an explicit nil
func (o *EnhancedWorkspaceListItem) SetLastActivityNil() {
	o.LastActivity.Set(nil)
}

// UnsetLastActivity ensures that no value is present for LastActivity, not even an explicit nil
func (o *EnhancedWorkspaceListItem) UnsetLastActivity() {
	o.LastActivity.Unset()
}

// GetCreatedAt returns the CreatedAt field value
// If the value is explicit nil, the zero value for string will be returned
func (o *EnhancedWorkspaceListItem) GetCreatedAt() string {
	if o == nil || o.CreatedAt.Get() == nil {
		var ret string
		return ret
	}

	return *o.CreatedAt.Get()
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *EnhancedWorkspaceListItem) GetCreatedAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.CreatedAt.Get(), o.CreatedAt.IsSet()
}

// SetCreatedAt sets field value
func (o *EnhancedWorkspaceListItem) SetCreatedAt(v string) {
	o.CreatedAt.Set(&v)
}

// GetUpdatedAt returns the UpdatedAt field value
// If the value is explicit nil, the zero value for string will be returned
func (o *EnhancedWorkspaceListItem) GetUpdatedAt() string {
	if o == nil || o.UpdatedAt.Get() == nil {
		var ret string
		return ret
	}

	return *o.UpdatedAt.Get()
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *EnhancedWorkspaceListItem) GetUpdatedAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.UpdatedAt.Get(), o.UpdatedAt.IsSet()
}

// SetUpdatedAt sets field value
func (o *EnhancedWorkspaceListItem) SetUpdatedAt(v string) {
	o.UpdatedAt.Set(&v)
}

func (o EnhancedWorkspaceListItem) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EnhancedWorkspaceListItem) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["name"] = o.Name
	toSerialize["slug"] = o.Slug
	toSerialize["billing_email"] = o.BillingEmail.Get()
	toSerialize["website"] = o.Website.Get()
	toSerialize["logo_url"] = o.LogoUrl.Get()
	toSerialize["timezone"] = o.Timezone
	toSerialize["member_count"] = o.MemberCount
	if !IsNil(o.SubscriptionTier) {
		toSerialize["subscription_tier"] = o.SubscriptionTier
	}
	if !IsNil(o.SubscriptionStatus) {
		toSerialize["subscription_status"] = o.SubscriptionStatus
	}
	if !IsNil(o.UsageThisMonth) {
		toSerialize["usage_this_month"] = o.UsageThisMonth
	}
	if o.LastActivity.IsSet() {
		toSerialize["last_activity"] = o.LastActivity.Get()
	}
	toSerialize["created_at"] = o.CreatedAt.Get()
	toSerialize["updated_at"] = o.UpdatedAt.Get()
	return toSerialize, nil
}

func (o *EnhancedWorkspaceListItem) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"name",
		"slug",
		"billing_email",
		"website",
		"logo_url",
		"timezone",
		"member_count",
		"created_at",
		"updated_at",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varEnhancedWorkspaceListItem := _EnhancedWorkspaceListItem{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varEnhancedWorkspaceListItem)

	if err != nil {
		return err
	}

	*o = EnhancedWorkspaceListItem(varEnhancedWorkspaceListItem)

	return err
}

type NullableEnhancedWorkspaceListItem struct {
	value *EnhancedWorkspaceListItem
	isSet bool
}

func (v NullableEnhancedWorkspaceListItem) Get() *EnhancedWorkspaceListItem {
	return v.value
}

func (v *NullableEnhancedWorkspaceListItem) Set(val *EnhancedWorkspaceListItem) {
	v.value = val
	v.isSet = true
}

func (v NullableEnhancedWorkspaceListItem) IsSet() bool {
	return v.isSet
}

func (v *NullableEnhancedWorkspaceListItem) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEnhancedWorkspaceListItem(val *EnhancedWorkspaceListItem) *NullableEnhancedWorkspaceListItem {
	return &NullableEnhancedWorkspaceListItem{value: val, isSet: true}
}

func (v NullableEnhancedWorkspaceListItem) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEnhancedWorkspaceListItem) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


