/*
SpatialFlow API

Real-time geospatial automation platform API.  ## Authentication  **API Key:** Include `X-API-Key` header **JWT Token:** Include `Authorization: Bearer <token>` header  ## Rate Limits  - Authenticated: 1,000 requests per hour (per API key, JWT, or session) - Anonymous: 100 requests per hour  ## Webhook Verification  Outbound webhooks include HMAC-SHA256 signatures in `X-SF-Signature` header.  ## Support  - Documentation: https://docs.spatialflow.io - GitHub: https://github.com/spatialflow/spatialflow - Email: support@spatialflow.io     

API version: v1.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package generated

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the RouteTestProgress type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RouteTestProgress{}

// RouteTestProgress Progress for async tests.
type RouteTestProgress struct {
	PointsProcessed int32 `json:"points_processed"`
	TotalPoints int32 `json:"total_points"`
	Percent float32 `json:"percent"`
}

type _RouteTestProgress RouteTestProgress

// NewRouteTestProgress instantiates a new RouteTestProgress object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRouteTestProgress(pointsProcessed int32, totalPoints int32, percent float32) *RouteTestProgress {
	this := RouteTestProgress{}
	this.PointsProcessed = pointsProcessed
	this.TotalPoints = totalPoints
	this.Percent = percent
	return &this
}

// NewRouteTestProgressWithDefaults instantiates a new RouteTestProgress object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRouteTestProgressWithDefaults() *RouteTestProgress {
	this := RouteTestProgress{}
	return &this
}

// GetPointsProcessed returns the PointsProcessed field value
func (o *RouteTestProgress) GetPointsProcessed() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.PointsProcessed
}

// GetPointsProcessedOk returns a tuple with the PointsProcessed field value
// and a boolean to check if the value has been set.
func (o *RouteTestProgress) GetPointsProcessedOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PointsProcessed, true
}

// SetPointsProcessed sets field value
func (o *RouteTestProgress) SetPointsProcessed(v int32) {
	o.PointsProcessed = v
}

// GetTotalPoints returns the TotalPoints field value
func (o *RouteTestProgress) GetTotalPoints() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.TotalPoints
}

// GetTotalPointsOk returns a tuple with the TotalPoints field value
// and a boolean to check if the value has been set.
func (o *RouteTestProgress) GetTotalPointsOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TotalPoints, true
}

// SetTotalPoints sets field value
func (o *RouteTestProgress) SetTotalPoints(v int32) {
	o.TotalPoints = v
}

// GetPercent returns the Percent field value
func (o *RouteTestProgress) GetPercent() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.Percent
}

// GetPercentOk returns a tuple with the Percent field value
// and a boolean to check if the value has been set.
func (o *RouteTestProgress) GetPercentOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Percent, true
}

// SetPercent sets field value
func (o *RouteTestProgress) SetPercent(v float32) {
	o.Percent = v
}

func (o RouteTestProgress) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RouteTestProgress) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["points_processed"] = o.PointsProcessed
	toSerialize["total_points"] = o.TotalPoints
	toSerialize["percent"] = o.Percent
	return toSerialize, nil
}

func (o *RouteTestProgress) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"points_processed",
		"total_points",
		"percent",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRouteTestProgress := _RouteTestProgress{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varRouteTestProgress)

	if err != nil {
		return err
	}

	*o = RouteTestProgress(varRouteTestProgress)

	return err
}

type NullableRouteTestProgress struct {
	value *RouteTestProgress
	isSet bool
}

func (v NullableRouteTestProgress) Get() *RouteTestProgress {
	return v.value
}

func (v *NullableRouteTestProgress) Set(val *RouteTestProgress) {
	v.value = val
	v.isSet = true
}

func (v NullableRouteTestProgress) IsSet() bool {
	return v.isSet
}

func (v *NullableRouteTestProgress) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRouteTestProgress(val *RouteTestProgress) *NullableRouteTestProgress {
	return &NullableRouteTestProgress{value: val, isSet: true}
}

func (v NullableRouteTestProgress) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRouteTestProgress) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


