/*
SpatialFlow API

Real-time geospatial automation platform API.  ## Authentication  **API Key:** Include `X-API-Key` header **JWT Token:** Include `Authorization: Bearer <token>` header  ## Rate Limits  - Authenticated: 1,000 requests per hour (per API key, JWT, or session) - Anonymous: 100 requests per hour  ## Webhook Verification  Outbound webhooks include HMAC-SHA256 signatures in `X-SF-Signature` header.  ## Support  - Documentation: https://docs.spatialflow.io/ - Email: support@spatialflow.io     

API version: v1.36.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package generated

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the LocationUpdateOut type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &LocationUpdateOut{}

// LocationUpdateOut struct for LocationUpdateOut
type LocationUpdateOut struct {
	Success bool `json:"success"`
	DeviceId string `json:"device_id"`
	EventsTriggered int32 `json:"events_triggered"`
	Message string `json:"message"`
	ErrorCode NullableString `json:"error_code,omitempty"`
	LocationResults []BatchLocationResultOut `json:"location_results,omitempty"`
}

type _LocationUpdateOut LocationUpdateOut

// NewLocationUpdateOut instantiates a new LocationUpdateOut object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewLocationUpdateOut(success bool, deviceId string, eventsTriggered int32, message string) *LocationUpdateOut {
	this := LocationUpdateOut{}
	this.Success = success
	this.DeviceId = deviceId
	this.EventsTriggered = eventsTriggered
	this.Message = message
	return &this
}

// NewLocationUpdateOutWithDefaults instantiates a new LocationUpdateOut object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewLocationUpdateOutWithDefaults() *LocationUpdateOut {
	this := LocationUpdateOut{}
	return &this
}

// GetSuccess returns the Success field value
func (o *LocationUpdateOut) GetSuccess() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Success
}

// GetSuccessOk returns a tuple with the Success field value
// and a boolean to check if the value has been set.
func (o *LocationUpdateOut) GetSuccessOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Success, true
}

// SetSuccess sets field value
func (o *LocationUpdateOut) SetSuccess(v bool) {
	o.Success = v
}

// GetDeviceId returns the DeviceId field value
func (o *LocationUpdateOut) GetDeviceId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DeviceId
}

// GetDeviceIdOk returns a tuple with the DeviceId field value
// and a boolean to check if the value has been set.
func (o *LocationUpdateOut) GetDeviceIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DeviceId, true
}

// SetDeviceId sets field value
func (o *LocationUpdateOut) SetDeviceId(v string) {
	o.DeviceId = v
}

// GetEventsTriggered returns the EventsTriggered field value
func (o *LocationUpdateOut) GetEventsTriggered() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.EventsTriggered
}

// GetEventsTriggeredOk returns a tuple with the EventsTriggered field value
// and a boolean to check if the value has been set.
func (o *LocationUpdateOut) GetEventsTriggeredOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.EventsTriggered, true
}

// SetEventsTriggered sets field value
func (o *LocationUpdateOut) SetEventsTriggered(v int32) {
	o.EventsTriggered = v
}

// GetMessage returns the Message field value
func (o *LocationUpdateOut) GetMessage() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Message
}

// GetMessageOk returns a tuple with the Message field value
// and a boolean to check if the value has been set.
func (o *LocationUpdateOut) GetMessageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Message, true
}

// SetMessage sets field value
func (o *LocationUpdateOut) SetMessage(v string) {
	o.Message = v
}

// GetErrorCode returns the ErrorCode field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *LocationUpdateOut) GetErrorCode() string {
	if o == nil || IsNil(o.ErrorCode.Get()) {
		var ret string
		return ret
	}
	return *o.ErrorCode.Get()
}

// GetErrorCodeOk returns a tuple with the ErrorCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *LocationUpdateOut) GetErrorCodeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ErrorCode.Get(), o.ErrorCode.IsSet()
}

// HasErrorCode returns a boolean if a field has been set.
func (o *LocationUpdateOut) HasErrorCode() bool {
	if o != nil && o.ErrorCode.IsSet() {
		return true
	}

	return false
}

// SetErrorCode gets a reference to the given NullableString and assigns it to the ErrorCode field.
func (o *LocationUpdateOut) SetErrorCode(v string) {
	o.ErrorCode.Set(&v)
}
// SetErrorCodeNil sets the value for ErrorCode to be an explicit nil
func (o *LocationUpdateOut) SetErrorCodeNil() {
	o.ErrorCode.Set(nil)
}

// UnsetErrorCode ensures that no value is present for ErrorCode, not even an explicit nil
func (o *LocationUpdateOut) UnsetErrorCode() {
	o.ErrorCode.Unset()
}

// GetLocationResults returns the LocationResults field value if set, zero value otherwise.
func (o *LocationUpdateOut) GetLocationResults() []BatchLocationResultOut {
	if o == nil || IsNil(o.LocationResults) {
		var ret []BatchLocationResultOut
		return ret
	}
	return o.LocationResults
}

// GetLocationResultsOk returns a tuple with the LocationResults field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LocationUpdateOut) GetLocationResultsOk() ([]BatchLocationResultOut, bool) {
	if o == nil || IsNil(o.LocationResults) {
		return nil, false
	}
	return o.LocationResults, true
}

// HasLocationResults returns a boolean if a field has been set.
func (o *LocationUpdateOut) HasLocationResults() bool {
	if o != nil && !IsNil(o.LocationResults) {
		return true
	}

	return false
}

// SetLocationResults gets a reference to the given []BatchLocationResultOut and assigns it to the LocationResults field.
func (o *LocationUpdateOut) SetLocationResults(v []BatchLocationResultOut) {
	o.LocationResults = v
}

func (o LocationUpdateOut) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o LocationUpdateOut) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["success"] = o.Success
	toSerialize["device_id"] = o.DeviceId
	toSerialize["events_triggered"] = o.EventsTriggered
	toSerialize["message"] = o.Message
	if o.ErrorCode.IsSet() {
		toSerialize["error_code"] = o.ErrorCode.Get()
	}
	if !IsNil(o.LocationResults) {
		toSerialize["location_results"] = o.LocationResults
	}
	return toSerialize, nil
}

func (o *LocationUpdateOut) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"success",
		"device_id",
		"events_triggered",
		"message",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varLocationUpdateOut := _LocationUpdateOut{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varLocationUpdateOut)

	if err != nil {
		return err
	}

	*o = LocationUpdateOut(varLocationUpdateOut)

	return err
}

type NullableLocationUpdateOut struct {
	value *LocationUpdateOut
	isSet bool
}

func (v NullableLocationUpdateOut) Get() *LocationUpdateOut {
	return v.value
}

func (v *NullableLocationUpdateOut) Set(val *LocationUpdateOut) {
	v.value = val
	v.isSet = true
}

func (v NullableLocationUpdateOut) IsSet() bool {
	return v.isSet
}

func (v *NullableLocationUpdateOut) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLocationUpdateOut(val *LocationUpdateOut) *NullableLocationUpdateOut {
	return &NullableLocationUpdateOut{value: val, isSet: true}
}

func (v NullableLocationUpdateOut) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLocationUpdateOut) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


