/*
SpatialFlow API

Real-time geospatial automation platform API.  ## Authentication  **API Key:** Include `X-API-Key` header **JWT Token:** Include `Authorization: Bearer <token>` header  ## Rate Limits  - Authenticated: 1,000 requests per hour (per API key, JWT, or session) - Anonymous: 100 requests per hour  ## Webhook Verification  Outbound webhooks include HMAC-SHA256 signatures in `X-SF-Signature` header.  ## Support  - Documentation: https://docs.spatialflow.io - GitHub: https://github.com/spatialflow/spatialflow - Email: support@spatialflow.io     

API version: v1.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package generated

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the MobileWorkspaceSelectionOut type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MobileWorkspaceSelectionOut{}

// MobileWorkspaceSelectionOut struct for MobileWorkspaceSelectionOut
type MobileWorkspaceSelectionOut struct {
	EligibleWorkspaces []MobileWorkspaceRow `json:"eligible_workspaces"`
	EligibleCount int32 `json:"eligible_count"`
	SelectedWorkspaceId NullableString `json:"selected_workspace_id,omitempty"`
	SelectedWorkspace NullableMobileWorkspaceRow `json:"selected_workspace,omitempty"`
	SkipPicker bool `json:"skip_picker"`
	SelectionRequired bool `json:"selection_required"`
	AccessToken string `json:"access_token"`
	RefreshToken string `json:"refresh_token"`
	TokenType string `json:"token_type"`
	ExpiresIn int32 `json:"expires_in"`
	User map[string]interface{} `json:"user"`
}

type _MobileWorkspaceSelectionOut MobileWorkspaceSelectionOut

// NewMobileWorkspaceSelectionOut instantiates a new MobileWorkspaceSelectionOut object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMobileWorkspaceSelectionOut(eligibleWorkspaces []MobileWorkspaceRow, eligibleCount int32, skipPicker bool, selectionRequired bool, accessToken string, refreshToken string, tokenType string, expiresIn int32, user map[string]interface{}) *MobileWorkspaceSelectionOut {
	this := MobileWorkspaceSelectionOut{}
	this.EligibleWorkspaces = eligibleWorkspaces
	this.EligibleCount = eligibleCount
	this.SkipPicker = skipPicker
	this.SelectionRequired = selectionRequired
	this.AccessToken = accessToken
	this.RefreshToken = refreshToken
	this.TokenType = tokenType
	this.ExpiresIn = expiresIn
	this.User = user
	return &this
}

// NewMobileWorkspaceSelectionOutWithDefaults instantiates a new MobileWorkspaceSelectionOut object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMobileWorkspaceSelectionOutWithDefaults() *MobileWorkspaceSelectionOut {
	this := MobileWorkspaceSelectionOut{}
	return &this
}

// GetEligibleWorkspaces returns the EligibleWorkspaces field value
func (o *MobileWorkspaceSelectionOut) GetEligibleWorkspaces() []MobileWorkspaceRow {
	if o == nil {
		var ret []MobileWorkspaceRow
		return ret
	}

	return o.EligibleWorkspaces
}

// GetEligibleWorkspacesOk returns a tuple with the EligibleWorkspaces field value
// and a boolean to check if the value has been set.
func (o *MobileWorkspaceSelectionOut) GetEligibleWorkspacesOk() ([]MobileWorkspaceRow, bool) {
	if o == nil {
		return nil, false
	}
	return o.EligibleWorkspaces, true
}

// SetEligibleWorkspaces sets field value
func (o *MobileWorkspaceSelectionOut) SetEligibleWorkspaces(v []MobileWorkspaceRow) {
	o.EligibleWorkspaces = v
}

// GetEligibleCount returns the EligibleCount field value
func (o *MobileWorkspaceSelectionOut) GetEligibleCount() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.EligibleCount
}

// GetEligibleCountOk returns a tuple with the EligibleCount field value
// and a boolean to check if the value has been set.
func (o *MobileWorkspaceSelectionOut) GetEligibleCountOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.EligibleCount, true
}

// SetEligibleCount sets field value
func (o *MobileWorkspaceSelectionOut) SetEligibleCount(v int32) {
	o.EligibleCount = v
}

// GetSelectedWorkspaceId returns the SelectedWorkspaceId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *MobileWorkspaceSelectionOut) GetSelectedWorkspaceId() string {
	if o == nil || IsNil(o.SelectedWorkspaceId.Get()) {
		var ret string
		return ret
	}
	return *o.SelectedWorkspaceId.Get()
}

// GetSelectedWorkspaceIdOk returns a tuple with the SelectedWorkspaceId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *MobileWorkspaceSelectionOut) GetSelectedWorkspaceIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.SelectedWorkspaceId.Get(), o.SelectedWorkspaceId.IsSet()
}

// HasSelectedWorkspaceId returns a boolean if a field has been set.
func (o *MobileWorkspaceSelectionOut) HasSelectedWorkspaceId() bool {
	if o != nil && o.SelectedWorkspaceId.IsSet() {
		return true
	}

	return false
}

// SetSelectedWorkspaceId gets a reference to the given NullableString and assigns it to the SelectedWorkspaceId field.
func (o *MobileWorkspaceSelectionOut) SetSelectedWorkspaceId(v string) {
	o.SelectedWorkspaceId.Set(&v)
}
// SetSelectedWorkspaceIdNil sets the value for SelectedWorkspaceId to be an explicit nil
func (o *MobileWorkspaceSelectionOut) SetSelectedWorkspaceIdNil() {
	o.SelectedWorkspaceId.Set(nil)
}

// UnsetSelectedWorkspaceId ensures that no value is present for SelectedWorkspaceId, not even an explicit nil
func (o *MobileWorkspaceSelectionOut) UnsetSelectedWorkspaceId() {
	o.SelectedWorkspaceId.Unset()
}

// GetSelectedWorkspace returns the SelectedWorkspace field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *MobileWorkspaceSelectionOut) GetSelectedWorkspace() MobileWorkspaceRow {
	if o == nil || IsNil(o.SelectedWorkspace.Get()) {
		var ret MobileWorkspaceRow
		return ret
	}
	return *o.SelectedWorkspace.Get()
}

// GetSelectedWorkspaceOk returns a tuple with the SelectedWorkspace field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *MobileWorkspaceSelectionOut) GetSelectedWorkspaceOk() (*MobileWorkspaceRow, bool) {
	if o == nil {
		return nil, false
	}
	return o.SelectedWorkspace.Get(), o.SelectedWorkspace.IsSet()
}

// HasSelectedWorkspace returns a boolean if a field has been set.
func (o *MobileWorkspaceSelectionOut) HasSelectedWorkspace() bool {
	if o != nil && o.SelectedWorkspace.IsSet() {
		return true
	}

	return false
}

// SetSelectedWorkspace gets a reference to the given NullableMobileWorkspaceRow and assigns it to the SelectedWorkspace field.
func (o *MobileWorkspaceSelectionOut) SetSelectedWorkspace(v MobileWorkspaceRow) {
	o.SelectedWorkspace.Set(&v)
}
// SetSelectedWorkspaceNil sets the value for SelectedWorkspace to be an explicit nil
func (o *MobileWorkspaceSelectionOut) SetSelectedWorkspaceNil() {
	o.SelectedWorkspace.Set(nil)
}

// UnsetSelectedWorkspace ensures that no value is present for SelectedWorkspace, not even an explicit nil
func (o *MobileWorkspaceSelectionOut) UnsetSelectedWorkspace() {
	o.SelectedWorkspace.Unset()
}

// GetSkipPicker returns the SkipPicker field value
func (o *MobileWorkspaceSelectionOut) GetSkipPicker() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.SkipPicker
}

// GetSkipPickerOk returns a tuple with the SkipPicker field value
// and a boolean to check if the value has been set.
func (o *MobileWorkspaceSelectionOut) GetSkipPickerOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SkipPicker, true
}

// SetSkipPicker sets field value
func (o *MobileWorkspaceSelectionOut) SetSkipPicker(v bool) {
	o.SkipPicker = v
}

// GetSelectionRequired returns the SelectionRequired field value
func (o *MobileWorkspaceSelectionOut) GetSelectionRequired() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.SelectionRequired
}

// GetSelectionRequiredOk returns a tuple with the SelectionRequired field value
// and a boolean to check if the value has been set.
func (o *MobileWorkspaceSelectionOut) GetSelectionRequiredOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SelectionRequired, true
}

// SetSelectionRequired sets field value
func (o *MobileWorkspaceSelectionOut) SetSelectionRequired(v bool) {
	o.SelectionRequired = v
}

// GetAccessToken returns the AccessToken field value
func (o *MobileWorkspaceSelectionOut) GetAccessToken() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AccessToken
}

// GetAccessTokenOk returns a tuple with the AccessToken field value
// and a boolean to check if the value has been set.
func (o *MobileWorkspaceSelectionOut) GetAccessTokenOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AccessToken, true
}

// SetAccessToken sets field value
func (o *MobileWorkspaceSelectionOut) SetAccessToken(v string) {
	o.AccessToken = v
}

// GetRefreshToken returns the RefreshToken field value
func (o *MobileWorkspaceSelectionOut) GetRefreshToken() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.RefreshToken
}

// GetRefreshTokenOk returns a tuple with the RefreshToken field value
// and a boolean to check if the value has been set.
func (o *MobileWorkspaceSelectionOut) GetRefreshTokenOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RefreshToken, true
}

// SetRefreshToken sets field value
func (o *MobileWorkspaceSelectionOut) SetRefreshToken(v string) {
	o.RefreshToken = v
}

// GetTokenType returns the TokenType field value
func (o *MobileWorkspaceSelectionOut) GetTokenType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TokenType
}

// GetTokenTypeOk returns a tuple with the TokenType field value
// and a boolean to check if the value has been set.
func (o *MobileWorkspaceSelectionOut) GetTokenTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TokenType, true
}

// SetTokenType sets field value
func (o *MobileWorkspaceSelectionOut) SetTokenType(v string) {
	o.TokenType = v
}

// GetExpiresIn returns the ExpiresIn field value
func (o *MobileWorkspaceSelectionOut) GetExpiresIn() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.ExpiresIn
}

// GetExpiresInOk returns a tuple with the ExpiresIn field value
// and a boolean to check if the value has been set.
func (o *MobileWorkspaceSelectionOut) GetExpiresInOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ExpiresIn, true
}

// SetExpiresIn sets field value
func (o *MobileWorkspaceSelectionOut) SetExpiresIn(v int32) {
	o.ExpiresIn = v
}

// GetUser returns the User field value
func (o *MobileWorkspaceSelectionOut) GetUser() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}

	return o.User
}

// GetUserOk returns a tuple with the User field value
// and a boolean to check if the value has been set.
func (o *MobileWorkspaceSelectionOut) GetUserOk() (map[string]interface{}, bool) {
	if o == nil {
		return map[string]interface{}{}, false
	}
	return o.User, true
}

// SetUser sets field value
func (o *MobileWorkspaceSelectionOut) SetUser(v map[string]interface{}) {
	o.User = v
}

func (o MobileWorkspaceSelectionOut) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MobileWorkspaceSelectionOut) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["eligible_workspaces"] = o.EligibleWorkspaces
	toSerialize["eligible_count"] = o.EligibleCount
	if o.SelectedWorkspaceId.IsSet() {
		toSerialize["selected_workspace_id"] = o.SelectedWorkspaceId.Get()
	}
	if o.SelectedWorkspace.IsSet() {
		toSerialize["selected_workspace"] = o.SelectedWorkspace.Get()
	}
	toSerialize["skip_picker"] = o.SkipPicker
	toSerialize["selection_required"] = o.SelectionRequired
	toSerialize["access_token"] = o.AccessToken
	toSerialize["refresh_token"] = o.RefreshToken
	toSerialize["token_type"] = o.TokenType
	toSerialize["expires_in"] = o.ExpiresIn
	toSerialize["user"] = o.User
	return toSerialize, nil
}

func (o *MobileWorkspaceSelectionOut) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"eligible_workspaces",
		"eligible_count",
		"skip_picker",
		"selection_required",
		"access_token",
		"refresh_token",
		"token_type",
		"expires_in",
		"user",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varMobileWorkspaceSelectionOut := _MobileWorkspaceSelectionOut{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varMobileWorkspaceSelectionOut)

	if err != nil {
		return err
	}

	*o = MobileWorkspaceSelectionOut(varMobileWorkspaceSelectionOut)

	return err
}

type NullableMobileWorkspaceSelectionOut struct {
	value *MobileWorkspaceSelectionOut
	isSet bool
}

func (v NullableMobileWorkspaceSelectionOut) Get() *MobileWorkspaceSelectionOut {
	return v.value
}

func (v *NullableMobileWorkspaceSelectionOut) Set(val *MobileWorkspaceSelectionOut) {
	v.value = val
	v.isSet = true
}

func (v NullableMobileWorkspaceSelectionOut) IsSet() bool {
	return v.isSet
}

func (v *NullableMobileWorkspaceSelectionOut) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMobileWorkspaceSelectionOut(val *MobileWorkspaceSelectionOut) *NullableMobileWorkspaceSelectionOut {
	return &NullableMobileWorkspaceSelectionOut{value: val, isSet: true}
}

func (v NullableMobileWorkspaceSelectionOut) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMobileWorkspaceSelectionOut) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


