/*
SpatialFlow API

Real-time geospatial automation platform API.  ## Authentication  **API Key:** Include `X-API-Key` header **JWT Token:** Include `Authorization: Bearer <token>` header  ## Rate Limits  - Authenticated: 1,000 requests per hour (per API key, JWT, or session) - Anonymous: 100 requests per hour  ## Webhook Verification  Outbound webhooks include HMAC-SHA256 signatures in `X-SF-Signature` header.  ## Support  - Documentation: https://docs.spatialflow.io - GitHub: https://github.com/spatialflow/spatialflow - Email: support@spatialflow.io     

API version: v1.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package generated

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the IntegrationDetailSchema type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &IntegrationDetailSchema{}

// IntegrationDetailSchema Detailed integration response with masked config
type IntegrationDetailSchema struct {
	Id string `json:"id"`
	Name string `json:"name"`
	Type string `json:"type"`
	Description string `json:"description"`
	IsActive bool `json:"is_active"`
	IsVerified bool `json:"is_verified"`
	HealthStatus string `json:"health_status"`
	HealthMessage string `json:"health_message"`
	UsageCount int32 `json:"usage_count"`
	LastUsedAt NullableString `json:"last_used_at,omitempty"`
	LastVerifiedAt NullableString `json:"last_verified_at,omitempty"`
	Tags []string `json:"tags"`
	CreatedAt string `json:"created_at"`
	UpdatedAt string `json:"updated_at"`
	Config map[string]interface{} `json:"config"`
}

type _IntegrationDetailSchema IntegrationDetailSchema

// NewIntegrationDetailSchema instantiates a new IntegrationDetailSchema object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewIntegrationDetailSchema(id string, name string, type_ string, description string, isActive bool, isVerified bool, healthStatus string, healthMessage string, usageCount int32, tags []string, createdAt string, updatedAt string, config map[string]interface{}) *IntegrationDetailSchema {
	this := IntegrationDetailSchema{}
	this.Id = id
	this.Name = name
	this.Type = type_
	this.Description = description
	this.IsActive = isActive
	this.IsVerified = isVerified
	this.HealthStatus = healthStatus
	this.HealthMessage = healthMessage
	this.UsageCount = usageCount
	this.Tags = tags
	this.CreatedAt = createdAt
	this.UpdatedAt = updatedAt
	this.Config = config
	return &this
}

// NewIntegrationDetailSchemaWithDefaults instantiates a new IntegrationDetailSchema object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewIntegrationDetailSchemaWithDefaults() *IntegrationDetailSchema {
	this := IntegrationDetailSchema{}
	return &this
}

// GetId returns the Id field value
func (o *IntegrationDetailSchema) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *IntegrationDetailSchema) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *IntegrationDetailSchema) SetId(v string) {
	o.Id = v
}

// GetName returns the Name field value
func (o *IntegrationDetailSchema) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *IntegrationDetailSchema) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *IntegrationDetailSchema) SetName(v string) {
	o.Name = v
}

// GetType returns the Type field value
func (o *IntegrationDetailSchema) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *IntegrationDetailSchema) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *IntegrationDetailSchema) SetType(v string) {
	o.Type = v
}

// GetDescription returns the Description field value
func (o *IntegrationDetailSchema) GetDescription() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Description
}

// GetDescriptionOk returns a tuple with the Description field value
// and a boolean to check if the value has been set.
func (o *IntegrationDetailSchema) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Description, true
}

// SetDescription sets field value
func (o *IntegrationDetailSchema) SetDescription(v string) {
	o.Description = v
}

// GetIsActive returns the IsActive field value
func (o *IntegrationDetailSchema) GetIsActive() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.IsActive
}

// GetIsActiveOk returns a tuple with the IsActive field value
// and a boolean to check if the value has been set.
func (o *IntegrationDetailSchema) GetIsActiveOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IsActive, true
}

// SetIsActive sets field value
func (o *IntegrationDetailSchema) SetIsActive(v bool) {
	o.IsActive = v
}

// GetIsVerified returns the IsVerified field value
func (o *IntegrationDetailSchema) GetIsVerified() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.IsVerified
}

// GetIsVerifiedOk returns a tuple with the IsVerified field value
// and a boolean to check if the value has been set.
func (o *IntegrationDetailSchema) GetIsVerifiedOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IsVerified, true
}

// SetIsVerified sets field value
func (o *IntegrationDetailSchema) SetIsVerified(v bool) {
	o.IsVerified = v
}

// GetHealthStatus returns the HealthStatus field value
func (o *IntegrationDetailSchema) GetHealthStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.HealthStatus
}

// GetHealthStatusOk returns a tuple with the HealthStatus field value
// and a boolean to check if the value has been set.
func (o *IntegrationDetailSchema) GetHealthStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.HealthStatus, true
}

// SetHealthStatus sets field value
func (o *IntegrationDetailSchema) SetHealthStatus(v string) {
	o.HealthStatus = v
}

// GetHealthMessage returns the HealthMessage field value
func (o *IntegrationDetailSchema) GetHealthMessage() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.HealthMessage
}

// GetHealthMessageOk returns a tuple with the HealthMessage field value
// and a boolean to check if the value has been set.
func (o *IntegrationDetailSchema) GetHealthMessageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.HealthMessage, true
}

// SetHealthMessage sets field value
func (o *IntegrationDetailSchema) SetHealthMessage(v string) {
	o.HealthMessage = v
}

// GetUsageCount returns the UsageCount field value
func (o *IntegrationDetailSchema) GetUsageCount() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.UsageCount
}

// GetUsageCountOk returns a tuple with the UsageCount field value
// and a boolean to check if the value has been set.
func (o *IntegrationDetailSchema) GetUsageCountOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UsageCount, true
}

// SetUsageCount sets field value
func (o *IntegrationDetailSchema) SetUsageCount(v int32) {
	o.UsageCount = v
}

// GetLastUsedAt returns the LastUsedAt field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *IntegrationDetailSchema) GetLastUsedAt() string {
	if o == nil || IsNil(o.LastUsedAt.Get()) {
		var ret string
		return ret
	}
	return *o.LastUsedAt.Get()
}

// GetLastUsedAtOk returns a tuple with the LastUsedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *IntegrationDetailSchema) GetLastUsedAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.LastUsedAt.Get(), o.LastUsedAt.IsSet()
}

// HasLastUsedAt returns a boolean if a field has been set.
func (o *IntegrationDetailSchema) HasLastUsedAt() bool {
	if o != nil && o.LastUsedAt.IsSet() {
		return true
	}

	return false
}

// SetLastUsedAt gets a reference to the given NullableString and assigns it to the LastUsedAt field.
func (o *IntegrationDetailSchema) SetLastUsedAt(v string) {
	o.LastUsedAt.Set(&v)
}
// SetLastUsedAtNil sets the value for LastUsedAt to be an explicit nil
func (o *IntegrationDetailSchema) SetLastUsedAtNil() {
	o.LastUsedAt.Set(nil)
}

// UnsetLastUsedAt ensures that no value is present for LastUsedAt, not even an explicit nil
func (o *IntegrationDetailSchema) UnsetLastUsedAt() {
	o.LastUsedAt.Unset()
}

// GetLastVerifiedAt returns the LastVerifiedAt field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *IntegrationDetailSchema) GetLastVerifiedAt() string {
	if o == nil || IsNil(o.LastVerifiedAt.Get()) {
		var ret string
		return ret
	}
	return *o.LastVerifiedAt.Get()
}

// GetLastVerifiedAtOk returns a tuple with the LastVerifiedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *IntegrationDetailSchema) GetLastVerifiedAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.LastVerifiedAt.Get(), o.LastVerifiedAt.IsSet()
}

// HasLastVerifiedAt returns a boolean if a field has been set.
func (o *IntegrationDetailSchema) HasLastVerifiedAt() bool {
	if o != nil && o.LastVerifiedAt.IsSet() {
		return true
	}

	return false
}

// SetLastVerifiedAt gets a reference to the given NullableString and assigns it to the LastVerifiedAt field.
func (o *IntegrationDetailSchema) SetLastVerifiedAt(v string) {
	o.LastVerifiedAt.Set(&v)
}
// SetLastVerifiedAtNil sets the value for LastVerifiedAt to be an explicit nil
func (o *IntegrationDetailSchema) SetLastVerifiedAtNil() {
	o.LastVerifiedAt.Set(nil)
}

// UnsetLastVerifiedAt ensures that no value is present for LastVerifiedAt, not even an explicit nil
func (o *IntegrationDetailSchema) UnsetLastVerifiedAt() {
	o.LastVerifiedAt.Unset()
}

// GetTags returns the Tags field value
func (o *IntegrationDetailSchema) GetTags() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.Tags
}

// GetTagsOk returns a tuple with the Tags field value
// and a boolean to check if the value has been set.
func (o *IntegrationDetailSchema) GetTagsOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Tags, true
}

// SetTags sets field value
func (o *IntegrationDetailSchema) SetTags(v []string) {
	o.Tags = v
}

// GetCreatedAt returns the CreatedAt field value
func (o *IntegrationDetailSchema) GetCreatedAt() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *IntegrationDetailSchema) GetCreatedAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *IntegrationDetailSchema) SetCreatedAt(v string) {
	o.CreatedAt = v
}

// GetUpdatedAt returns the UpdatedAt field value
func (o *IntegrationDetailSchema) GetUpdatedAt() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value
// and a boolean to check if the value has been set.
func (o *IntegrationDetailSchema) GetUpdatedAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UpdatedAt, true
}

// SetUpdatedAt sets field value
func (o *IntegrationDetailSchema) SetUpdatedAt(v string) {
	o.UpdatedAt = v
}

// GetConfig returns the Config field value
func (o *IntegrationDetailSchema) GetConfig() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}

	return o.Config
}

// GetConfigOk returns a tuple with the Config field value
// and a boolean to check if the value has been set.
func (o *IntegrationDetailSchema) GetConfigOk() (map[string]interface{}, bool) {
	if o == nil {
		return map[string]interface{}{}, false
	}
	return o.Config, true
}

// SetConfig sets field value
func (o *IntegrationDetailSchema) SetConfig(v map[string]interface{}) {
	o.Config = v
}

func (o IntegrationDetailSchema) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o IntegrationDetailSchema) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["name"] = o.Name
	toSerialize["type"] = o.Type
	toSerialize["description"] = o.Description
	toSerialize["is_active"] = o.IsActive
	toSerialize["is_verified"] = o.IsVerified
	toSerialize["health_status"] = o.HealthStatus
	toSerialize["health_message"] = o.HealthMessage
	toSerialize["usage_count"] = o.UsageCount
	if o.LastUsedAt.IsSet() {
		toSerialize["last_used_at"] = o.LastUsedAt.Get()
	}
	if o.LastVerifiedAt.IsSet() {
		toSerialize["last_verified_at"] = o.LastVerifiedAt.Get()
	}
	toSerialize["tags"] = o.Tags
	toSerialize["created_at"] = o.CreatedAt
	toSerialize["updated_at"] = o.UpdatedAt
	toSerialize["config"] = o.Config
	return toSerialize, nil
}

func (o *IntegrationDetailSchema) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"name",
		"type",
		"description",
		"is_active",
		"is_verified",
		"health_status",
		"health_message",
		"usage_count",
		"tags",
		"created_at",
		"updated_at",
		"config",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varIntegrationDetailSchema := _IntegrationDetailSchema{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varIntegrationDetailSchema)

	if err != nil {
		return err
	}

	*o = IntegrationDetailSchema(varIntegrationDetailSchema)

	return err
}

type NullableIntegrationDetailSchema struct {
	value *IntegrationDetailSchema
	isSet bool
}

func (v NullableIntegrationDetailSchema) Get() *IntegrationDetailSchema {
	return v.value
}

func (v *NullableIntegrationDetailSchema) Set(val *IntegrationDetailSchema) {
	v.value = val
	v.isSet = true
}

func (v NullableIntegrationDetailSchema) IsSet() bool {
	return v.isSet
}

func (v *NullableIntegrationDetailSchema) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableIntegrationDetailSchema(val *IntegrationDetailSchema) *NullableIntegrationDetailSchema {
	return &NullableIntegrationDetailSchema{value: val, isSet: true}
}

func (v NullableIntegrationDetailSchema) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableIntegrationDetailSchema) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


