/*
SpatialFlow API

Real-time geospatial automation platform API.  ## Authentication  **API Key:** Include `X-API-Key` header **JWT Token:** Include `Authorization: Bearer <token>` header  ## Rate Limits  - Authenticated: 1,000 requests per hour (per API key, JWT, or session) - Anonymous: 100 requests per hour  ## Webhook Verification  Outbound webhooks include HMAC-SHA256 signatures in `X-SF-Signature` header.  ## Support  - Documentation: https://docs.spatialflow.io - GitHub: https://github.com/spatialflow/spatialflow - Email: support@spatialflow.io     

API version: v1.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package generated

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the ExecutionOut type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ExecutionOut{}

// ExecutionOut struct for ExecutionOut
type ExecutionOut struct {
	Id string `json:"id"`
	WorkflowId string `json:"workflow_id"`
	WorkflowName string `json:"workflow_name"`
	ExecutionId string `json:"execution_id"`
	TriggerSource string `json:"trigger_source"`
	Status string `json:"status"`
	StartedAt NullableTime `json:"started_at"`
	CompletedAt NullableTime `json:"completed_at"`
	DurationSeconds NullableFloat32 `json:"duration_seconds"`
	ErrorMessage NullableString `json:"error_message"`
}

type _ExecutionOut ExecutionOut

// NewExecutionOut instantiates a new ExecutionOut object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewExecutionOut(id string, workflowId string, workflowName string, executionId string, triggerSource string, status string, startedAt NullableTime, completedAt NullableTime, durationSeconds NullableFloat32, errorMessage NullableString) *ExecutionOut {
	this := ExecutionOut{}
	this.Id = id
	this.WorkflowId = workflowId
	this.WorkflowName = workflowName
	this.ExecutionId = executionId
	this.TriggerSource = triggerSource
	this.Status = status
	this.StartedAt = startedAt
	this.CompletedAt = completedAt
	this.DurationSeconds = durationSeconds
	this.ErrorMessage = errorMessage
	return &this
}

// NewExecutionOutWithDefaults instantiates a new ExecutionOut object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewExecutionOutWithDefaults() *ExecutionOut {
	this := ExecutionOut{}
	return &this
}

// GetId returns the Id field value
func (o *ExecutionOut) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *ExecutionOut) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *ExecutionOut) SetId(v string) {
	o.Id = v
}

// GetWorkflowId returns the WorkflowId field value
func (o *ExecutionOut) GetWorkflowId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.WorkflowId
}

// GetWorkflowIdOk returns a tuple with the WorkflowId field value
// and a boolean to check if the value has been set.
func (o *ExecutionOut) GetWorkflowIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.WorkflowId, true
}

// SetWorkflowId sets field value
func (o *ExecutionOut) SetWorkflowId(v string) {
	o.WorkflowId = v
}

// GetWorkflowName returns the WorkflowName field value
func (o *ExecutionOut) GetWorkflowName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.WorkflowName
}

// GetWorkflowNameOk returns a tuple with the WorkflowName field value
// and a boolean to check if the value has been set.
func (o *ExecutionOut) GetWorkflowNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.WorkflowName, true
}

// SetWorkflowName sets field value
func (o *ExecutionOut) SetWorkflowName(v string) {
	o.WorkflowName = v
}

// GetExecutionId returns the ExecutionId field value
func (o *ExecutionOut) GetExecutionId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ExecutionId
}

// GetExecutionIdOk returns a tuple with the ExecutionId field value
// and a boolean to check if the value has been set.
func (o *ExecutionOut) GetExecutionIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ExecutionId, true
}

// SetExecutionId sets field value
func (o *ExecutionOut) SetExecutionId(v string) {
	o.ExecutionId = v
}

// GetTriggerSource returns the TriggerSource field value
func (o *ExecutionOut) GetTriggerSource() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TriggerSource
}

// GetTriggerSourceOk returns a tuple with the TriggerSource field value
// and a boolean to check if the value has been set.
func (o *ExecutionOut) GetTriggerSourceOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TriggerSource, true
}

// SetTriggerSource sets field value
func (o *ExecutionOut) SetTriggerSource(v string) {
	o.TriggerSource = v
}

// GetStatus returns the Status field value
func (o *ExecutionOut) GetStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *ExecutionOut) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *ExecutionOut) SetStatus(v string) {
	o.Status = v
}

// GetStartedAt returns the StartedAt field value
// If the value is explicit nil, the zero value for time.Time will be returned
func (o *ExecutionOut) GetStartedAt() time.Time {
	if o == nil || o.StartedAt.Get() == nil {
		var ret time.Time
		return ret
	}

	return *o.StartedAt.Get()
}

// GetStartedAtOk returns a tuple with the StartedAt field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ExecutionOut) GetStartedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.StartedAt.Get(), o.StartedAt.IsSet()
}

// SetStartedAt sets field value
func (o *ExecutionOut) SetStartedAt(v time.Time) {
	o.StartedAt.Set(&v)
}

// GetCompletedAt returns the CompletedAt field value
// If the value is explicit nil, the zero value for time.Time will be returned
func (o *ExecutionOut) GetCompletedAt() time.Time {
	if o == nil || o.CompletedAt.Get() == nil {
		var ret time.Time
		return ret
	}

	return *o.CompletedAt.Get()
}

// GetCompletedAtOk returns a tuple with the CompletedAt field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ExecutionOut) GetCompletedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.CompletedAt.Get(), o.CompletedAt.IsSet()
}

// SetCompletedAt sets field value
func (o *ExecutionOut) SetCompletedAt(v time.Time) {
	o.CompletedAt.Set(&v)
}

// GetDurationSeconds returns the DurationSeconds field value
// If the value is explicit nil, the zero value for float32 will be returned
func (o *ExecutionOut) GetDurationSeconds() float32 {
	if o == nil || o.DurationSeconds.Get() == nil {
		var ret float32
		return ret
	}

	return *o.DurationSeconds.Get()
}

// GetDurationSecondsOk returns a tuple with the DurationSeconds field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ExecutionOut) GetDurationSecondsOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return o.DurationSeconds.Get(), o.DurationSeconds.IsSet()
}

// SetDurationSeconds sets field value
func (o *ExecutionOut) SetDurationSeconds(v float32) {
	o.DurationSeconds.Set(&v)
}

// GetErrorMessage returns the ErrorMessage field value
// If the value is explicit nil, the zero value for string will be returned
func (o *ExecutionOut) GetErrorMessage() string {
	if o == nil || o.ErrorMessage.Get() == nil {
		var ret string
		return ret
	}

	return *o.ErrorMessage.Get()
}

// GetErrorMessageOk returns a tuple with the ErrorMessage field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ExecutionOut) GetErrorMessageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ErrorMessage.Get(), o.ErrorMessage.IsSet()
}

// SetErrorMessage sets field value
func (o *ExecutionOut) SetErrorMessage(v string) {
	o.ErrorMessage.Set(&v)
}

func (o ExecutionOut) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ExecutionOut) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["workflow_id"] = o.WorkflowId
	toSerialize["workflow_name"] = o.WorkflowName
	toSerialize["execution_id"] = o.ExecutionId
	toSerialize["trigger_source"] = o.TriggerSource
	toSerialize["status"] = o.Status
	toSerialize["started_at"] = o.StartedAt.Get()
	toSerialize["completed_at"] = o.CompletedAt.Get()
	toSerialize["duration_seconds"] = o.DurationSeconds.Get()
	toSerialize["error_message"] = o.ErrorMessage.Get()
	return toSerialize, nil
}

func (o *ExecutionOut) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"workflow_id",
		"workflow_name",
		"execution_id",
		"trigger_source",
		"status",
		"started_at",
		"completed_at",
		"duration_seconds",
		"error_message",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varExecutionOut := _ExecutionOut{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varExecutionOut)

	if err != nil {
		return err
	}

	*o = ExecutionOut(varExecutionOut)

	return err
}

type NullableExecutionOut struct {
	value *ExecutionOut
	isSet bool
}

func (v NullableExecutionOut) Get() *ExecutionOut {
	return v.value
}

func (v *NullableExecutionOut) Set(val *ExecutionOut) {
	v.value = val
	v.isSet = true
}

func (v NullableExecutionOut) IsSet() bool {
	return v.isSet
}

func (v *NullableExecutionOut) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableExecutionOut(val *ExecutionOut) *NullableExecutionOut {
	return &NullableExecutionOut{value: val, isSet: true}
}

func (v NullableExecutionOut) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableExecutionOut) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


