/*
SpatialFlow API

Real-time geospatial automation platform API.  ## Authentication  **API Key:** Include `X-API-Key` header **JWT Token:** Include `Authorization: Bearer <token>` header  ## Rate Limits  - Authenticated: 1,000 requests per hour (per API key, JWT, or session) - Anonymous: 100 requests per hour  ## Webhook Verification  Outbound webhooks include HMAC-SHA256 signatures in `X-SF-Signature` header.  ## Support  - Documentation: https://docs.spatialflow.io - GitHub: https://github.com/spatialflow/spatialflow - Email: support@spatialflow.io     

API version: v1.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package generated

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the OAuthProvidersResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OAuthProvidersResponse{}

// OAuthProvidersResponse struct for OAuthProvidersResponse
type OAuthProvidersResponse struct {
	Providers []*map[string]interface{} `json:"providers"`
}

type _OAuthProvidersResponse OAuthProvidersResponse

// NewOAuthProvidersResponse instantiates a new OAuthProvidersResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOAuthProvidersResponse(providers []*map[string]interface{}) *OAuthProvidersResponse {
	this := OAuthProvidersResponse{}
	this.Providers = providers
	return &this
}

// NewOAuthProvidersResponseWithDefaults instantiates a new OAuthProvidersResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOAuthProvidersResponseWithDefaults() *OAuthProvidersResponse {
	this := OAuthProvidersResponse{}
	return &this
}

// GetProviders returns the Providers field value
func (o *OAuthProvidersResponse) GetProviders() []*map[string]interface{} {
	if o == nil {
		var ret []*map[string]interface{}
		return ret
	}

	return o.Providers
}

// GetProvidersOk returns a tuple with the Providers field value
// and a boolean to check if the value has been set.
func (o *OAuthProvidersResponse) GetProvidersOk() ([]*map[string]interface{}, bool) {
	if o == nil {
		return nil, false
	}
	return o.Providers, true
}

// SetProviders sets field value
func (o *OAuthProvidersResponse) SetProviders(v []*map[string]interface{}) {
	o.Providers = v
}

func (o OAuthProvidersResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OAuthProvidersResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["providers"] = o.Providers
	return toSerialize, nil
}

func (o *OAuthProvidersResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"providers",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varOAuthProvidersResponse := _OAuthProvidersResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varOAuthProvidersResponse)

	if err != nil {
		return err
	}

	*o = OAuthProvidersResponse(varOAuthProvidersResponse)

	return err
}

type NullableOAuthProvidersResponse struct {
	value *OAuthProvidersResponse
	isSet bool
}

func (v NullableOAuthProvidersResponse) Get() *OAuthProvidersResponse {
	return v.value
}

func (v *NullableOAuthProvidersResponse) Set(val *OAuthProvidersResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableOAuthProvidersResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableOAuthProvidersResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOAuthProvidersResponse(val *OAuthProvidersResponse) *NullableOAuthProvidersResponse {
	return &NullableOAuthProvidersResponse{value: val, isSet: true}
}

func (v NullableOAuthProvidersResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOAuthProvidersResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


